In [1]:
import pandas as pd
import numpy as np

In [2]:
base = "https://raw.githubusercontent.com/"
url_agg = "zzhangusf/Predicting-Fantasy-Football-Points-Using-Machine-Learning/master/data/aggregated_2015.csv"
df_agg = pd.read_csv(base+url_agg)
#df_agg.columns

In [3]:
url_box = "zzhangusf/Predicting-Fantasy-Football-Points-Using-Machine-Learning/master/data/players_box_scores_2015.csv"
df_box = pd.read_csv(base+url_box)
#df_box.shape

## Normalizing Names

In [30]:
names_df = pd.read_csv('data/all_nfl_team_abbr.csv')
names_df.head(3)

,TeamName,fanduel_2015,statistics_2015,fantasy_2015,fanduel_2016,statistics_2016,fantasy_2016
0,Arizona Cardinals,ari,ARI,ARI,ari,ARI,ARI
1,Atlanta Falcons,atl,ATL,ATL,atl,ATL,ATL
2,Baltimore Ravens,bal,BAL,BAL,bal,BAL,BAL

In [31]:
names_df.replace({"Oakland Raiders": "Las Vegas Raiders", \
                  "San Diego Chargers": "Los Angeles Chargers", \
                 "St.Louis / Los Angeles Rams": "Los Angeles Rams"}, inplace=True)

names_df.sort_values('TeamName', inplace=True)
names_df.drop(names_df.columns[1:], axis=1, inplace=True)

In [32]:
def get_unique_team_names(df, col):
    temp_df = pd.read_csv(df) 
    temp_list = list(temp_df[col].unique())
    temp_list.sort()
    return temp_list

In [33]:
import glob

temp_lists=[]
temp_cols=[]
for file in glob.glob('data/*_Fanduel_Results.csv'):
    temp_list = get_unique_team_names(file, 'Team')
    temp_col = file
    temp_cols.append(temp_col)
    temp_lists.append(temp_list)

In [34]:
print(temp_lists, temp_cols)

[['ari', 'atl', 'bal', 'buf', 'car', 'chi', 'cin', 'cle', 'dal', 'den', 'det', 'gnb', 'hou', 'ind', 'jac', 'kan', 'lac', 'lar', 'mia', 'min', 'nor', 'nwe', 'nyg', 'nyj', 'oak', 'phi', 'pit', 'sea', 'sfo', 'tam', 'ten', 'was'], ['ari', 'atl', 'bal', 'buf', 'car', 'chi', 'cin', 'cle', 'dal', 'den', 'det', 'gnb', 'hou', 'ind', 'jac', 'kan', 'lac', 'lar', 'lvr', 'mia', 'min', 'nor', 'nwe', 'nyg', 'nyj', 'phi', 'pit', 'sea', 'sfo', 'tam', 'ten', 'was'], ['ari', 'atl', 'bal', 'buf', 'car', 'chi', 'cin', 'cle', 'dal', 'den', 'det', 'gnb', 'hou', 'ind', 'jac', 'kan', 'lac', 'lar', 'lvr', 'mia', 'min', 'nor', 'nwe', 'nyg', 'nyj', 'phi', 'pit', 'sea', 'sfo', 'tam', 'ten', 'was'], ['ari', 'atl', 'bal', 'buf', 'car', 'chi', 'cin', 'cle', 'dal', 'den', 'det', 'gnb', 'hou', 'ind', 'jac', 'kan', 'lac', 'lar', 'mia', 'min', 'nor', 'nwe', 'nyg', 'nyj', 'oak', 'phi', 'pit', 'sea', 'sfo', 'tam', 'ten', 'was']] ['data/2018_Fanduel_Results.csv', 'data/2020_Fanduel_Results.csv', 'data/2021_Fanduel_Results.csv', 'data/2019_Fanduel_Results.csv']

In [36]:
names_df
names_df

                TeamName
0      Arizona Cardinals
1        Atlanta Falcons
2       Baltimore Ravens
3          Buffalo Bills
4      Carolina Panthers
5          Chicago Bears
6     Cincinnati Bengals
7       Cleveland Browns
8         Dallas Cowboys
9         Denver Broncos
10         Detroit Lions
11     Green Bay Packers
12        Houston Texans
13    Indianapolis Colts
14  Jacksonville Jaguars
15    Kansas City Chiefs
22     Las Vegas Raiders
25  Los Angeles Chargers
28      Los Angeles Rams
16        Miami Dolphins
17     Minnesota Vikings
18  New England Patriots
19     New Orlean Saints
20       New York Giants
21         New York Jets
23   Philadelphia Eagles
24   Pittsburgh Steelers
27   San Francisco 49ers
26      Seattle Seahawks
29  Tampa Bay Buccaneers
30      Tennessee Titans
31   Washington Redskins