In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("contest-standings-113707720.csv", low_memory=False)
df

,Rank,EntryId,EntryName,TimeRemaining,Points,Lineup,Unnamed: 6,Player,Roster Position,%Drafted,FPTS
0,1,2835322889,rwagner74,0,146.04999,FLEX Davante Adams FLEX Aaron Rodgers FLEX Rob...,NaN,Aaron Rodgers,FLEX,71.42%,26.80
1,1,2836661081,filsmif (19/20),0,146.04999,FLEX Davante Adams FLEX Aaron Rodgers FLEX Rob...,NaN,Davante Adams,FLEX,69.78%,23.10
2,1,2836983240,tattedmomma,0,146.04999,FLEX Davante Adams FLEX Aaron Rodgers FLEX Rob...,NaN,Jared Goff,FLEX,48.30%,20.44
3,1,2840233099,BigGuy2006 (6/20),0,146.04999,FLEX Davante Adams FLEX Aaron Rodgers FLEX Rob...,NaN,Aaron Jones,FLEX,44.99%,41.50
4,1,2840615099,hornets0875 (2/2),0,146.04999,FLEX Davante Adams FLEX Aaron Rodgers FLEX Rob...,NaN,T.J. Hockenson,CPT,44.70%,30.90
...,...,...,...,...,...,...,...,...,...,...,...
89174,88574,2844279370,thecrownjoel (17/20),0,0.00000,NaN,NaN,NaN,NaN,NaN,NaN
89175,88574,2844279371,thecrownjoel (18/20),0,0.00000,NaN,NaN,NaN,NaN,NaN,NaN
89176,88574,2844279372,thecrownjoel (19/20),0,0.00000,NaN,NaN,NaN,NaN,NaN,NaN
89177,88574,2844279373,thecrownjoel (20/20),0,0.00000,NaN,NaN,NaN,NaN,NaN,NaN
89178,88574,2844281110,Superball9999 (2/2),0,0.00000,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
def create_lineup_frame(df):
    df = df.Lineup.str.split(r'(FLEX|CPT)', expand=True)
    replace_values = {"": np.nan, " ": np.nan, "FLEX": np.nan, "CPT": np.nan}
    df.replace(replace_values, inplace=True)
    df = df.dropna(axis=1, how='all')
    df = df.dropna(axis=0, how='all')
    cols = ['FLEX', 'FLEX', 'FLEX', 'FLEX', 'FLEX', 'CPT']
    df.columns = cols
    return df

create_lineup_frame(df)

,FLEX,FLEX,FLEX,FLEX,FLEX,CPT
0,Davante Adams,Aaron Rodgers,Robert Tonyan,Quintez Cephus,Trinity Benson,Aaron Jones
1,Davante Adams,Aaron Rodgers,Robert Tonyan,Quintez Cephus,Trinity Benson,Aaron Jones
2,Davante Adams,Aaron Rodgers,Robert Tonyan,Quintez Cephus,Trinity Benson,Aaron Jones
3,Davante Adams,Aaron Rodgers,Robert Tonyan,Quintez Cephus,Trinity Benson,Aaron Jones
4,Davante Adams,Aaron Rodgers,Robert Tonyan,Quintez Cephus,Trinity Benson,Aaron Jones
...,...,...,...,...,...,...
88568,Darren Fells,Trinity Benson,Marcedes Lewis,Malik Taylor,Amari Rodgers,Randall Cobb
88569,Darren Fells,Trinity Benson,Marcedes Lewis,Malik Taylor,Amari Rodgers,Randall Cobb
88570,Darren Fells,Trinity Benson,Marcedes Lewis,Malik Taylor,Amari Rodgers,Randall Cobb
88571,Darren Fells,Trinity Benson,Marcedes Lewis,Malik Taylor,Amari Rodgers,Randall Cobb
88572,Trinity Benson,Marcedes Lewis,Malik Taylor,Amari Rodgers,KhaDarel Hodge,AJ Dillon

In [4]:
def track_players(df):
    df = df.dropna(axis=0, subset=["Lineup"])
    df = df.EntryName.str.split("(", expand=True)
    cols = ['Player', 'Drop']
    df.columns = cols
    df = df.Player
    return df

track_players(df)

0           rwagner74
1            filsmif
2         tattedmomma
3         BigGuy2006
4        hornets0875
             ...
88568     dgeschwind
88569     dgeschwind
88570     dgeschwind
88571     dgeschwind
88572        serp101
Name: Player, Length: 88573, dtype: object