In [7]:
import requests
from bs4 import BeautifulSoup as soup
import pandas as pd

In [8]:
df_fd_temp = pd.read_csv("data/nfl/FanDuel-NFL-2021 ET-10 ET-17 ET-65217-players-list.csv")
df_fd = df_fd_temp.convert_dtypes()
df_fd.head()

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
0,65217-55050,RB,Christian,Christian McCaffrey,McCaffrey,16.800001,3,10000,MIN@CAR,CAR,MIN,IR,Hamstring,<NA>,<NA>,<NA>,RB/FLEX
1,65217-57439,QB,Patrick,Patrick Mahomes,Mahomes,27.379999,5,9000,KC@WAS,KC,WAS,<NA>,<NA>,<NA>,<NA>,<NA>,QB
2,65217-54140,RB,Dalvin,Dalvin Cook,Cook,12.866666,3,8800,MIN@CAR,MIN,CAR,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
3,65217-53681,WR,Tyreek,Tyreek Hill,Hill,19.32,5,8700,KC@WAS,KC,WAS,Q,Quadriceps,<NA>,<NA>,<NA>,WR/FLEX
4,65217-33076,TE,Travis,Travis Kelce,Kelce,15.18,5,8500,KC@WAS,KC,WAS,<NA>,<NA>,<NA>,<NA>,<NA>,TE/FLEX

In [9]:
import glob

df_list = []
for file in glob.glob('data/nfl/FantasyPros_Fantasy_Football_Projections_*.csv'):
    temp_df = pd.read_csv(file)
    #print(temp_df.columns)
    temp_df = temp_df[['Player', 'FPTS']]
    df_list.append(temp_df)
    
proj_df = pd.concat(df_list, axis=0)
proj_df.dropna(inplace=True)

proj_df

                   Player  FPTS
1           Derrick Henry  16.9
2             Kareem Hunt  16.8
3         Jonathan Taylor  16.1
4            Najee Harris  16.1
5           Austin Ekeler  15.7
..                    ...   ...
153    Stanley Morgan Jr.   0.2
154  Antonio Gandy-Golden   0.2
155          Kirk Merritt   0.2
156         Andy Isabella   0.2
157        Antoine Wesley   0.1

[478 rows x 2 columns]

In [10]:
replace_dict = {"Patrick Mahomes II":"Patrick Mahomes", }
clean_players = [replace_dict.get(item,item) for item in proj_df.Player]
proj_df['Player'] = clean_players

In [11]:
df_fd = df_fd.merge(proj_df, how='left', left_on='Nickname', right_on='Player')
df_fd

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position,Player,FPTS
0,65217-55050,RB,Christian,Christian McCaffrey,McCaffrey,16.800001,3,10000,MIN@CAR,CAR,MIN,IR,Hamstring,<NA>,<NA>,<NA>,RB/FLEX,NaN,NaN
1,65217-57439,QB,Patrick,Patrick Mahomes,Mahomes,27.379999,5,9000,KC@WAS,KC,WAS,<NA>,<NA>,<NA>,<NA>,<NA>,QB,Patrick Mahomes,26.3
2,65217-54140,RB,Dalvin,Dalvin Cook,Cook,12.866666,3,8800,MIN@CAR,MIN,CAR,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX,Dalvin Cook,14.4
3,65217-53681,WR,Tyreek,Tyreek Hill,Hill,19.32,5,8700,KC@WAS,KC,WAS,Q,Quadriceps,<NA>,<NA>,<NA>,WR/FLEX,Tyreek Hill,14.8
4,65217-33076,TE,Travis,Travis Kelce,Kelce,15.18,5,8500,KC@WAS,KC,WAS,<NA>,<NA>,<NA>,<NA>,<NA>,TE/FLEX,Travis Kelce,13.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,65217-12548,D,Los Angeles,Los Angeles Chargers,Chargers,4.6,5,3600,LAC@BAL,LAC,BAL,<NA>,<NA>,<NA>,<NA>,<NA>,DEF,Los Angeles Chargers,5.9
647,65217-12527,D,Chicago,Chicago Bears,Bears,8.6,5,3500,GB@CHI,CHI,GB,<NA>,<NA>,<NA>,<NA>,<NA>,DEF,Chicago Bears,5.3
648,65217-12556,D,Houston,Houston Texans,Texans,3.8,5,3400,HOU@IND,HOU,IND,<NA>,<NA>,<NA>,<NA>,<NA>,DEF,Houston Texans,5.6
649,65217-12543,D,New York,New York Giants,Giants,3.2,5,3200,LAR@NYG,NYG,LAR,<NA>,<NA>,<NA>,<NA>,<NA>,DEF,New York Giants,5.0
650,65217-12552,D,Washington,Washington Football Team,Football Team,3.4,5,3000,KC@WAS,WAS,KC,<NA>,<NA>,<NA>,<NA>,<NA>,DEF,Washington Football Team,5.3

In [13]:
df_fd["FPPG"] = df_fd["FPTS"]
df_fd.drop(labels = ["Player", "FPTS"], axis=1, inplace=True)
df_fd.head(3)

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
0,65217-55050,RB,Christian,Christian McCaffrey,McCaffrey,NaN,3,10000,MIN@CAR,CAR,MIN,IR,Hamstring,<NA>,<NA>,<NA>,RB/FLEX
1,65217-57439,QB,Patrick,Patrick Mahomes,Mahomes,26.3,5,9000,KC@WAS,KC,WAS,<NA>,<NA>,<NA>,<NA>,<NA>,QB
2,65217-54140,RB,Dalvin,Dalvin Cook,Cook,14.4,3,8800,MIN@CAR,MIN,CAR,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
3,65217-53681,WR,Tyreek,Tyreek Hill,Hill,14.8,5,8700,KC@WAS,KC,WAS,Q,Quadriceps,<NA>,<NA>,<NA>,WR/FLEX
4,65217-33076,TE,Travis,Travis Kelce,Kelce,13.3,5,8500,KC@WAS,KC,WAS,<NA>,<NA>,<NA>,<NA>,<NA>,TE/FLEX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,65217-12548,D,Los Angeles,Los Angeles Chargers,Chargers,5.9,5,3600,LAC@BAL,LAC,BAL,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
647,65217-12527,D,Chicago,Chicago Bears,Bears,5.3,5,3500,GB@CHI,CHI,GB,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
648,65217-12556,D,Houston,Houston Texans,Texans,5.6,5,3400,HOU@IND,HOU,IND,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
649,65217-12543,D,New York,New York Giants,Giants,5.0,5,3200,LAR@NYG,NYG,LAR,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
650,65217-12552,D,Washington,Washington Football Team,Football Team,5.3,5,3000,KC@WAS,WAS,KC,<NA>,<NA>,<NA>,<NA>,<NA>,DEF

In [14]:
df_fd.to_csv('data/nfl/FDprojections.csv')

In [17]:
from pydfs_lineup_optimizer import Site, Sport, get_optimizer, PlayerFilter, AfterEachExposureStrategy, TeamStack

optimizer = get_optimizer(Site.FANDUEL, Sport.FOOTBALL)
optimizer.load_players_from_csv("data/nfl/FDprojections.csv")
optimizer.add_stack(TeamStack(3, for_positions=['QB', 'WR', 'TE']))
#optimizer.add_stack(TeamStack(2, for_positions=['RB', 'D']))
for lineup in optimizer.optimize(40, max_exposure=0.4, exposure_strategy=AfterEachExposureStrategy):
    print(lineup)
optimizer.export('data/nfl/fd_result.csv')

 1. QB      Lamar Jackson                 QB    BAL            LAC@BAL  24.1           8200.0$
 2. RB      Darrel Williams               RB    KC             KC@WAS   10.5           5200.0$
 3. RB      Jonathan Taylor               RB    IND            HOU@IND  16.1           7500.0$
 4. WR      Cooper Kupp                   WR    LAR            LAR@NYG  13.6           8200.0$
 5. WR      Davante Adams                 WR    GB             GB@CHI   15.0           8500.0$
 6. WR      Marquise Brown                WR    BAL            LAC@BAL  11.2           7000.0$
 7. TE      Mark Andrews                  TE    BAL            LAC@BAL  10.5           6300.0$
 8. FLEX    Khalil Herbert                RB    CHI            GB@CHI   11.3           5500.0$
 9. DEF     Cleveland Browns              D     CLE            ARI@CLE  6.1            3600.0$

Fantasy Points 118.40
Salary 60000.00

 1. QB      Patrick Mahomes               QB    KC             KC@WAS   26.3           9000.0$
 2. RB      Austin Ekeler                 RB    LAC            LAC@BAL  15.7           8400.0$
 3. RB      Chuba Hubbard                 RB    CAR            MIN@CAR  12.0           6900.0$
 4. WR      Brandin Cooks                 WR    HOU            HOU@IND  10.6           6500.0$
 5. WR      Mecole Hardman                WR    KC             KC@WAS   6.9            5500.0$
 6. WR      Michael Pittman Jr.           WR    IND            HOU@IND  9.6            5800.0$
 7. TE      Travis Kelce                  TE    KC             KC@WAS   13.3           8500.0$
 8. FLEX    Javonte Williams              RB    DEN            LV@DEN   8.8            5600.0$
 9. DEF     Minnesota Vikings             D     MIN            MIN@CAR  7.0            3700.0$

Fantasy Points 110.20
Salary 59900.00

 1. QB      Justin Herbert                QB    LAC            LAC@BAL  22.3           8000.0$
 2. RB      Aaron Jones                   RB    GB             GB@CHI   14.1           8000.0$
 3. RB      Darrell Henderson Jr.         RB    LAR            LAR@NYG  13.2           7300.0$
 4. WR      Courtland Sutton              WR    DEN            LV@DEN   10.3           6600.0$
 5. WR      Keenan Allen                  WR    LAC            LAC@BAL  10.5           7100.0$
 6. WR      Robert Woods                  WR    LAR            LAR@NYG  10.3           6900.0$
 7. TE      Jared Cook                    TE    LAC            LAC@BAL  6.2            5400.0$
 8. FLEX    Devontae Booker               RB    NYG            LAR@NYG  9.3            5900.0$
 9. DEF     Indianapolis Colts            D     IND            HOU@IND  8.4            4700.0$

Fantasy Points 104.60
Salary 59900.00

 1. QB      Lamar Jackson                 QB    BAL            LAC@BAL  24.1           8200.0$
 2. RB      Darrel Williams               RB    KC             KC@WAS   10.5           5200.0$
 3. RB      Jonathan Taylor               RB    IND            HOU@IND  16.1           7500.0$
 4. WR      Cooper Kupp                   WR    LAR            LAR@NYG  13.6           8200.0$
 5. WR      Davante Adams                 WR    GB             GB@CHI   15.0           8500.0$
 6. WR      Marquise Brown                WR    BAL            LAC@BAL  11.2           7000.0$
 7. TE      Mark Andrews                  TE    BAL            LAC@BAL  10.5           6300.0$
 8. FLEX    Khalil Herbert                RB    CHI            GB@CHI   11.3           5500.0$
 9. DEF     Los Angeles Chargers          D     LAC            LAC@BAL  5.9            3600.0$

Fantasy Points 118.20
Salary 60000.00

 1. QB      Patrick Mahomes               QB    KC             KC@WAS   26.3           9000.0$
 2. RB      Austin Ekeler                 RB    LAC            LAC@BAL  15.7           8400.0$
 3. RB      Darrell Henderson Jr.         RB    LAR            LAR@NYG  13.2           7300.0$
 4. WR      Brandin Cooks                 WR    HOU            HOU@IND  10.6           6500.0$
 5. WR      Mecole Hardman                WR    KC             KC@WAS   6.9            5500.0$
 6. WR      Michael Pittman Jr.           WR    IND            HOU@IND  9.6            5800.0$
 7. TE      Travis Kelce                  TE    KC             KC@WAS   13.3           8500.0$
 8. FLEX    Devontae Booker               RB    NYG            LAR@NYG  9.3            5900.0$
 9. DEF     Washington Football Team      D     WAS            KC@WAS   5.3            3000.0$

Fantasy Points 110.20
Salary 59900.00

 1. QB      Kyler Murray                  QB    ARI            ARI@CLE  22.6           8400.0$
 2. RB      Aaron Jones                   RB    GB             GB@CHI   14.1           8000.0$
 3. RB      Chuba Hubbard                 RB    CAR            MIN@CAR  12.0           6900.0$
 4. WR      Courtland Sutton              WR    DEN            LV@DEN   10.3           6600.0$
 5. WR      John Brown                    WR    DEN            LV@DEN   4.9            4500.0$
 6. WR      Tim Patrick                   WR    DEN            LV@DEN   8.5            6100.0$
 7. TE      Darren Waller                 TE    LV             LV@DEN   10.3           7000.0$
 8. FLEX    Dalvin Cook                   RB    MIN            MIN@CAR  14.4           8800.0$
 9. DEF     Minnesota Vikings             D     MIN            MIN@CAR  7.0            3700.0$

Fantasy Points 104.10
Salary 60000.00

 1. QB      Lamar Jackson                 QB    BAL            LAC@BAL  24.1           8200.0$
 2. RB      Darrell Henderson Jr.         RB    LAR            LAR@NYG  13.2           7300.0$
 3. RB      Jonathan Taylor               RB    IND            HOU@IND  16.1           7500.0$
 4. WR      Davante Adams                 WR    GB             GB@CHI   15.0           8500.0$
 5. WR      Marquise Brown                WR    BAL            LAC@BAL  11.2           7000.0$
 6. WR      Michael Pittman Jr.           WR    IND            HOU@IND  9.6            5800.0$
 7. TE      Mark Andrews                  TE    BAL            LAC@BAL  10.5           6300.0$
 8. FLEX    Khalil Herbert                RB    CHI            GB@CHI   11.3           5500.0$
 9. DEF     Minnesota Vikings             D     MIN            MIN@CAR  7.0            3700.0$

Fantasy Points 118.00
Salary 59800.00

 1. QB      Patrick Mahomes               QB    KC             KC@WAS   26.3           9000.0$
 2. RB      Austin Ekeler                 RB    LAC            LAC@BAL  15.7           8400.0$
 3. RB      Chuba Hubbard                 RB    CAR            MIN@CAR  12.0           6900.0$
 4. WR      Brandin Cooks                 WR    HOU            HOU@IND  10.6           6500.0$
 5. WR      Courtland Sutton              WR    DEN            LV@DEN   10.3           6600.0$
 6. WR      Mecole Hardman                WR    KC             KC@WAS   6.9            5500.0$
 7. TE      Travis Kelce                  TE    KC             KC@WAS   13.3           8500.0$
 8. FLEX    Darrel Williams               RB    KC             KC@WAS   10.5           5200.0$
 9. DEF     Houston Texans                D     HOU            HOU@IND  5.6            3400.0$

Fantasy Points 111.20
Salary 60000.00

 1. QB      Lamar Jackson                 QB    BAL            LAC@BAL  24.1           8200.0$
 2. RB      Austin Ekeler                 RB    LAC            LAC@BAL  15.7           8400.0$
 3. RB      Darrel Williams               RB    KC             KC@WAS   10.5           5200.0$
 4. WR      Davante Adams                 WR    GB             GB@CHI   15.0           8500.0$
 5. WR      Marquise Brown                WR    BAL            LAC@BAL  11.2           7000.0$
 6. WR      Michael Pittman Jr.           WR    IND            HOU@IND  9.6            5800.0$
 7. TE      Mark Andrews                  TE    BAL            LAC@BAL  10.5           6300.0$
 8. FLEX    Jonathan Taylor               RB    IND            HOU@IND  16.1           7500.0$
 9. DEF     Washington Football Team      D     WAS            KC@WAS   5.3            3000.0$

Fantasy Points 118.00
Salary 59900.00

 1. QB      Patrick Mahomes               QB    KC             KC@WAS   26.3           9000.0$
 2. RB      Chuba Hubbard                 RB    CAR            MIN@CAR  12.0           6900.0$
 3. RB      Darrell Henderson Jr.         RB    LAR            LAR@NYG  13.2           7300.0$
 4. WR      Brandin Cooks                 WR    HOU            HOU@IND  10.6           6500.0$
 5. WR      Courtland Sutton              WR    DEN            LV@DEN   10.3           6600.0$
 6. WR      Mecole Hardman                WR    KC             KC@WAS   6.9            5500.0$
 7. TE      Travis Kelce                  TE    KC             KC@WAS   13.3           8500.0$
 8. FLEX    Khalil Herbert                RB    CHI            GB@CHI   11.3           5500.0$
 9. DEF     Green Bay Packers             D     GB             GB@CHI   7.5            4200.0$

Fantasy Points 111.40
Salary 60000.00

 1. QB      Matthew Stafford              QB    LAR            LAR@NYG  20.5           7900.0$
 2. RB      Aaron Jones                   RB    GB             GB@CHI   14.1           8000.0$
 3. RB      Devontae Booker               RB    NYG            LAR@NYG  9.3            5900.0$
 4. WR      Amari Cooper                  WR    DAL            DAL@NE   10.2           6800.0$
 5. WR      Cooper Kupp                   WR    LAR            LAR@NYG  13.6           8200.0$
 6. WR      Robert Woods                  WR    LAR            LAR@NYG  10.3           6900.0$
 7. TE      Darren Waller                 TE    LV             LV@DEN   10.3           7000.0$
 8. FLEX    Javonte Williams              RB    DEN            LV@DEN   8.8            5600.0$
 9. DEF     Minnesota Vikings             D     MIN            MIN@CAR  7.0            3700.0$

Fantasy Points 104.10
Salary 60000.00

 1. QB      Lamar Jackson                 QB    BAL            LAC@BAL  24.1           8200.0$
 2. RB      Darrel Williams               RB    KC             KC@WAS   10.5           5200.0$
 3. RB      Jonathan Taylor               RB    IND            HOU@IND  16.1           7500.0$
 4. WR      Cooper Kupp                   WR    LAR            LAR@NYG  13.6           8200.0$
 5. WR      Davante Adams                 WR    GB             GB@CHI   15.0           8500.0$
 6. WR      Marquise Brown                WR    BAL            LAC@BAL  11.2           7000.0$
 7. TE      Mark Andrews                  TE    BAL            LAC@BAL  10.5           6300.0$
 8. FLEX    Khalil Herbert                RB    CHI            GB@CHI   11.3           5500.0$
 9. DEF     Houston Texans                D     HOU            HOU@IND  5.6            3400.0$

Fantasy Points 117.90
Salary 59800.00

 1. QB      Patrick Mahomes               QB    KC             KC@WAS   26.3           9000.0$
 2. RB      Austin Ekeler                 RB    LAC            LAC@BAL  15.7           8400.0$
 3. RB      Darrell Henderson Jr.         RB    LAR            LAR@NYG  13.2           7300.0$
 4. WR      Brandin Cooks                 WR    HOU            HOU@IND  10.6           6500.0$
 5. WR      Mecole Hardman                WR    KC             KC@WAS   6.9            5500.0$
 6. WR      Michael Pittman Jr.           WR    IND            HOU@IND  9.6            5800.0$
 7. TE      Travis Kelce                  TE    KC             KC@WAS   13.3           8500.0$
 8. FLEX    Javonte Williams              RB    DEN            LV@DEN   8.8            5600.0$
 9. DEF     Houston Texans                D     HOU            HOU@IND  5.6            3400.0$

Fantasy Points 110.00
Salary 60000.00

 1. QB      Lamar Jackson                 QB    BAL            LAC@BAL  24.1           8200.0$
 2. RB      Darrel Williams               RB    KC             KC@WAS   10.5           5200.0$
 3. RB      Jonathan Taylor               RB    IND            HOU@IND  16.1           7500.0$
 4. WR      Brandin Cooks                 WR    HOU            HOU@IND  10.6           6500.0$
 5. WR      Davante Adams                 WR    GB             GB@CHI   15.0           8500.0$
 6. WR      Marquise Brown                WR    BAL            LAC@BAL  11.2           7000.0$
 7. TE      Mark Andrews                  TE    BAL            LAC@BAL  10.5           6300.0$
 8. FLEX    Khalil Herbert                RB    CHI            GB@CHI   11.3           5500.0$
 9. DEF     Indianapolis Colts            D     IND            HOU@IND  8.4            4700.0$

Fantasy Points 117.70
Salary 59400.00

 1. QB      Patrick Mahomes               QB    KC             KC@WAS   26.3           9000.0$
 2. RB      Austin Ekeler                 RB    LAC            LAC@BAL  15.7           8400.0$
 3. RB      Chuba Hubbard                 RB    CAR            MIN@CAR  12.0           6900.0$
 4. WR      Courtland Sutton              WR    DEN            LV@DEN   10.3           6600.0$
 5. WR      Mecole Hardman                WR    KC             KC@WAS   6.9            5500.0$
 6. WR      Michael Pittman Jr.           WR    IND            HOU@IND  9.6            5800.0$
 7. TE      Travis Kelce                  TE    KC             KC@WAS   13.3           8500.0$
 8. FLEX    Javonte Williams              RB    DEN            LV@DEN   8.8            5600.0$
 9. DEF     Minnesota Vikings             D     MIN            MIN@CAR  7.0            3700.0$

Fantasy Points 109.90
Salary 60000.00

 1. QB      Justin Herbert                QB    LAC            LAC@BAL  22.3           8000.0$
 2. RB      Aaron Jones                   RB    GB             GB@CHI   14.1           8000.0$
 3. RB      Darrell Henderson Jr.         RB    LAR            LAR@NYG  13.2           7300.0$
 4. WR      Cooper Kupp                   WR    LAR            LAR@NYG  13.6           8200.0$
 5. WR      Courtland Sutton              WR    DEN            LV@DEN   10.3           6600.0$
 6. WR      Keenan Allen                  WR    LAC            LAC@BAL  10.5           7100.0$
 7. TE      Jared Cook                    TE    LAC            LAC@BAL  6.2            5400.0$
 8. FLEX    Javonte Williams              RB    DEN            LV@DEN   8.8            5600.0$
 9. DEF     Minnesota Vikings             D     MIN            MIN@CAR  7.0            3700.0$

Fantasy Points 106.00
Salary 59900.00

 1. QB      Lamar Jackson                 QB    BAL            LAC@BAL  24.1           8200.0$
 2. RB      Darrel Williams               RB    KC             KC@WAS   10.5           5200.0$
 3. RB      Darrell Henderson Jr.         RB    LAR            LAR@NYG  13.2           7300.0$
 4. WR      Davante Adams                 WR    GB             GB@CHI   15.0           8500.0$
 5. WR      Marquise Brown                WR    BAL            LAC@BAL  11.2           7000.0$
 6. WR      Michael Pittman Jr.           WR    IND            HOU@IND  9.6            5800.0$
 7. TE      Mark Andrews                  TE    BAL            LAC@BAL  10.5           6300.0$
 8. FLEX    Jonathan Taylor               RB    IND            HOU@IND  16.1           7500.0$
 9. DEF     Green Bay Packers             D     GB             GB@CHI   7.5            4200.0$

Fantasy Points 117.70
Salary 60000.00

 1. QB      Patrick Mahomes               QB    KC             KC@WAS   26.3           9000.0$
 2. RB      Austin Ekeler                 RB    LAC            LAC@BAL  15.7           8400.0$
 3. RB      Chuba Hubbard                 RB    CAR            MIN@CAR  12.0           6900.0$
 4. WR      Brandin Cooks                 WR    HOU            HOU@IND  10.6           6500.0$
 5. WR      Courtland Sutton              WR    DEN            LV@DEN   10.3           6600.0$
 6. WR      Mecole Hardman                WR    KC             KC@WAS   6.9            5500.0$
 7. TE      Travis Kelce                  TE    KC             KC@WAS   13.3           8500.0$
 8. FLEX    Khalil Herbert                RB    CHI            GB@CHI   11.3           5500.0$
 9. DEF     Washington Football Team      D     WAS            KC@WAS   5.3            3000.0$

Fantasy Points 111.70
Salary 59900.00

 1. QB      Lamar Jackson                 QB    BAL            LAC@BAL  24.1           8200.0$
 2. RB      Darrel Williams               RB    KC             KC@WAS   10.5           5200.0$
 3. RB      Jonathan Taylor               RB    IND            HOU@IND  16.1           7500.0$
 4. WR      Cooper Kupp                   WR    LAR            LAR@NYG  13.6           8200.0$
 5. WR      Davante Adams                 WR    GB             GB@CHI   15.0           8500.0$
 6. WR      Marquise Brown                WR    BAL            LAC@BAL  11.2           7000.0$
 7. TE      Mark Andrews                  TE    BAL            LAC@BAL  10.5           6300.0$
 8. FLEX    Khalil Herbert                RB    CHI            GB@CHI   11.3           5500.0$
 9. DEF     Washington Football Team      D     WAS            KC@WAS   5.3            3000.0$

Fantasy Points 117.60
Salary 59400.00

 1. QB      Patrick Mahomes               QB    KC             KC@WAS   26.3           9000.0$
 2. RB      Austin Ekeler                 RB    LAC            LAC@BAL  15.7           8400.0$
 3. RB      Darrell Henderson Jr.         RB    LAR            LAR@NYG  13.2           7300.0$
 4. WR      Courtland Sutton              WR    DEN            LV@DEN   10.3           6600.0$
 5. WR      Mecole Hardman                WR    KC             KC@WAS   6.9            5500.0$
 6. WR      Michael Pittman Jr.           WR    IND            HOU@IND  9.6            5800.0$
 7. TE      Travis Kelce                  TE    KC             KC@WAS   13.3           8500.0$
 8. FLEX    Devontae Booker               RB    NYG            LAR@NYG  9.3            5900.0$
 9. DEF     Washington Football Team      D     WAS            KC@WAS   5.3            3000.0$

Fantasy Points 109.90
Salary 60000.00

 1. QB      Justin Herbert                QB    LAC            LAC@BAL  22.3           8000.0$
 2. RB      Aaron Jones                   RB    GB             GB@CHI   14.1           8000.0$
 3. RB      Chuba Hubbard                 RB    CAR            MIN@CAR  12.0           6900.0$
 4. WR      Brandin Cooks                 WR    HOU            HOU@IND  10.6           6500.0$
 5. WR      Cooper Kupp                   WR    LAR            LAR@NYG  13.6           8200.0$
 6. WR      Keenan Allen                  WR    LAC            LAC@BAL  10.5           7100.0$
 7. TE      Jared Cook                    TE    LAC            LAC@BAL  6.2            5400.0$
 8. FLEX    Devontae Booker               RB    NYG            LAR@NYG  9.3            5900.0$
 9. DEF     Minnesota Vikings             D     MIN            MIN@CAR  7.0            3700.0$

Fantasy Points 105.60
Salary 59700.00

 1. QB      Lamar Jackson                 QB    BAL            LAC@BAL  24.1           8200.0$
 2. RB      Darrel Williams               RB    KC             KC@WAS   10.5           5200.0$
 3. RB      Jonathan Taylor               RB    IND            HOU@IND  16.1           7500.0$
 4. WR      Davante Adams                 WR    GB             GB@CHI   15.0           8500.0$
 5. WR      Ja'Marr Chase                 WR    CIN            CIN@DET  11.9           7800.0$
 6. WR      Marquise Brown                WR    BAL            LAC@BAL  11.2           7000.0$
 7. TE      Mark Andrews                  TE    BAL            LAC@BAL  10.5           6300.0$
 8. FLEX    Khalil Herbert                RB    CHI            GB@CHI   11.3           5500.0$
 9. DEF     Minnesota Vikings             D     MIN            MIN@CAR  7.0            3700.0$

Fantasy Points 117.60
Salary 59700.00

 1. QB      Patrick Mahomes               QB    KC             KC@WAS   26.3           9000.0$
 2. RB      Austin Ekeler                 RB    LAC            LAC@BAL  15.7           8400.0$
 3. RB      Darrell Henderson Jr.         RB    LAR            LAR@NYG  13.2           7300.0$