from functions.clean_data import archive_files

archive_files()

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_fd = pd.read_csv("data/nfl/FanDuel-NFL-2021 ET-10 ET-18 ET-65439-players-list.csv")

In [3]:
import glob

df_list = []
for file in glob.glob('data/nfl/FantasyPros_Fantasy_Football_Projections_*.csv'):
    temp_df = pd.read_csv(file)
    #print(temp_df.columns)
    temp_df = temp_df[['Player', 'FPTS']]
    df_list.append(temp_df)
    
proj_df = pd.concat(df_list, axis=0)
proj_df.dropna(inplace=True)

proj_df

                   Player  FPTS
1           Derrick Henry  16.9
2             Kareem Hunt  16.8
3         Jonathan Taylor  16.1
4            Najee Harris  16.1
5           Austin Ekeler  15.7
..                    ...   ...
153    Stanley Morgan Jr.   0.2
154  Antonio Gandy-Golden   0.2
155          Kirk Merritt   0.2
156         Andy Isabella   0.2
157        Antoine Wesley   0.1

[478 rows x 2 columns]

In [4]:
df_fd.head()

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
0,65439-62239,QB,Josh,Josh Allen,Allen,25.920001,5.0,17000,BUF@TEN,BUF,TEN,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
1,65439-39280,RB,Derrick,Derrick Henry,Henry,25.500000,5.0,15500,BUF@TEN,TEN,BUF,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
2,65439-21948,QB,Ryan,Ryan Tannehill,Tannehill,17.208000,5.0,14000,BUF@TEN,TEN,BUF,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
3,65439-25079,WR,Stefon,Stefon Diggs,Diggs,11.480000,5.0,12500,BUF@TEN,BUF,TEN,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
4,65439-72846,WR,A.J.,A.J. Brown,Brown,6.075000,4.0,11500,BUF@TEN,TEN,BUF,Q,Illness,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX

In [5]:
df_fd.columns

Index(['Id', 'Position', 'First Name', 'Nickname', 'Last Name', 'FPPG',
       'Played', 'Salary', 'Game', 'Team', 'Opponent', 'Injury Indicator',
       'Injury Details', 'Tier', 'Unnamed: 14', 'Unnamed: 15',
       'Roster Position'],
      dtype='object')

In [6]:
#df.drop(df.dropna(subset=['columnA']).index)
df_fd = df_fd.drop(df_fd.dropna(subset=['Injury Indicator']).index)
#df_fd = df_fd.query("Position != 'QB' or Nickname == 'Tom Brady' or Nickname == 'Jalen Hurts'")
df_fd.head()

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
0,65439-62239,QB,Josh,Josh Allen,Allen,25.920001,5.0,17000,BUF@TEN,BUF,TEN,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
1,65439-39280,RB,Derrick,Derrick Henry,Henry,25.500000,5.0,15500,BUF@TEN,TEN,BUF,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
2,65439-21948,QB,Ryan,Ryan Tannehill,Tannehill,17.208000,5.0,14000,BUF@TEN,TEN,BUF,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
3,65439-25079,WR,Stefon,Stefon Diggs,Diggs,11.480000,5.0,12500,BUF@TEN,BUF,TEN,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
5,65439-14190,WR,Julio,Julio Jones,Jones,8.800000,3.0,11000,BUF@TEN,TEN,BUF,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX

In [7]:
df_fd = df_fd.merge(proj_df, how='left', left_on='Nickname', right_on='Player')
df_fd.head(3)

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position,Player,FPTS
0,65439-62239,QB,Josh,Josh Allen,Allen,25.920001,5.0,17000,BUF@TEN,BUF,TEN,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX,Josh Allen,26.3
1,65439-39280,RB,Derrick,Derrick Henry,Henry,25.500000,5.0,15500,BUF@TEN,TEN,BUF,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX,Derrick Henry,16.9
2,65439-21948,QB,Ryan,Ryan Tannehill,Tannehill,17.208000,5.0,14000,BUF@TEN,TEN,BUF,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX,Ryan Tannehill,16.9

In [8]:
df_fd["FPPG"] = df_fd["FPTS"]
df_fd.drop(labels = ["Player", "FPTS"], axis=1, inplace=True)
df_fd.head(3)

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
0,65439-62239,QB,Josh,Josh Allen,Allen,26.3,5.0,17000,BUF@TEN,BUF,TEN,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
1,65439-39280,RB,Derrick,Derrick Henry,Henry,16.9,5.0,15500,BUF@TEN,TEN,BUF,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
2,65439-21948,QB,Ryan,Ryan Tannehill,Tannehill,16.9,5.0,14000,BUF@TEN,TEN,BUF,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX

In [9]:
df_fd.set_index('Id',inplace=True)

In [10]:
df_fd.to_csv('data/nfl/FDprojectionsSD.csv')

In [12]:
from pydfs_lineup_optimizer import Site, Sport, get_optimizer, PlayerFilter, AfterEachExposureStrategy

optimizer = get_optimizer(Site.FANDUEL_SINGLE_GAME, Sport.FOOTBALL)
optimizer.load_players_from_csv("data/nfl/FDprojectionsSD.csv")
for lineup in optimizer.optimize(20, max_exposure=0.5, exposure_strategy=AfterEachExposureStrategy):
    print(lineup)
optimizer.export('data/nfl/fd_resultSD.csv')

 1. MVP     Josh Allen                    QB    BUF            BUF@TEN  39.45          17000.0$
 2. UTIL    Cole Beasley                  WR    BUF            BUF@TEN  7.3            7500.0$
 3. UTIL    Ryan Tannehill                QB    TEN            BUF@TEN  16.9           14000.0$
 4. UTIL    Stefon Diggs                  WR    BUF            BUF@TEN  12.9           12500.0$
 5. UTIL    Tyler Bass                    K     BUF            BUF@TEN  8.0            9000.0$

Fantasy Points 84.55
Salary 60000.00

 1. MVP     Ryan Tannehill                QB    TEN            BUF@TEN  25.35          14000.0$
 2. UTIL    Dawson Knox                   TE    BUF            BUF@TEN  7.5            9000.0$
 3. UTIL    Emmanuel Sanders              WR    BUF            BUF@TEN  9.6            10000.0$
 4. UTIL    Josh Allen                    QB    BUF            BUF@TEN  26.3           17000.0$
 5. UTIL    Zack Moss                     RB    BUF            BUF@TEN  10.0           9500.0$

Fantasy Points 78.75
Salary 59500.00

 1. MVP     Stefon Diggs                  WR    BUF            BUF@TEN  19.35          12500.0$
 2. UTIL    Derrick Henry                 RB    TEN            BUF@TEN  16.9           15500.0$
 3. UTIL    Devin Singletary              RB    BUF            BUF@TEN  6.3            8000.0$
 4. UTIL    Julio Jones                   WR    TEN            BUF@TEN  7.4            11000.0$
 5. UTIL    Randy Bullock                 K     TEN            BUF@TEN  7.4            8000.0$

Fantasy Points 57.35
Salary 55000.00

 1. MVP     Josh Allen                    QB    BUF            BUF@TEN  39.45          17000.0$
 2. UTIL    Anthony Firkser               TE    TEN            BUF@TEN  3.6            6000.0$
 3. UTIL    Cole Beasley                  WR    BUF            BUF@TEN  7.3            7500.0$
 4. UTIL    Derrick Henry                 RB    TEN            BUF@TEN  16.9           15500.0$
 5. UTIL    Ryan Tannehill                QB    TEN            BUF@TEN  16.9           14000.0$

Fantasy Points 84.15
Salary 60000.00

 1. MVP     Ryan Tannehill                QB    TEN            BUF@TEN  25.35          14000.0$
 2. UTIL    Emmanuel Sanders              WR    BUF            BUF@TEN  9.6            10000.0$
 3. UTIL    Josh Allen                    QB    BUF            BUF@TEN  26.3           17000.0$
 4. UTIL    Tyler Bass                    K     BUF            BUF@TEN  8.0            9000.0$
 5. UTIL    Zack Moss                     RB    BUF            BUF@TEN  10.0           9500.0$

Fantasy Points 79.25
Salary 59500.00

 1. MVP     Josh Allen                    QB    BUF            BUF@TEN  39.45          17000.0$
 2. UTIL    Cole Beasley                  WR    BUF            BUF@TEN  7.3            7500.0$
 3. UTIL    Dawson Knox                   TE    BUF            BUF@TEN  7.5            9000.0$
 4. UTIL    Ryan Tannehill                QB    TEN            BUF@TEN  16.9           14000.0$
 5. UTIL    Stefon Diggs                  WR    BUF            BUF@TEN  12.9           12500.0$

Fantasy Points 84.05
Salary 60000.00

 1. MVP     Ryan Tannehill                QB    TEN            BUF@TEN  25.35          14000.0$
 2. UTIL    Emmanuel Sanders              WR    BUF            BUF@TEN  9.6            10000.0$
 3. UTIL    Josh Allen                    QB    BUF            BUF@TEN  26.3           17000.0$
 4. UTIL    Randy Bullock                 K     TEN            BUF@TEN  7.4            8000.0$
 5. UTIL    Zack Moss                     RB    BUF            BUF@TEN  10.0           9500.0$

Fantasy Points 78.65
Salary 58500.00

 1. MVP     Josh Allen                    QB    BUF            BUF@TEN  39.45          17000.0$
 2. UTIL    Emmanuel Sanders              WR    BUF            BUF@TEN  9.6            10000.0$
 3. UTIL    Ryan Tannehill                QB    TEN            BUF@TEN  16.9           14000.0$
 4. UTIL    Tyler Bass                    K     BUF            BUF@TEN  8.0            9000.0$
 5. UTIL    Zack Moss                     RB    BUF            BUF@TEN  10.0           9500.0$

Fantasy Points 83.95
Salary 59500.00

 1. MVP     Ryan Tannehill                QB    TEN            BUF@TEN  25.35          14000.0$
 2. UTIL    Cole Beasley                  WR    BUF            BUF@TEN  7.3            7500.0$
 3. UTIL    Josh Allen                    QB    BUF            BUF@TEN  26.3           17000.0$
 4. UTIL    Stefon Diggs                  WR    BUF            BUF@TEN  12.9           12500.0$
 5. UTIL    Tyler Bass                    K     BUF            BUF@TEN  8.0            9000.0$

Fantasy Points 79.85
Salary 60000.00

 1. MVP     Josh Allen                    QB    BUF            BUF@TEN  39.45          17000.0$
 2. UTIL    Cole Beasley                  WR    BUF            BUF@TEN  7.3            7500.0$
 3. UTIL    Randy Bullock                 K     TEN            BUF@TEN  7.4            8000.0$
 4. UTIL    Ryan Tannehill                QB    TEN            BUF@TEN  16.9           14000.0$
 5. UTIL    Stefon Diggs                  WR    BUF            BUF@TEN  12.9           12500.0$

Fantasy Points 83.95
Salary 59000.00

 1. MVP     Derrick Henry                 RB    TEN            BUF@TEN  25.35          15500.0$
 2. UTIL    Emmanuel Sanders              WR    BUF            BUF@TEN  9.6            10000.0$
 3. UTIL    Josh Allen                    QB    BUF            BUF@TEN  26.3           17000.0$
 4. UTIL    Randy Bullock                 K     TEN            BUF@TEN  7.4            8000.0$
 5. UTIL    Zack Moss                     RB    BUF            BUF@TEN  10.0           9500.0$

Fantasy Points 78.65
Salary 60000.00

 1. MVP     Josh Allen                    QB    BUF            BUF@TEN  39.45          17000.0$
 2. UTIL    Cole Beasley                  WR    BUF            BUF@TEN  7.3            7500.0$
 3. UTIL    Derrick Henry                 RB    TEN            BUF@TEN  16.9           15500.0$
 4. UTIL    Marcus Johnson                WR    TEN            BUF@TEN  2.9            6000.0$
 5. UTIL    Ryan Tannehill                QB    TEN            BUF@TEN  16.9           14000.0$

Fantasy Points 83.45
Salary 60000.00

 1. MVP     Ryan Tannehill                QB    TEN            BUF@TEN  25.35          14000.0$
 2. UTIL    Devin Singletary              RB    BUF            BUF@TEN  6.3            8000.0$
 3. UTIL    Josh Allen                    QB    BUF            BUF@TEN  26.3           17000.0$
 4. UTIL    Randy Bullock                 K     TEN            BUF@TEN  7.4            8000.0$
 5. UTIL    Stefon Diggs                  WR    BUF            BUF@TEN  12.9           12500.0$

Fantasy Points 78.25
Salary 59500.00

 1. MVP     Josh Allen                    QB    BUF            BUF@TEN  39.45          17000.0$
 2. UTIL    Dawson Knox                   TE    BUF            BUF@TEN  7.5            9000.0$
 3. UTIL    Emmanuel Sanders              WR    BUF            BUF@TEN  9.6            10000.0$
 4. UTIL    Ryan Tannehill                QB    TEN            BUF@TEN  16.9           14000.0$
 5. UTIL    Zack Moss                     RB    BUF            BUF@TEN  10.0           9500.0$

Fantasy Points 83.45
Salary 59500.00

 1. MVP     Ryan Tannehill                QB    TEN            BUF@TEN  25.35          14000.0$
 2. UTIL    Anthony Firkser               TE    TEN            BUF@TEN  3.6            6000.0$
 3. UTIL    Cole Beasley                  WR    BUF            BUF@TEN  7.3            7500.0$
 4. UTIL    Derrick Henry                 RB    TEN            BUF@TEN  16.9           15500.0$
 5. UTIL    Josh Allen                    QB    BUF            BUF@TEN  26.3           17000.0$

Fantasy Points 79.45
Salary 60000.00

 1. MVP     Josh Allen                    QB    BUF            BUF@TEN  39.45          17000.0$
 2. UTIL    Derrick Henry                 RB    TEN            BUF@TEN  16.9           15500.0$
 3. UTIL    Emmanuel Sanders              WR    BUF            BUF@TEN  9.6            10000.0$
 4. UTIL    Randy Bullock                 K     TEN            BUF@TEN  7.4            8000.0$
 5. UTIL    Zack Moss                     RB    BUF            BUF@TEN  10.0           9500.0$

Fantasy Points 83.35
Salary 60000.00

 1. MVP     Derrick Henry                 RB    TEN            BUF@TEN  25.35          15500.0$
 2. UTIL    Anthony Firkser               TE    TEN            BUF@TEN  3.6            6000.0$
 3. UTIL    Cole Beasley                  WR    BUF            BUF@TEN  7.3            7500.0$
 4. UTIL    Josh Allen                    QB    BUF            BUF@TEN  26.3           17000.0$
 5. UTIL    Ryan Tannehill                QB    TEN            BUF@TEN  16.9           14000.0$

Fantasy Points 79.45
Salary 60000.00

 1. MVP     Josh Allen                    QB    BUF            BUF@TEN  39.45          17000.0$
 2. UTIL    Emmanuel Sanders              WR    BUF            BUF@TEN  9.6            10000.0$
 3. UTIL    Randy Bullock                 K     TEN            BUF@TEN  7.4            8000.0$
 4. UTIL    Ryan Tannehill                QB    TEN            BUF@TEN  16.9           14000.0$
 5. UTIL    Zack Moss                     RB    BUF            BUF@TEN  10.0           9500.0$

Fantasy Points 83.35
Salary 58500.00

 1. MVP     Ryan Tannehill                QB    TEN            BUF@TEN  25.35          14000.0$
 2. UTIL    Cole Beasley                  WR    BUF            BUF@TEN  7.3            7500.0$
 3. UTIL    Dawson Knox                   TE    BUF            BUF@TEN  7.5            9000.0$
 4. UTIL    Josh Allen                    QB    BUF            BUF@TEN  26.3           17000.0$
 5. UTIL    Stefon Diggs                  WR    BUF            BUF@TEN  12.9           12500.0$

Fantasy Points 79.35
Salary 60000.00

 1. MVP     Josh Allen                    QB    BUF            BUF@TEN  39.45          17000.0$
 2. UTIL    Cole Beasley                  WR    BUF            BUF@TEN  7.3            7500.0$
 3. UTIL    Derrick Henry                 RB    TEN            BUF@TEN  16.9           15500.0$
 4. UTIL    Emmanuel Sanders              WR    BUF            BUF@TEN  9.6            10000.0$
 5. UTIL    Zack Moss                     RB    BUF            BUF@TEN  10.0           9500.0$

Fantasy Points 83.25
Salary 59500.00