In [1]:
import requests
from bs4 import BeautifulSoup as soup
import pandas as pd

In [3]:
def get_spread_page():
    url = "https://rotogrinders.com/lineups/nfl"
    html = requests.get(url).text
    page = soup(html)
    return page
page = get_spread_page()

team_list = page.find_all("span", {"class": "shrt"})
teams = [i.text for i in team_list]
odds_list = page.find_all("a", {"href": "/nfl/odds"})
odds = [i.text for i in odds_list]
teams.sort()
print(teams)

['ARI', 'ATL', 'BAL', 'BUF', 'CAR', 'CHI', 'CIN', 'CLE', 'DAL', 'DEN', 'DET', 'GBP', 'HOU', 'IND', 'JAC', 'KCC', 'LAC', 'LAR', 'LVR', 'MIA', 'MIN', 'NEP', 'NOS', 'NYG', 'NYJ', 'PHI', 'PIT', 'SEA', 'SFO', 'TBB', 'TEN', 'WAS']

In [52]:
df_fd_temp = pd.read_csv("data/nfl/FanDuel-NFL-2021 ET-10 ET-10 ET-64897-players-list.csv")
df_fd = df_fd_temp.convert_dtypes()
df_fd.head()

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
0,64897-39280,RB,Derrick,Derrick Henry,Henry,24.125,4,10400,TEN@JAC,TEN,JAC,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
1,64897-55050,RB,Christian,Christian McCaffrey,McCaffrey,16.800001,3,10000,PHI@CAR,CAR,PHI,D,Hamstring,<NA>,<NA>,<NA>,RB/FLEX
2,64897-54140,RB,Dalvin,Dalvin Cook,Cook,12.866666,3,9000,DET@MIN,MIN,DET,Q,Ankle,<NA>,<NA>,<NA>,RB/FLEX
3,64897-42104,RB,Alvin,Alvin Kamara,Kamara,13.225,4,8600,NO@WAS,NO,WAS,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
4,64897-63484,QB,Kyler,Kyler Murray,Murray,27.955,4,8500,SF@ARI,ARI,SF,<NA>,<NA>,<NA>,<NA>,<NA>,QB

df_teams = list(df_fd.Team.unique())
df_teams.sort()
print(df_teams)

df_fd.head()

In [53]:
replace_dict = {"GBP":"GB", "KCC":"KC", "LVR":"LV", "NEP":"NE", "NOS":"NO", "SFO":"SF", "TBB":"TB"}
clean_teams = [replace_dict.get(item,item) for item in teams]
print(clean_teams)

['ARI', 'ATL', 'BAL', 'BUF', 'CAR', 'CHI', 'CIN', 'CLE', 'DAL', 'DEN', 'DET', 'GB', 'HOU', 'IND', 'JAC', 'KC', 'LAC', 'LAR', 'LV', 'MIA', 'MIN', 'NE', 'NO', 'NYG', 'NYJ', 'PHI', 'PIT', 'SEA', 'SF', 'TB', 'TEN', 'WAS']

In [54]:
df_odds = dict(zip(clean_teams, odds))
#print(df_odds)
print(dict(sorted(df_odds.items(), key=lambda item: item[1])))

{'CHI': '15.50', 'IND': '18.50', 'CIN': '18.75', 'TEN': '19.50', 'JAC': '19.75', 'MIN': '20.25', 'HOU': '20.50', 'MIA': '20.50', 'BAL': '21.25', 'DAL': '21.25', 'PIT': '21.50', 'GB': '22.25', 'NO': '22.50', 'NYJ': '22.75', 'LV': '23.00', 'CAR': '23.50', 'BUF': '23.75', 'LAR': '24.00', 'DEN': '24.25', 'NYG': '24.50', 'ATL': '25.25', 'NE': '25.75', 'WAS': '26.50', 'DET': '26.75', 'LAC': '27.00', 'SEA': '27.00', 'SF': '27.00', 'ARI': '27.75', 'CLE': '28.75', 'TB': '29.50', 'KC': '29.75', 'PHI': '29.75'}

In [55]:
df_fd_def = df_fd.query("Position == 'D'")
df_fd = df_fd.query("Position != 'D'")
df_fd_def.head(3)

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
223,64897-12541,D,New England,New England Patriots,Patriots,7.25,4,5000,NE@HOU,NE,HOU,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
255,64897-12551,D,Tampa Bay,Tampa Bay Buccaneers,Buccaneers,7.5,4,4800,MIA@TB,TB,MIA,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
273,64897-12546,D,Arizona,Arizona Cardinals,Cardinals,10.75,4,4700,SF@ARI,ARI,SF,<NA>,<NA>,<NA>,<NA>,<NA>,DEF

In [56]:
df_fd["expts"] = df_fd["Team"].map(df_odds)
df_fd.expts = df_fd.expts.astype('float')
pts_bins = [1.2, 1.1, 1.0, .9,.8]
df_fd["rkpts"] = pd.cut(df_fd.expts, 5, labels=pts_bins)
df_fd.rkpts = df_fd.rkpts.astype('float')
df_fd["new_expts"] = df_fd.FPPG * df_fd.rkpts
df_fd.head()

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position,expts,rkpts,new_expts
0,64897-39280,RB,Derrick,Derrick Henry,Henry,24.125,4,10400,TEN@JAC,TEN,JAC,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX,19.50,1.1,26.5375
1,64897-55050,RB,Christian,Christian McCaffrey,McCaffrey,16.800001,3,10000,PHI@CAR,CAR,PHI,D,Hamstring,<NA>,<NA>,<NA>,RB/FLEX,23.50,1.0,16.800001
2,64897-54140,RB,Dalvin,Dalvin Cook,Cook,12.866666,3,9000,DET@MIN,MIN,DET,Q,Ankle,<NA>,<NA>,<NA>,RB/FLEX,20.25,1.1,14.153333
3,64897-42104,RB,Alvin,Alvin Kamara,Kamara,13.225,4,8600,NO@WAS,NO,WAS,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX,22.50,1.0,13.225
4,64897-63484,QB,Kyler,Kyler Murray,Murray,27.955,4,8500,SF@ARI,ARI,SF,<NA>,<NA>,<NA>,<NA>,<NA>,QB,27.75,0.8,22.364

In [57]:
df_fd.FPPG = df_fd.new_expts
df_fd = df_fd.drop(['expts', 'rkpts', 'new_expts'], axis=1)
df_fd = pd.concat([df_fd, df_fd_def])
#df_fd.query("Position == 'D'")
df_fd.head()

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
223,64897-12541,D,New England,New England Patriots,Patriots,7.25,4,5000,NE@HOU,NE,HOU,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
255,64897-12551,D,Tampa Bay,Tampa Bay Buccaneers,Buccaneers,7.5,4,4800,MIA@TB,TB,MIA,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
273,64897-12546,D,Arizona,Arizona Cardinals,Cardinals,10.75,4,4700,SF@ARI,ARI,SF,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
295,64897-12542,D,New Orleans,New Orleans Saints,Saints,10.75,4,4600,NO@WAS,NO,WAS,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
357,64897-12537,D,Las Vegas,Las Vegas Raiders,Raiders,4.25,4,4500,CHI@LV,LV,CHI,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
626,64897-12531,D,Denver,Denver Broncos,Broncos,9.75,4,4400,DEN@PIT,DEN,PIT,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
632,64897-12527,D,Chicago,Chicago Bears,Bears,8.5,4,4300,CHI@LV,CHI,LV,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
636,64897-12534,D,Tennessee,Tennessee Titans,Titans,2.0,4,4200,TEN@JAC,TEN,JAC,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
646,64897-12529,D,Cleveland,Cleveland Browns,Browns,8.0,4,4100,CLE@LAC,CLE,LAC,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
647,64897-12533,D,Green Bay,Green Bay Packers,Packers,4.0,4,4100,GB@CIN,GB,CIN,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
671,64897-12530,D,Dallas,Dallas Cowboys,Cowboys,8.75,4,4000,NYG@DAL,DAL,NYG,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
672,64897-12547,D,Pittsburgh,Pittsburgh Steelers,Steelers,5.75,4,4000,DEN@PIT,PIT,DEN,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
767,64897-12540,D,Minnesota,Minnesota Vikings,Vikings,6.0,4,3900,DET@MIN,MIN,DET,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
768,64897-12552,D,Washington,Washington Football Team,Football Team,3.0,4,3800,NO@WAS,WAS,NO,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
769,64897-12553,D,Carolina,Carolina Panthers,Panthers,6.25,4,3800,PHI@CAR,CAR,PHI,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
770,64897-12548,D,Los Angeles,Los Angeles Chargers,Chargers,6.5,4,3700,CLE@LAC,LAC,CLE,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
771,64897-12549,D,San Francisco,San Francisco 49ers,49ers,5.0,4,3700,SF@ARI,SF,ARI,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
772,64897-12539,D,Miami,Miami Dolphins,Dolphins,5.25,4,3600,MIA@TB,MIA,TB,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
773,64897-12545,D,Philadelphia,Philadelphia Eagles,Eagles,4.5,4,3500,PHI@CAR,PHI,CAR,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
774,64897-12528,D,Cincinnati,Cincinnati Bengals,Bengals,6.0,4,3400,GB@CIN,CIN,GB,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
775,64897-12554,D,Jacksonville,Jacksonville Jaguars,Jaguars,2.25,4,3300,TEN@JAC,JAC,TEN,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
776,64897-12556,D,Houston,Houston Texans,Texans,3.5,4,3200,NE@HOU,HOU,NE,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
777,64897-12532,D,Detroit,Detroit Lions,Lions,2.5,4,3100,DET@MIN,DET,MIN,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
778,64897-12543,D,New York,New York Giants,Giants,3.5,4,3000,NYG@DAL,NYG,DAL,<NA>,<NA>,<NA>,<NA>,<NA>,DEF

In [58]:
df_fd.to_csv('data/nfl/FDprojections.csv')

In [1]:
from pydfs_lineup_optimizer import Site, Sport, get_optimizer, PlayerFilter, AfterEachExposureStrategy, TeamStack

optimizer = get_optimizer(Site.FANDUEL, Sport.FOOTBALL)
optimizer.load_players_from_csv("data/nfl/FDprojections.csv")
optimizer.add_stack(TeamStack(3, for_positions=['QB', 'WR', 'TE']))
#optimizer.add_stack(TeamStack(2, for_positions=['RB', 'D']))
for lineup in optimizer.optimize(40, max_exposure=0.3, exposure_strategy = AfterEachExposureStrategy):
    print(lineup)
optimizer.export('data/nfl/fd_result.csv')

 1. QB      Sam Darnold                   QB    CAR            PHI@CAR  24.44          7600.0$
 2. RB      Derrick Henry                 RB    TEN            TEN@JAC  26.538         10400.0$
 3. RB      James Robinson                RB    JAC            TEN@JAC  15.757         7400.0$
 4. WR      Brandin Cooks                 WR    HOU            NE@HOU   15.785         6300.0$
 5. WR      Brandon Zylstra               WR    CAR            PHI@CAR  9.6            4900.0$
 6. WR      DJ Moore                      WR    CAR            PHI@CAR  18.675         7900.0$
 7. TE      Dalton Schultz                TE    DAL            NYG@DAL  12.025         6200.0$
 8. FLEX    John Ross III                 WR    NYG            NYG@DAL  13.68          5200.0$
 9. DEF     Dallas Cowboys                D     DAL            NYG@DAL  8.75           4000.0$

Fantasy Points 145.25
Salary 59900.00

 1. QB      Kirk Cousins                  QB    MIN            DET@MIN  22.974         7500.0$
 2. RB      Najee Harris                  RB    PIT            DEN@PIT  15.325         7300.0$
 3. RB      Tony Pollard                  RB    DAL            NYG@DAL  10.375         5600.0$
 4. WR      Adam Thielen                  WR    MIN            DET@MIN  16.143         7500.0$
 5. WR      Diontae Johnson               WR    PIT            DEN@PIT  15.6           7000.0$
 6. WR      Ja'Marr Chase                 WR    CIN            GB@CIN   17.05          7300.0$
 7. TE      Juwan Johnson                 TE    NO             NO@WAS   9.133          5000.0$
 8. FLEX    Justin Jefferson              WR    MIN            DET@MIN  17.941         8000.0$
 9. DEF     New Orleans Saints            D     NO             NO@WAS   10.75          4600.0$

Fantasy Points 135.29
Salary 59800.00

 1. QB      Derek Carr                    QB    LV             CHI@LV   21.715         7100.0$
 2. RB      Aaron Jones                   RB    GB             GB@CIN   16.925         8400.0$
 3. RB      Austin Ekeler                 RB    LAC            CLE@LAC  15.48          7700.0$
 4. WR      Breshad Perriman              WR    CHI            CHI@LV   8.41           4500.0$
 5. WR      Deebo Samuel                  WR    SF             SF@ARI   15.98          7700.0$
 6. WR      Hunter Renfrow                WR    LV             CHI@LV   11.975         5800.0$
 7. TE      Darren Waller                 TE    LV             CHI@LV   12.85          7400.0$
 8. FLEX    Tee Higgins                   WR    CIN            GB@CIN   14.74          6700.0$
 9. DEF     Arizona Cardinals             D     ARI            SF@ARI   10.75          4700.0$

Fantasy Points 128.82
Salary 60000.00

 1. QB      Joe Burrow                    QB    CIN            GB@CIN   20.025         7000.0$
 2. RB      Josh Jacobs                   RB    LV             CHI@LV   12.35          7200.0$
 3. RB      Kareem Hunt                   RB    CLE            CLE@LAC  12.3           7000.0$
 4. WR      Davante Adams                 WR    GB             GB@CIN   14.7           8200.0$
 5. WR      Marvin Jones Jr.              WR    JAC            TEN@JAC  12.045         6600.0$
 6. WR      Terry McLaurin                WR    WAS            NO@WAS   14.828         7400.0$
 7. TE      C.J. Uzomah                   TE    CIN            GB@CIN   8.222          5500.0$
 8. FLEX    Tyler Boyd                    WR    CIN            GB@CIN   11.935         6300.0$
 9. DEF     Denver Broncos                D     DEN            DEN@PIT  9.75           4400.0$

Fantasy Points 116.16
Salary 59600.00

 1. QB      Sam Darnold                   QB    CAR            PHI@CAR  24.44          7600.0$
 2. RB      Derrick Henry                 RB    TEN            TEN@JAC  26.538         10400.0$
 3. RB      Najee Harris                  RB    PIT            DEN@PIT  15.325         7300.0$
 4. WR      Brandin Cooks                 WR    HOU            NE@HOU   15.785         6300.0$
 5. WR      Brandon Zylstra               WR    CAR            PHI@CAR  9.6            4900.0$
 6. WR      DJ Moore                      WR    CAR            PHI@CAR  18.675         7900.0$
 7. TE      Dalton Schultz                TE    DAL            NYG@DAL  12.025         6200.0$
 8. FLEX    John Ross III                 WR    NYG            NYG@DAL  13.68          5200.0$
 9. DEF     Dallas Cowboys                D     DAL            NYG@DAL  8.75           4000.0$

Fantasy Points 144.82
Salary 59800.00

 1. QB      Kirk Cousins                  QB    MIN            DET@MIN  22.974         7500.0$
 2. RB      James Robinson                RB    JAC            TEN@JAC  15.757         7400.0$
 3. RB      Tony Pollard                  RB    DAL            NYG@DAL  10.375         5600.0$
 4. WR      Adam Thielen                  WR    MIN            DET@MIN  16.143         7500.0$
 5. WR      Diontae Johnson               WR    PIT            DEN@PIT  15.6           7000.0$
 6. WR      Ja'Marr Chase                 WR    CIN            GB@CIN   17.05          7300.0$
 7. TE      Juwan Johnson                 TE    NO             NO@WAS   9.133          5000.0$
 8. FLEX    Justin Jefferson              WR    MIN            DET@MIN  17.941         8000.0$
 9. DEF     New Orleans Saints            D     NO             NO@WAS   10.75          4600.0$

Fantasy Points 135.72
Salary 59900.00

 1. QB      Derek Carr                    QB    LV             CHI@LV   21.715         7100.0$
 2. RB      Aaron Jones                   RB    GB             GB@CIN   16.925         8400.0$
 3. RB      Austin Ekeler                 RB    LAC            CLE@LAC  15.48          7700.0$
 4. WR      Deebo Samuel                  WR    SF             SF@ARI   15.98          7700.0$
 5. WR      Hunter Renfrow                WR    LV             CHI@LV   11.975         5800.0$
 6. WR      Tee Higgins                   WR    CIN            GB@CIN   14.74          6700.0$
 7. TE      Foster Moreau                 TE    LV             CHI@LV   5.85           4400.0$
 8. FLEX    Terry McLaurin                WR    WAS            NO@WAS   14.828         7400.0$
 9. DEF     Arizona Cardinals             D     ARI            SF@ARI   10.75          4700.0$

Fantasy Points 128.24
Salary 59900.00

 1. QB      Sam Darnold                   QB    CAR            PHI@CAR  24.44          7600.0$
 2. RB      Derrick Henry                 RB    TEN            TEN@JAC  26.538         10400.0$
 3. RB      James Robinson                RB    JAC            TEN@JAC  15.757         7400.0$
 4. WR      Brandin Cooks                 WR    HOU            NE@HOU   15.785         6300.0$
 5. WR      Brandon Zylstra               WR    CAR            PHI@CAR  9.6            4900.0$
 6. WR      DJ Moore                      WR    CAR            PHI@CAR  18.675         7900.0$
 7. TE      Dalton Schultz                TE    DAL            NYG@DAL  12.025         6200.0$
 8. FLEX    John Ross III                 WR    NYG            NYG@DAL  13.68          5200.0$
 9. DEF     Cleveland Browns              D     CLE            CLE@LAC  8.0            4100.0$

Fantasy Points 144.50
Salary 60000.00

 1. QB      Kirk Cousins                  QB    MIN            DET@MIN  22.974         7500.0$
 2. RB      Najee Harris                  RB    PIT            DEN@PIT  15.325         7300.0$
 3. RB      Tony Pollard                  RB    DAL            NYG@DAL  10.375         5600.0$
 4. WR      Adam Thielen                  WR    MIN            DET@MIN  16.143         7500.0$
 5. WR      Diontae Johnson               WR    PIT            DEN@PIT  15.6           7000.0$
 6. WR      Ja'Marr Chase                 WR    CIN            GB@CIN   17.05          7300.0$
 7. TE      Juwan Johnson                 TE    NO             NO@WAS   9.133          5000.0$
 8. FLEX    Justin Jefferson              WR    MIN            DET@MIN  17.941         8000.0$
 9. DEF     Arizona Cardinals             D     ARI            SF@ARI   10.75          4700.0$

Fantasy Points 135.29
Salary 59900.00

 1. QB      Derek Carr                    QB    LV             CHI@LV   21.715         7100.0$
 2. RB      Aaron Jones                   RB    GB             GB@CIN   16.925         8400.0$
 3. RB      Austin Ekeler                 RB    LAC            CLE@LAC  15.48          7700.0$
 4. WR      Breshad Perriman              WR    CHI            CHI@LV   8.41           4500.0$
 5. WR      Deebo Samuel                  WR    SF             SF@ARI   15.98          7700.0$
 6. WR      Hunter Renfrow                WR    LV             CHI@LV   11.975         5800.0$
 7. TE      Darren Waller                 TE    LV             CHI@LV   12.85          7400.0$
 8. FLEX    Tee Higgins                   WR    CIN            GB@CIN   14.74          6700.0$
 9. DEF     New Orleans Saints            D     NO             NO@WAS   10.75          4600.0$

Fantasy Points 128.82
Salary 59900.00

 1. QB      Daniel Jones                  QB    NYG            NYG@DAL  21.411         7400.0$
 2. RB      Kareem Hunt                   RB    CLE            CLE@LAC  12.3           7000.0$
 3. RB      Saquon Barkley                RB    NYG            NYG@DAL  12.735         7800.0$
 4. WR      Davante Adams                 WR    GB             GB@CIN   14.7           8200.0$
 5. WR      Henry Ruggs III               WR    LV             CHI@LV   10.9           5900.0$
 6. WR      John Brown                    WR    LV             CHI@LV   7.825          4500.0$
 7. TE      Darren Waller                 TE    LV             CHI@LV   12.85          7400.0$
 8. FLEX    Terry McLaurin                WR    WAS            NO@WAS   14.828         7400.0$
 9. DEF     Denver Broncos                D     DEN            DEN@PIT  9.75           4400.0$

Fantasy Points 117.30
Salary 60000.00

 1. QB      Sam Darnold                   QB    CAR            PHI@CAR  24.44          7600.0$
 2. RB      Derrick Henry                 RB    TEN            TEN@JAC  26.538         10400.0$
 3. RB      James Robinson                RB    JAC            TEN@JAC  15.757         7400.0$
 4. WR      Brandin Cooks                 WR    HOU            NE@HOU   15.785         6300.0$
 5. WR      Brandon Zylstra               WR    CAR            PHI@CAR  9.6            4900.0$
 6. WR      DJ Moore                      WR    CAR            PHI@CAR  18.675         7900.0$
 7. TE      Mike Gesicki                  TE    MIA            MIA@TB   9.185          5600.0$
 8. FLEX    John Ross III                 WR    NYG            NYG@DAL  13.68          5200.0$
 9. DEF     New Orleans Saints            D     NO             NO@WAS   10.75          4600.0$

Fantasy Points 144.41
Salary 59900.00

 1. QB      Kirk Cousins                  QB    MIN            DET@MIN  22.974         7500.0$
 2. RB      Jeff Wilson Jr.               RB    SF             SF@ARI   9.053          5000.0$
 3. RB      Najee Harris                  RB    PIT            DEN@PIT  15.325         7300.0$
 4. WR      Adam Thielen                  WR    MIN            DET@MIN  16.143         7500.0$
 5. WR      Ja'Marr Chase                 WR    CIN            GB@CIN   17.05          7300.0$
 6. WR      Justin Jefferson              WR    MIN            DET@MIN  17.941         8000.0$
 7. TE      Dalton Schultz                TE    DAL            NYG@DAL  12.025         6200.0$
 8. FLEX    Tee Higgins                   WR    CIN            GB@CIN   14.74          6700.0$
 9. DEF     Denver Broncos                D     DEN            DEN@PIT  9.75           4400.0$

Fantasy Points 135.00
Salary 59900.00

 1. QB      Derek Carr                    QB    LV             CHI@LV   21.715         7100.0$
 2. RB      Aaron Jones                   RB    GB             GB@CIN   16.925         8400.0$
 3. RB      Austin Ekeler                 RB    LAC            CLE@LAC  15.48          7700.0$
 4. WR      Breshad Perriman              WR    CHI            CHI@LV   8.41           4500.0$
 5. WR      Deebo Samuel                  WR    SF             SF@ARI   15.98          7700.0$
 6. WR      Diontae Johnson               WR    PIT            DEN@PIT  15.6           7000.0$
 7. TE      Darren Waller                 TE    LV             CHI@LV   12.85          7400.0$
 8. FLEX    Hunter Renfrow                WR    LV             CHI@LV   11.975         5800.0$
 9. DEF     Denver Broncos                D     DEN            DEN@PIT  9.75           4400.0$

Fantasy Points 128.69
Salary 60000.00

 1. QB      Sam Darnold                   QB    CAR            PHI@CAR  24.44          7600.0$
 2. RB      Derrick Henry                 RB    TEN            TEN@JAC  26.538         10400.0$
 3. RB      James Robinson                RB    JAC            TEN@JAC  15.757         7400.0$
 4. WR      Brandin Cooks                 WR    HOU            NE@HOU   15.785         6300.0$
 5. WR      Brandon Zylstra               WR    CAR            PHI@CAR  9.6            4900.0$
 6. WR      DJ Moore                      WR    CAR            PHI@CAR  18.675         7900.0$
 7. TE      Mike Gesicki                  TE    MIA            MIA@TB   9.185          5600.0$
 8. FLEX    John Ross III                 WR    NYG            NYG@DAL  13.68          5200.0$
 9. DEF     Arizona Cardinals             D     ARI            SF@ARI   10.75          4700.0$

Fantasy Points 144.41
Salary 60000.00

 1. QB      Kirk Cousins                  QB    MIN            DET@MIN  22.974         7500.0$
 2. RB      Aaron Jones                   RB    GB             GB@CIN   16.925         8400.0$
 3. RB      Najee Harris                  RB    PIT            DEN@PIT  15.325         7300.0$
 4. WR      Ja'Marr Chase                 WR    CIN            GB@CIN   17.05          7300.0$
 5. WR      Justin Jefferson              WR    MIN            DET@MIN  17.941         8000.0$
 6. WR      K.J. Osborn                   WR    MIN            DET@MIN  10.285         5200.0$
 7. TE      Juwan Johnson                 TE    NO             NO@WAS   9.133          5000.0$
 8. FLEX    Tee Higgins                   WR    CIN            GB@CIN   14.74          6700.0$
 9. DEF     New Orleans Saints            D     NO             NO@WAS   10.75          4600.0$

Fantasy Points 135.12
Salary 60000.00

 1. QB      Derek Carr                    QB    LV             CHI@LV   21.715         7100.0$
 2. RB      Austin Ekeler                 RB    LAC            CLE@LAC  15.48          7700.0$
 3. RB      Jeff Wilson Jr.               RB    SF             SF@ARI   9.053          5000.0$
 4. WR      Adam Thielen                  WR    MIN            DET@MIN  16.143         7500.0$
 5. WR      Deebo Samuel                  WR    SF             SF@ARI   15.98          7700.0$
 6. WR      Diontae Johnson               WR    PIT            DEN@PIT  15.6           7000.0$
 7. TE      Darren Waller                 TE    LV             CHI@LV   12.85          7400.0$
 8. FLEX    Hunter Renfrow                WR    LV             CHI@LV   11.975         5800.0$
 9. DEF     Arizona Cardinals             D     ARI            SF@ARI   10.75          4700.0$

Fantasy Points 129.55
Salary 59900.00

 1. QB      Sam Darnold                   QB    CAR            PHI@CAR  24.44          7600.0$
 2. RB      Derrick Henry                 RB    TEN            TEN@JAC  26.538         10400.0$
 3. RB      James Robinson                RB    JAC            TEN@JAC  15.757         7400.0$
 4. WR      Brandin Cooks                 WR    HOU            NE@HOU   15.785         6300.0$
 5. WR      Brandon Zylstra               WR    CAR            PHI@CAR  9.6            4900.0$
 6. WR      DJ Moore                      WR    CAR            PHI@CAR  18.675         7900.0$
 7. TE      Juwan Johnson                 TE    NO             NO@WAS   9.133          5000.0$
 8. FLEX    John Ross III                 WR    NYG            NYG@DAL  13.68          5200.0$
 9. DEF     New Orleans Saints            D     NO             NO@WAS   10.75          4600.0$

Fantasy Points 144.36
Salary 59300.00

 1. QB      Kirk Cousins                  QB    MIN            DET@MIN  22.974         7500.0$
 2. RB      Jeff Wilson Jr.               RB    SF             SF@ARI   9.053          5000.0$
 3. RB      Najee Harris                  RB    PIT            DEN@PIT  15.325         7300.0$
 4. WR      Adam Thielen                  WR    MIN            DET@MIN  16.143         7500.0$
 5. WR      Diontae Johnson               WR    PIT            DEN@PIT  15.6           7000.0$
 6. WR      Ja'Marr Chase                 WR    CIN            GB@CIN   17.05          7300.0$
 7. TE      Dalton Schultz                TE    DAL            NYG@DAL  12.025         6200.0$
 8. FLEX    Justin Jefferson              WR    MIN            DET@MIN  17.941         8000.0$
 9. DEF     Dallas Cowboys                D     DAL            NYG@DAL  8.75           4000.0$

Fantasy Points 134.86
Salary 59800.00

 1. QB      Derek Carr                    QB    LV             CHI@LV   21.715         7100.0$
 2. RB      Aaron Jones                   RB    GB             GB@CIN   16.925         8400.0$
 3. RB      Austin Ekeler                 RB    LAC            CLE@LAC  15.48          7700.0$
 4. WR      Deebo Samuel                  WR    SF             SF@ARI   15.98          7700.0$
 5. WR      Henry Ruggs III               WR    LV             CHI@LV   10.9           5900.0$
 6. WR      Hunter Renfrow                WR    LV             CHI@LV   11.975         5800.0$
 7. TE      Dalton Schultz                TE    DAL            NYG@DAL  12.025         6200.0$
 8. FLEX    Tee Higgins                   WR    CIN            GB@CIN   14.74          6700.0$
 9. DEF     Denver Broncos                D     DEN            DEN@PIT  9.75           4400.0$

Fantasy Points 129.49
Salary 59900.00

 1. QB      Daniel Jones                  QB    NYG            NYG@DAL  21.411         7400.0$
 2. RB      Josh Jacobs                   RB    LV             CHI@LV   12.35          7200.0$
 3. RB      Kareem Hunt                   RB    CLE            CLE@LAC  12.3           7000.0$
 4. WR      Davante Adams                 WR    GB             GB@CIN   14.7           8200.0$
 5. WR      Henry Ruggs III               WR    LV             CHI@LV   10.9           5900.0$
 6. WR      John Brown                    WR    LV             CHI@LV   7.825          4500.0$
 7. TE      Darren Waller                 TE    LV             CHI@LV   12.85          7400.0$
 8. FLEX    Terry McLaurin                WR    WAS            NO@WAS   14.828         7400.0$
 9. DEF     Arizona Cardinals             D     ARI            SF@ARI   10.75          4700.0$

Fantasy Points 117.91
Salary 59700.00

 1. QB      Sam Darnold                   QB    CAR            PHI@CAR  24.44          7600.0$
 2. RB      Derrick Henry                 RB    TEN            TEN@JAC  26.538         10400.0$
 3. RB      James Robinson                RB    JAC            TEN@JAC  15.757         7400.0$
 4. WR      Brandin Cooks                 WR    HOU            NE@HOU   15.785         6300.0$
 5. WR      Brandon Zylstra               WR    CAR            PHI@CAR  9.6            4900.0$
 6. WR      DJ Moore                      WR    CAR            PHI@CAR  18.675         7900.0$
 7. TE      Juwan Johnson                 TE    NO             NO@WAS   9.133          5000.0$
 8. FLEX    John Ross III                 WR    NYG            NYG@DAL  13.68          5200.0$
 9. DEF     Arizona Cardinals             D     ARI            SF@ARI   10.75          4700.0$

Fantasy Points 144.36
Salary 59400.00

 1. QB      Kirk Cousins                  QB    MIN            DET@MIN  22.974         7500.0$
 2. RB      Duke Johnson                  RB    JAC            TEN@JAC  7.04           4500.0$
 3. RB      Najee Harris                  RB    PIT            DEN@PIT  15.325         7300.0$