In [1]:
from functions.clean_data import archive_files

In [2]:
archive_files()

In [4]:
import pandas as pd
import numpy as np

In [22]:
df_fd = pd.read_csv("data/nfl/FanDuel-NFL-2021 ET-10 ET-14 ET-65214-players-list.csv")

In [23]:
df_fd.head()

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
0,65214-6498,QB,Tom,Tom Brady,Brady,27.256000,5.0,16500,TB@PHI,TB,PHI,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
1,65214-69531,QB,Jalen,Jalen Hurts,Hurts,25.039999,5.0,15500,TB@PHI,PHI,TB,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
2,65214-32384,WR,Mike,Mike Evans,Evans,15.560001,5.0,13500,TB@PHI,TB,PHI,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
3,65214-55635,WR,Chris,Chris Godwin,Godwin,13.460001,5.0,13000,TB@PHI,TB,PHI,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
4,65214-90576,WR,DeVonta,DeVonta Smith,Smith,9.980000,5.0,12000,TB@PHI,PHI,TB,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX

In [24]:
df_fd.columns

Index(['Id', 'Position', 'First Name', 'Nickname', 'Last Name', 'FPPG',
       'Played', 'Salary', 'Game', 'Team', 'Opponent', 'Injury Indicator',
       'Injury Details', 'Tier', 'Unnamed: 14', 'Unnamed: 15',
       'Roster Position'],
      dtype='object')

In [25]:
df_fd.set_index('Id',inplace=True)

In [27]:
#df.drop(df.dropna(subset=['columnA']).index)
df_fd = df_fd.drop(df_fd.dropna(subset=['Injury Indicator']).index)
df_fd = df_fd.query("Position != 'QB' or Nickname == 'Tom Brady' or Nickname == 'Jalen Hurts'")
df_fd.head()

,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
Id,,,,,,,,,,,,,,,,
65214-6498,QB,Tom,Tom Brady,Brady,27.256000,5.0,16500,TB@PHI,TB,PHI,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
65214-69531,QB,Jalen,Jalen Hurts,Hurts,25.039999,5.0,15500,TB@PHI,PHI,TB,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
65214-32384,WR,Mike,Mike Evans,Evans,15.560001,5.0,13500,TB@PHI,TB,PHI,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
65214-55635,WR,Chris,Chris Godwin,Godwin,13.460001,5.0,13000,TB@PHI,TB,PHI,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
65214-90576,WR,DeVonta,DeVonta Smith,Smith,9.980000,5.0,12000,TB@PHI,PHI,TB,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX

In [28]:
df_fd.to_csv('data/nfl/FDprojectionsSD.csv')

In [31]:
from pydfs_lineup_optimizer import Site, Sport, get_optimizer, PlayerFilter, AfterEachExposureStrategy

optimizer = get_optimizer(Site.FANDUEL_SINGLE_GAME, Sport.FOOTBALL)
optimizer.load_players_from_csv("data/nfl/FDprojectionsSD.csv")
for lineup in optimizer.optimize(20):
    print(lineup)
optimizer.export('data/nfl/fd_resultSD.csv')

 1. MVP     Tom Brady                     QB    TB             TB@PHI   40.884         16500.0$
 2. UTIL    Antonio Brown                 WR    TB             TB@PHI   15.275         11500.0$
 3. UTIL    Darwin Thompson               RB    TB             TB@PHI   5.94           5000.0$
 4. UTIL    Jalen Hurts                   QB    PHI            TB@PHI   25.04          15500.0$
 5. UTIL    Leonard Fournette             RB    TB             TB@PHI   11.46          11000.0$

Fantasy Points 98.60
Salary 59500.00

 1. MVP     Tom Brady                     QB    TB             TB@PHI   40.884         16500.0$
 2. UTIL    Antonio Brown                 WR    TB             TB@PHI   15.275         11500.0$
 3. UTIL    Giovani Bernard               RB    TB             TB@PHI   7.725          7000.0$
 4. UTIL    Jalen Hurts                   QB    PHI            TB@PHI   25.04          15500.0$
 5. UTIL    Ryan Succop                   K     TB             TB@PHI   8.8            9000.0$

Fantasy Points 97.72
Salary 59500.00

 1. MVP     Tom Brady                     QB    TB             TB@PHI   40.884         16500.0$
 2. UTIL    Antonio Brown                 WR    TB             TB@PHI   15.275         11500.0$
 3. UTIL    Giovani Bernard               RB    TB             TB@PHI   7.725          7000.0$
 4. UTIL    Jalen Hurts                   QB    PHI            TB@PHI   25.04          15500.0$
 5. UTIL    Kenneth Gainwell              RB    PHI            TB@PHI   8.64           8500.0$

Fantasy Points 97.56
Salary 59000.00

 1. MVP     Jalen Hurts                   QB    PHI            TB@PHI   37.56          15500.0$
 2. UTIL    Antonio Brown                 WR    TB             TB@PHI   15.275         11500.0$
 3. UTIL    Darwin Thompson               RB    TB             TB@PHI   5.94           5000.0$
 4. UTIL    Leonard Fournette             RB    TB             TB@PHI   11.46          11000.0$
 5. UTIL    Tom Brady                     QB    TB             TB@PHI   27.256         16500.0$

Fantasy Points 97.49
Salary 59500.00

 1. MVP     Tom Brady                     QB    TB             TB@PHI   40.884         16500.0$
 2. UTIL    Antonio Brown                 WR    TB             TB@PHI   15.275         11500.0$
 3. UTIL    Jake Elliott                  K     PHI            TB@PHI   7.0            8000.0$
 4. UTIL    Jalen Hurts                   QB    PHI            TB@PHI   25.04          15500.0$
 5. UTIL    Kenneth Gainwell              RB    PHI            TB@PHI   8.64           8500.0$

Fantasy Points 96.84
Salary 60000.00

 1. MVP     Tom Brady                     QB    TB             TB@PHI   40.884         16500.0$
 2. UTIL    Antonio Brown                 WR    TB             TB@PHI   15.275         11500.0$
 3. UTIL    Jalen Hurts                   QB    PHI            TB@PHI   25.04          15500.0$
 4. UTIL    Quez Watkins                  WR    PHI            TB@PHI   6.64           7000.0$
 5. UTIL    Ryan Succop                   K     TB             TB@PHI   8.8            9000.0$

Fantasy Points 96.64
Salary 59500.00

 1. MVP     Jalen Hurts                   QB    PHI            TB@PHI   37.56          15500.0$
 2. UTIL    Antonio Brown                 WR    TB             TB@PHI   15.275         11500.0$
 3. UTIL    Giovani Bernard               RB    TB             TB@PHI   7.725          7000.0$
 4. UTIL    Ryan Succop                   K     TB             TB@PHI   8.8            9000.0$
 5. UTIL    Tom Brady                     QB    TB             TB@PHI   27.256         16500.0$

Fantasy Points 96.62
Salary 59500.00

 1. MVP     Tom Brady                     QB    TB             TB@PHI   40.884         16500.0$
 2. UTIL    Antonio Brown                 WR    TB             TB@PHI   15.275         11500.0$
 3. UTIL    Jalen Hurts                   QB    PHI            TB@PHI   25.04          15500.0$
 4. UTIL    Kenneth Gainwell              RB    PHI            TB@PHI   8.64           8500.0$
 5. UTIL    Quez Watkins                  WR    PHI            TB@PHI   6.64           7000.0$

Fantasy Points 96.48
Salary 59000.00

 1. MVP     Jalen Hurts                   QB    PHI            TB@PHI   37.56          15500.0$
 2. UTIL    Antonio Brown                 WR    TB             TB@PHI   15.275         11500.0$
 3. UTIL    Giovani Bernard               RB    TB             TB@PHI   7.725          7000.0$
 4. UTIL    Kenneth Gainwell              RB    PHI            TB@PHI   8.64           8500.0$
 5. UTIL    Tom Brady                     QB    TB             TB@PHI   27.256         16500.0$

Fantasy Points 96.46
Salary 59000.00

 1. MVP     Tom Brady                     QB    TB             TB@PHI   40.884         16500.0$
 2. UTIL    Antonio Brown                 WR    TB             TB@PHI   15.275         11500.0$
 3. UTIL    Jalen Hurts                   QB    PHI            TB@PHI   25.04          15500.0$
 4. UTIL    Jordan Howard                 RB    PHI            TB@PHI   3.775          5000.0$
 5. UTIL    Leonard Fournette             RB    TB             TB@PHI   11.46          11000.0$

Fantasy Points 96.43
Salary 59500.00

 1. MVP     Tom Brady                     QB    TB             TB@PHI   40.884         16500.0$
 2. UTIL    Antonio Brown                 WR    TB             TB@PHI   15.275         11500.0$
 3. UTIL    JJ Arcega-Whiteside           WR    PHI            TB@PHI   3.7            5000.0$
 4. UTIL    Jalen Hurts                   QB    PHI            TB@PHI   25.04          15500.0$
 5. UTIL    Leonard Fournette             RB    TB             TB@PHI   11.46          11000.0$

Fantasy Points 96.36
Salary 59500.00

 1. MVP     Tom Brady                     QB    TB             TB@PHI   40.884         16500.0$
 2. UTIL    Darwin Thompson               RB    TB             TB@PHI   5.94           5000.0$
 3. UTIL    Jalen Hurts                   QB    PHI            TB@PHI   25.04          15500.0$
 4. UTIL    Mike Evans                    WR    TB             TB@PHI   15.56          13500.0$
 5. UTIL    Ryan Succop                   K     TB             TB@PHI   8.8            9000.0$

Fantasy Points 96.22
Salary 59500.00

 1. MVP     Tom Brady                     QB    TB             TB@PHI   40.884         16500.0$
 2. UTIL    Darwin Thompson               RB    TB             TB@PHI   5.94           5000.0$
 3. UTIL    Jalen Hurts                   QB    PHI            TB@PHI   25.04          15500.0$
 4. UTIL    Kenneth Gainwell              RB    PHI            TB@PHI   8.64           8500.0$
 5. UTIL    Mike Evans                    WR    TB             TB@PHI   15.56          13500.0$

Fantasy Points 96.06
Salary 59000.00

 1. MVP     Tom Brady                     QB    TB             TB@PHI   40.884         16500.0$
 2. UTIL    Antonio Brown                 WR    TB             TB@PHI   15.275         11500.0$
 3. UTIL    Darwin Thompson               RB    TB             TB@PHI   5.94           5000.0$
 4. UTIL    Jalen Hurts                   QB    PHI            TB@PHI   25.04          15500.0$
 5. UTIL    Ryan Succop                   K     TB             TB@PHI   8.8            9000.0$

Fantasy Points 95.94
Salary 57500.00

 1. MVP     Tom Brady                     QB    TB             TB@PHI   40.884         16500.0$
 2. UTIL    Antonio Brown                 WR    TB             TB@PHI   15.275         11500.0$
 3. UTIL    Jalen Hurts                   QB    PHI            TB@PHI   25.04          15500.0$
 4. UTIL    Jalen Reagor                  WR    PHI            TB@PHI   5.94           7500.0$
 5. UTIL    Ryan Succop                   K     TB             TB@PHI   8.8            9000.0$

Fantasy Points 95.94
Salary 60000.00

 1. MVP     Tom Brady                     QB    TB             TB@PHI   40.884         16500.0$
 2. UTIL    Antonio Brown                 WR    TB             TB@PHI   15.275         11500.0$
 3. UTIL    Giovani Bernard               RB    TB             TB@PHI   7.725          7000.0$
 4. UTIL    Jake Elliott                  K     PHI            TB@PHI   7.0            8000.0$
 5. UTIL    Jalen Hurts                   QB    PHI            TB@PHI   25.04          15500.0$

Fantasy Points 95.92
Salary 58500.00

 1. MVP     Tom Brady                     QB    TB             TB@PHI   40.884         16500.0$
 2. UTIL    Giovani Bernard               RB    TB             TB@PHI   7.725          7000.0$
 3. UTIL    Jalen Hurts                   QB    PHI            TB@PHI   25.04          15500.0$
 4. UTIL    Mike Evans                    WR    TB             TB@PHI   15.56          13500.0$
 5. UTIL    Quez Watkins                  WR    PHI            TB@PHI   6.64           7000.0$

Fantasy Points 95.85
Salary 59500.00

 1. MVP     Tom Brady                     QB    TB             TB@PHI   40.884         16500.0$
 2. UTIL    Antonio Brown                 WR    TB             TB@PHI   15.275         11500.0$
 3. UTIL    Jalen Hurts                   QB    PHI            TB@PHI   25.04          15500.0$
 4. UTIL    Ryan Succop                   K     TB             TB@PHI   8.8            9000.0$
 5. UTIL    Zach Ertz                     TE    PHI            TB@PHI   5.8            6500.0$

Fantasy Points 95.80
Salary 59000.00

 1. MVP     Tom Brady                     QB    TB             TB@PHI   40.884         16500.0$
 2. UTIL    Antonio Brown                 WR    TB             TB@PHI   15.275         11500.0$
 3. UTIL    Darwin Thompson               RB    TB             TB@PHI   5.94           5000.0$
 4. UTIL    Jalen Hurts                   QB    PHI            TB@PHI   25.04          15500.0$
 5. UTIL    Kenneth Gainwell              RB    PHI            TB@PHI   8.64           8500.0$

Fantasy Points 95.78
Salary 57000.00

 1. MVP     Tom Brady                     QB    TB             TB@PHI   40.884         16500.0$
 2. UTIL    Antonio Brown                 WR    TB             TB@PHI   15.275         11500.0$
 3. UTIL    Jalen Hurts                   QB    PHI            TB@PHI   25.04          15500.0$
 4. UTIL    Jalen Reagor                  WR    PHI            TB@PHI   5.94           7500.0$
 5. UTIL    Kenneth Gainwell              RB    PHI            TB@PHI   8.64           8500.0$

Fantasy Points 95.78
Salary 59500.00