In [1]:
import pandas as pd
import numpy as np

In [2]:
df_fd = pd.read_csv("data/nfl/FanDuel-NFL-2021 ET-10 ET-11 ET-65108-players-list.csv")

In [3]:
df_fd.head()

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
0,65108-63115,QB,Lamar,Lamar Jackson,Jackson,22.995001,4.0,17000,IND@BAL,BAL,IND,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
1,65108-70324,QB,Carson,Carson Wentz,Wentz,15.650000,4.0,14000,IND@BAL,IND,BAL,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
2,65108-86687,WR,Marquise,Marquise Brown,Brown,15.150000,4.0,13500,IND@BAL,BAL,IND,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
3,65108-89675,RB,Jonathan,Jonathan Taylor,Taylor,11.750000,4.0,13000,IND@BAL,IND,BAL,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
4,65108-52436,TE,Mark,Mark Andrews,Andrews,8.575000,4.0,12000,IND@BAL,BAL,IND,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX

In [4]:
df_fd.columns

Index(['Id', 'Position', 'First Name', 'Nickname', 'Last Name', 'FPPG',
       'Played', 'Salary', 'Game', 'Team', 'Opponent', 'Injury Indicator',
       'Injury Details', 'Tier', 'Unnamed: 14', 'Unnamed: 15',
       'Roster Position'],
      dtype='object')

In [5]:
df_fd.set_index('Id',inplace=True)

In [9]:
#df.drop(df.dropna(subset=['columnA']).index)
df_fd = df_fd.drop(df_fd.dropna(subset=['Injury Indicator']).index)
df_fd = df_fd.query("Nickname != 'Carson Wentz'")
df_fd.head()

,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
Id,,,,,,,,,,,,,,,,
65108-63115,QB,Lamar,Lamar Jackson,Jackson,22.995001,4.0,17000,IND@BAL,BAL,IND,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
65108-86687,WR,Marquise,Marquise Brown,Brown,15.150000,4.0,13500,IND@BAL,BAL,IND,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
65108-89675,RB,Jonathan,Jonathan Taylor,Taylor,11.750000,4.0,13000,IND@BAL,IND,BAL,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
65108-52436,TE,Mark,Mark Andrews,Andrews,8.575000,4.0,12000,IND@BAL,BAL,IND,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
65108-69213,WR,Michael,Michael Pittman Jr.,Pittman Jr.,9.975000,4.0,11000,IND@BAL,IND,BAL,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX

In [10]:
df_fd.to_csv('data/nfl/FDprojectionsSD.csv')

In [11]:
from pydfs_lineup_optimizer import Site, Sport, get_optimizer, PlayerFilter, AfterEachExposureStrategy

optimizer = get_optimizer(Site.FANDUEL_SINGLE_GAME, Sport.FOOTBALL)
optimizer.load_players_from_csv("data/nfl/FDprojectionsSD.csv")
for lineup in optimizer.optimize(20, max_exposure=.4, exposure_strategy=AfterEachExposureStrategy):
    print(lineup)
optimizer.export('data/nfl/fd_resultSD.csv')

 1. MVP     Lamar Jackson                 QB    BAL            IND@BAL  34.493         17000.0$
 2. UTIL    Jonathan Taylor               RB    IND            IND@BAL  11.75          13000.0$
 3. UTIL    Justin Tucker                 K     BAL            IND@BAL  12.0           9000.0$
 4. UTIL    Keke Coutee                   WR    IND            IND@BAL  8.812          5000.0$
 5. UTIL    Marquise Brown                WR    BAL            IND@BAL  15.15          13500.0$

Fantasy Points 82.20
Salary 57500.00

 1. MVP     Marquise Brown                WR    BAL            IND@BAL  22.725         13500.0$
 2. UTIL    Lamar Jackson                 QB    BAL            IND@BAL  22.995         17000.0$
 3. UTIL    Michael Pittman Jr.           WR    IND            IND@BAL  9.975          11000.0$
 4. UTIL    Rodrigo Blankenship           K     IND            IND@BAL  9.25           8500.0$
 5. UTIL    Zach Pascal                   WR    IND            IND@BAL  10.275         9500.0$

Fantasy Points 75.22
Salary 59500.00

 1. MVP     Jonathan Taylor               RB    IND            IND@BAL  17.625         13000.0$
 2. UTIL    Latavius Murray               RB    BAL            IND@BAL  8.275          10000.0$
 3. UTIL    Mark Andrews                  TE    BAL            IND@BAL  8.575          12000.0$
 4. UTIL    Sammy Watkins                 WR    BAL            IND@BAL  8.425          7500.0$
 5. UTIL    Ty'Son Williams               RB    BAL            IND@BAL  9.8            10000.0$

Fantasy Points 52.70
Salary 52500.00

 1. MVP     Lamar Jackson                 QB    BAL            IND@BAL  34.493         17000.0$
 2. UTIL    Justin Tucker                 K     BAL            IND@BAL  12.0           9000.0$
 3. UTIL    Marquise Brown                WR    BAL            IND@BAL  15.15          13500.0$
 4. UTIL    Michael Pittman Jr.           WR    IND            IND@BAL  9.975          11000.0$
 5. UTIL    Zach Pascal                   WR    IND            IND@BAL  10.275         9500.0$

Fantasy Points 81.89
Salary 60000.00

 1. MVP     Marquise Brown                WR    BAL            IND@BAL  22.725         13500.0$
 2. UTIL    Jonathan Taylor               RB    IND            IND@BAL  11.75          13000.0$
 3. UTIL    Keke Coutee                   WR    IND            IND@BAL  8.812          5000.0$
 4. UTIL    Lamar Jackson                 QB    BAL            IND@BAL  22.995         17000.0$
 5. UTIL    Ty'Son Williams               RB    BAL            IND@BAL  9.8            10000.0$

Fantasy Points 76.08
Salary 58500.00

 1. MVP     Justin Tucker                 K     BAL            IND@BAL  18.0           9000.0$
 2. UTIL    Latavius Murray               RB    BAL            IND@BAL  8.275          10000.0$
 3. UTIL    Mark Andrews                  TE    BAL            IND@BAL  8.575          12000.0$
 4. UTIL    Rodrigo Blankenship           K     IND            IND@BAL  9.25           8500.0$
 5. UTIL    Sammy Watkins                 WR    BAL            IND@BAL  8.425          7500.0$

Fantasy Points 52.52
Salary 47000.00

 1. MVP     Lamar Jackson                 QB    BAL            IND@BAL  34.493         17000.0$
 2. UTIL    Jonathan Taylor               RB    IND            IND@BAL  11.75          13000.0$
 3. UTIL    Justin Tucker                 K     BAL            IND@BAL  12.0           9000.0$
 4. UTIL    Marquise Brown                WR    BAL            IND@BAL  15.15          13500.0$
 5. UTIL    Sammy Watkins                 WR    BAL            IND@BAL  8.425          7500.0$

Fantasy Points 81.82
Salary 60000.00

 1. MVP     Marquise Brown                WR    BAL            IND@BAL  22.725         13500.0$
 2. UTIL    Lamar Jackson                 QB    BAL            IND@BAL  22.995         17000.0$
 3. UTIL    Rodrigo Blankenship           K     IND            IND@BAL  9.25           8500.0$
 4. UTIL    Ty'Son Williams               RB    BAL            IND@BAL  9.8            10000.0$
 5. UTIL    Zach Pascal                   WR    IND            IND@BAL  10.275         9500.0$

Fantasy Points 75.05
Salary 58500.00

 1. MVP     Lamar Jackson                 QB    BAL            IND@BAL  34.493         17000.0$
 2. UTIL    Justin Tucker                 K     BAL            IND@BAL  12.0           9000.0$
 3. UTIL    Marquise Brown                WR    BAL            IND@BAL  15.15          13500.0$
 4. UTIL    Ty'Son Williams               RB    BAL            IND@BAL  9.8            10000.0$
 5. UTIL    Zach Pascal                   WR    IND            IND@BAL  10.275         9500.0$

Fantasy Points 81.72
Salary 59000.00

 1. MVP     Marquise Brown                WR    BAL            IND@BAL  22.725         13500.0$
 2. UTIL    Jonathan Taylor               RB    IND            IND@BAL  11.75          13000.0$
 3. UTIL    Keke Coutee                   WR    IND            IND@BAL  8.812          5000.0$
 4. UTIL    Lamar Jackson                 QB    BAL            IND@BAL  22.995         17000.0$
 5. UTIL    Michael Pittman Jr.           WR    IND            IND@BAL  9.975          11000.0$

Fantasy Points 76.26
Salary 59500.00

 1. MVP     Justin Tucker                 K     BAL            IND@BAL  18.0           9000.0$
 2. UTIL    Keke Coutee                   WR    IND            IND@BAL  8.812          5000.0$
 3. UTIL    Mark Andrews                  TE    BAL            IND@BAL  8.575          12000.0$
 4. UTIL    Michael Pittman Jr.           WR    IND            IND@BAL  9.975          11000.0$
 5. UTIL    Rodrigo Blankenship           K     IND            IND@BAL  9.25           8500.0$

Fantasy Points 54.61
Salary 45500.00

 1. MVP     Lamar Jackson                 QB    BAL            IND@BAL  34.493         17000.0$
 2. UTIL    Justin Tucker                 K     BAL            IND@BAL  12.0           9000.0$
 3. UTIL    Marquise Brown                WR    BAL            IND@BAL  15.15          13500.0$
 4. UTIL    Rodrigo Blankenship           K     IND            IND@BAL  9.25           8500.0$
 5. UTIL    Zach Pascal                   WR    IND            IND@BAL  10.275         9500.0$

Fantasy Points 81.17
Salary 57500.00

 1. MVP     Marquise Brown                WR    BAL            IND@BAL  22.725         13500.0$
 2. UTIL    Jonathan Taylor               RB    IND            IND@BAL  11.75          13000.0$
 3. UTIL    Keke Coutee                   WR    IND            IND@BAL  8.812          5000.0$
 4. UTIL    Lamar Jackson                 QB    BAL            IND@BAL  22.995         17000.0$
 5. UTIL    Sammy Watkins                 WR    BAL            IND@BAL  8.425          7500.0$

Fantasy Points 74.71
Salary 56000.00

 1. MVP     Lamar Jackson                 QB    BAL            IND@BAL  34.493         17000.0$
 2. UTIL    Justin Tucker                 K     BAL            IND@BAL  12.0           9000.0$
 3. UTIL    Marquise Brown                WR    BAL            IND@BAL  15.15          13500.0$
 4. UTIL    Michael Pittman Jr.           WR    IND            IND@BAL  9.975          11000.0$
 5. UTIL    Rodrigo Blankenship           K     IND            IND@BAL  9.25           8500.0$

Fantasy Points 80.87
Salary 59000.00

 1. MVP     Marquise Brown                WR    BAL            IND@BAL  22.725         13500.0$
 2. UTIL    Jonathan Taylor               RB    IND            IND@BAL  11.75          13000.0$
 3. UTIL    Keke Coutee                   WR    IND            IND@BAL  8.812          5000.0$
 4. UTIL    Lamar Jackson                 QB    BAL            IND@BAL  22.995         17000.0$
 5. UTIL    Zach Pascal                   WR    IND            IND@BAL  10.275         9500.0$

Fantasy Points 76.56
Salary 58000.00

 1. MVP     Justin Tucker                 K     BAL            IND@BAL  18.0           9000.0$
 2. UTIL    Mark Andrews                  TE    BAL            IND@BAL  8.575          12000.0$
 3. UTIL    Michael Pittman Jr.           WR    IND            IND@BAL  9.975          11000.0$
 4. UTIL    Sammy Watkins                 WR    BAL            IND@BAL  8.425          7500.0$
 5. UTIL    Ty'Son Williams               RB    BAL            IND@BAL  9.8            10000.0$

Fantasy Points 54.77
Salary 49500.00

 1. MVP     Lamar Jackson                 QB    BAL            IND@BAL  34.493         17000.0$
 2. UTIL    Justin Tucker                 K     BAL            IND@BAL  12.0           9000.0$
 3. UTIL    Keke Coutee                   WR    IND            IND@BAL  8.812          5000.0$
 4. UTIL    Marquise Brown                WR    BAL            IND@BAL  15.15          13500.0$
 5. UTIL    Zach Pascal                   WR    IND            IND@BAL  10.275         9500.0$

Fantasy Points 80.73
Salary 54000.00

 1. MVP     Marquise Brown                WR    BAL            IND@BAL  22.725         13500.0$
 2. UTIL    Jonathan Taylor               RB    IND            IND@BAL  11.75          13000.0$
 3. UTIL    Lamar Jackson                 QB    BAL            IND@BAL  22.995         17000.0$
 4. UTIL    Rodrigo Blankenship           K     IND            IND@BAL  9.25           8500.0$
 5. UTIL    Sammy Watkins                 WR    BAL            IND@BAL  8.425          7500.0$

Fantasy Points 75.14
Salary 59500.00

 1. MVP     Lamar Jackson                 QB    BAL            IND@BAL  34.493         17000.0$
 2. UTIL    Justin Tucker                 K     BAL            IND@BAL  12.0           9000.0$
 3. UTIL    Marquise Brown                WR    BAL            IND@BAL  15.15          13500.0$
 4. UTIL    Rodrigo Blankenship           K     IND            IND@BAL  9.25           8500.0$
 5. UTIL    Ty'Son Williams               RB    BAL            IND@BAL  9.8            10000.0$

Fantasy Points 80.69
Salary 58000.00

 1. MVP     Marquise Brown                WR    BAL            IND@BAL  22.725         13500.0$
 2. UTIL    Keke Coutee                   WR    IND            IND@BAL  8.812          5000.0$
 3. UTIL    Lamar Jackson                 QB    BAL            IND@BAL  22.995         17000.0$
 4. UTIL    Michael Pittman Jr.           WR    IND            IND@BAL  9.975          11000.0$
 5. UTIL    Zach Pascal                   WR    IND            IND@BAL  10.275         9500.0$

Fantasy Points 74.78
Salary 56000.00