In [1]:
import requests
from bs4 import BeautifulSoup as soup
import pandas as pd
from functions.nba_clean_data import archive_files
from functions.nba_proj_scape import nba_proj_scape

In [2]:
archive_files()

/home/micheal/code/fan_fact/lineupopt/data/nba/FD_proj.csv
/home/micheal/code/fan_fact/lineupopt/data/nba/FanDuel-NBA-2021 ET-11 ET-01 ET-66246-players-list-1.csv
/home/micheal/code/fan_fact/lineupopt/data/nba/fd_result.csv

In [3]:
# %load functions/get_nba_spread
import requests
from bs4 import BeautifulSoup as soup
import pandas as pd

def get_spread_page():
    url = "https://rotogrinders.com/lineups/nba?site=fanduel"
    html = requests.get(url).text
    page = soup(html)
    return page
page = get_spread_page()

team_list = page.find_all("span", {"class": "shrt"})
teams = [i.text for i in team_list]
odds_list = page.find_all("a", {"href": "/nba/odds"})
odds = [i.text for i in odds_list]
teams.sort()
print(teams)

['DAL', 'DET', 'HOU', 'LAL', 'MIA', 'MIL', 'NOP', 'PHO', 'SAC', 'UTA']

In [4]:
df_fd = pd.read_csv('data/nba/FanDuel-NBA-2021 ET-11 ET-02 ET-66298-players-list.csv')
teams2 = list(df_fd.Team.unique())
teams2.sort()
print(teams2)

['DAL', 'DET', 'HOU', 'LAL', 'MIA', 'MIL', 'NO', 'PHO', 'SAC', 'UTA']

In [5]:
replace_dict = {"GSW":"GS", "NYK":"NY", "NOP":"NO", "SAS":"SA"}
clean_teams = [replace_dict.get(item,item) for item in teams]
print(clean_teams)

['DAL', 'DET', 'HOU', 'LAL', 'MIA', 'MIL', 'NO', 'PHO', 'SAC', 'UTA']

In [6]:
df_odds = dict(zip(clean_teams, odds))
#print(df_odds)
print(dict(sorted(df_odds.items(), key=lambda item: item[1])))

{'NO': '102.00', 'DET': '103.75', 'LAL': '103.75', 'SAC': '103.75', 'HOU': '106.25', 'MIA': '106.25', 'DAL': '107.75', 'PHO': '113.50', 'UTA': '113.75', 'MIL': '115.25'}

In [7]:
stats_df = nba_proj_scape()
stats_df.head()

                Nickname    FP Value    Min
0  Giannis Antetokounmpo  57.8  5.12  33.58
1            Luka Doncic  48.7  4.69  34.79
2          Anthony Davis  46.0   4.6  34.19
3      Russell Westbrook  45.2  4.91  35.15
4      Jonas Valanciunas  44.0  5.11  32.08

In [8]:
df_fd = pd.merge(df_fd, stats_df, how='left', on='Nickname')
df_fd.head()

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position,FP,Value,Min
0,66298-40199,PF/SF,Giannis,Giannis Antetokounmpo,Antetokounmpo,54.371429,7.0,11300,MIL@DET,MIL,DET,NaN,NaN,NaN,NaN,NaN,SF/PF,57.8,5.12,33.58
1,66298-84669,PG/SG,Luka,Luka Doncic,Doncic,44.616669,6.0,10400,MIA@DAL,DAL,MIA,NaN,NaN,NaN,NaN,NaN,PG/SG,48.7,4.69,34.79
2,66298-15755,PF/C,Anthony,Anthony Davis,Davis,49.285714,7.0,10000,HOU@LAL,LAL,HOU,NaN,NaN,NaN,NaN,NaN,PF/C,46.0,4.6,34.19
3,66298-14528,SF/SG,Jimmy,Jimmy Butler,Butler,49.149999,6.0,10000,MIA@DAL,MIA,DAL,NaN,NaN,NaN,NaN,NaN,SG/SF,43.8,4.38,34.23
4,66298-9488,SF/PF,LeBron,LeBron James,James,46.360001,5.0,9800,HOU@LAL,LAL,HOU,GTD,Ankle,NaN,NaN,NaN,SF/PF,43.6,4.45,34.16

#%%writefile ./functions/nba20201023.py
df_fd["expts"] = df_fd["Team"].map(df_odds)
df_fd.expts = df_fd.expts.astype('float')
df_fd.Value = df_fd.Value.astype('float')
df_fd.FP = df_fd.FP.astype('float')
pts_bins = [.95, 1.0, 1.05]
val_bins = [.95, 1.0, 1.05]
df_fd["rkpts"] = pd.cut(df_fd.expts, 3, labels=pts_bins)
df_fd.rkpts = df_fd.rkpts.astype('float')
df_fd['vlpts'] = pd.cut(df_fd.Value, 3, labels=val_bins)
df_fd.vlpts = df_fd.vlpts.astype('float')
df_fd["new_expts"] = df_fd.FP * df_fd.vlpts * df_fd.rkpts

In [12]:
pd.set_option('display.max_rows', df_fd.shape[0]+1)
df_fd

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
0,66298-40199,PF/SF,Giannis,Giannis Antetokounmpo,Antetokounmpo,57.8,7.0,11300,MIL@DET,MIL,DET,NaN,NaN,NaN,NaN,NaN,SF/PF
1,66298-84669,PG/SG,Luka,Luka Doncic,Doncic,48.7,6.0,10400,MIA@DAL,DAL,MIA,NaN,NaN,NaN,NaN,NaN,PG/SG
2,66298-15755,PF/C,Anthony,Anthony Davis,Davis,46.0,7.0,10000,HOU@LAL,LAL,HOU,NaN,NaN,NaN,NaN,NaN,PF/C
3,66298-14528,SF/SG,Jimmy,Jimmy Butler,Butler,43.8,6.0,10000,MIA@DAL,MIA,DAL,NaN,NaN,NaN,NaN,NaN,SG/SF
4,66298-9488,SF/PF,LeBron,LeBron James,James,43.6,5.0,9800,HOU@LAL,LAL,HOU,GTD,Ankle,NaN,NaN,NaN,SF/PF
5,66298-9642,PG/SG,Russell,Russell Westbrook,Westbrook,45.2,7.0,9200,HOU@LAL,LAL,HOU,NaN,NaN,NaN,NaN,NaN,PG/SG
6,66298-14503,C,Jonas,Jonas Valanciunas,Valanciunas,44.0,7.0,8600,NO@PHO,NO,PHO,NaN,NaN,NaN,NaN,NaN,C
7,66298-80817,C/PF,Bam,Bam Adebayo,Adebayo,39.7,5.0,8500,MIA@DAL,MIA,DAL,NaN,NaN,NaN,NaN,NaN,PF/C
8,66298-110310,PF,Zion,Zion Williamson,Williamson,NaN,62.0,8300,NO@PHO,NO,PHO,O,Foot,NaN,NaN,NaN,PF
9,66298-66048,SF,Brandon,Brandon Ingram,Ingram,0.0,6.0,8200,NO@PHO,NO,PHO,GTD,Hip,NaN,NaN,NaN,SF
10,66298-40203,C,Rudy,Rudy Gobert,Gobert,39.9,6.0,8200,SAC@UTA,UTA,SAC,NaN,NaN,NaN,NaN,NaN,C
11,66298-58460,SG,Devin,Devin Booker,Booker,37.6,5.0,8200,NO@PHO,PHO,NO,NaN,NaN,NaN,NaN,NaN,SG
12,66298-66113,SG/PG,Donovan,Donovan Mitchell,Mitchell,39.9,6.0,8000,SAC@UTA,UTA,SAC,NaN,NaN,NaN,NaN,NaN,PG/SG
13,66298-42202,PF/C,Christian,Christian Wood,Wood,40.0,6.0,7900,HOU@LAL,HOU,LAL,NaN,NaN,NaN,NaN,NaN,PF/C
14,66298-16261,SF/SG,Khris,Khris Middleton,Middleton,0.0,6.0,7800,MIL@DET,MIL,DET,O,Covid-19,NaN,NaN,NaN,SG/SF
15,66298-9623,PG,Chris,Chris Paul,Paul,36.7,5.0,7800,NO@PHO,PHO,NO,NaN,NaN,NaN,NaN,NaN,PG
16,66298-84673,C,Deandre,Deandre Ayton,Ayton,33.0,5.0,7800,NO@PHO,PHO,NO,GTD,Lower leg,NaN,NaN,NaN,C
17,66298-15946,SF/PF,Harrison,Harrison Barnes,Barnes,33.2,6.0,7700,SAC@UTA,SAC,UTA,NaN,NaN,NaN,NaN,NaN,SF/PF
18,66298-80810,PG,De'Aaron,De'Aaron Fox,Fox,38.7,6.0,7700,SAC@UTA,SAC,UTA,NaN,NaN,NaN,NaN,NaN,PG
19,66298-23447,C/PF,Richaun,Richaun Holmes,Holmes,33.5,6.0,7500,SAC@UTA,SAC,UTA,NaN,NaN,NaN,NaN,NaN,PF/C
20,66298-23831,PF,Jerami,Jerami Grant,Grant,31.9,5.0,7400,MIL@DET,DET,MIL,NaN,NaN,NaN,NaN,NaN,PF
21,66298-9663,PG/SG,Jrue,Jrue Holiday,Holiday,0.0,2.0,7300,MIL@DET,MIL,DET,O,Ankle,NaN,NaN,NaN,PG/SG
22,66298-63122,PF/C,Kristaps,Kristaps Porzingis,Porzingis,0.0,3.0,7000,MIA@DAL,DAL,MIA,O,Back,NaN,NaN,NaN,PF/C
23,66298-84706,PG/SG,Devonte',Devonte' Graham,Graham,31.8,7.0,6800,NO@PHO,NO,PHO,GTD,Hip,NaN,NaN,NaN,PG/SG
24,66298-23665,SG/SF,Buddy,Buddy Hield,Hield,27.5,6.0,6600,SAC@UTA,SAC,UTA,NaN,NaN,NaN,NaN,NaN,SG/SF
25,66298-145328,SF,Saddiq,Saddiq Bey,Bey,27.3,6.0,6500,MIL@DET,DET,MIL,GTD,Ankle,NaN,NaN,NaN,SF
26,66298-110312,SG/SF,Tyler,Tyler Herro,Herro,27.1,6.0,6400,MIA@DAL,MIA,DAL,NaN,NaN,NaN,NaN,NaN,SG/SF
27,66298-110356,SG/SF,Nickeil,Nickeil Alexander-Walker,Alexander-Walker,32.6,7.0,6100,NO@PHO,NO,PHO,NaN,NaN,NaN,NaN,NaN,SG/SF
28,66298-22541,C/PF,Kelly,Kelly Olynyk,Olynyk,26.8,6.0,6000,MIL@DET,DET,MIL,NaN,NaN,NaN,NaN,NaN,PF/C
29,66298-9508,SF/PF,Carmelo,Carmelo Anthony,Anthony,21.8,7.0,6000,HOU@LAL,LAL,HOU,NaN,NaN,NaN,NaN,NaN,SF/PF
30,66298-145337,PG/SG,Tyrese,Tyrese Haliburton,Haliburton,29.5,6.0,6000,SAC@UTA,SAC,UTA,NaN,NaN,NaN,NaN,NaN,PG/SG
31,66298-110345,SF/PG,Kevin,Kevin Porter,Porter,26.3,6.0,5900,HOU@LAL,HOU,LAL,NaN,NaN,NaN,NaN,NaN,PG/SF
32,66298-9535,PG,Kyle,Kyle Lowry,Lowry,30.9,5.0,5900,MIA@DAL,MIA,DAL,NaN,NaN,NaN,NaN,NaN,PG
33,66298-9621,C,Brook,Brook Lopez,Lopez,0.0,1.0,5800,MIL@DET,MIL,DET,O,Back,NaN,NaN,NaN,C
34,66298-157907,SG/PG,Jalen,Jalen Green,Green,24.2,6.0,5800,HOU@LAL,HOU,LAL,NaN,NaN,NaN,NaN,NaN,PG/SG
35,66298-84670,SF/PF,Mikal,Mikal Bridges,Bridges,27.3,5.0,5700,NO@PHO,PHO,NO,NaN,NaN,NaN,NaN,NaN,SF/PF
36,66298-9575,PG,Mike,Mike Conley,Conley,30.2,5.0,5500,SAC@UTA,UTA,SAC,NaN,NaN,NaN,NaN,NaN,PG
37,66298-40562,SG/SF,Josh,Josh Hart,Hart,28.9,3.0,5500,NO@PHO,NO,PHO,NaN,NaN,NaN,NaN,NaN,SG/SF
38,66298-20640,PG/SG,Jordan,Jordan Clarkson,Clarkson,23.8,6.0,5400,SAC@UTA,UTA,SAC,NaN,NaN,NaN,NaN,NaN,PG/SG
39,66298-14530,SF/PF,Bojan,Bojan Bogdanovic,Bogdanovic,24.5,6.0,5400,SAC@UTA,UTA,SAC,NaN,NaN,NaN,NaN,NaN,SF/PF
40,66298-145307,PF,Isaiah,Isaiah Stewart,Stewart,25.4,6.0,5200,MIL@DET,DET,MIL,NaN,NaN,NaN,NaN,NaN,PF
41,66298-145576,SF/PF,Jae'Sean,Jae'Sean Tate,Tate,28.7,6.0,5200,HOU@LAL,HOU,LAL,GTD,Ankle,NaN,NaN,NaN,SF/PF
42,66298-157908,C/PF,Alperen,Alperen Sengun,Sengun,22.8,6.0,5100,HOU@LAL,HOU,LAL,NaN,NaN,NaN,NaN,NaN,PF/C
43,66298-16376,SF/SG,Dorian,Dorian Finney-Smith,Finney-Smith,21.7,6.0,5100,MIA@DAL,DAL,MIA,NaN,NaN,NaN,NaN,NaN,SG/SF
44,66298-157808,PG/SG,Cade,Cade Cunningham,Cunningham,24.1,1.0,5000,MIL@DET,DET,MIL,NaN,NaN,NaN,NaN,NaN,PG/SG
45,66298-15993,SG/SF,Pat,Pat Connaughton,Connaughton,22.0,7.0,5000,MIL@DET,MIL,DET,NaN,NaN,NaN,NaN,NaN,SG/SF
46,66298-15846,SG/SF,Tim,Tim Hardaway,Hardaway,NaN,6.0,5000,MIA@DAL,DAL,MIA,NaN,NaN,NaN,NaN,NaN,SG/SF
47,66298-84711,SG,Grayson,Grayson Allen,Allen,25.0,7.0,4900,MIL@DET,MIL,DET,GTD,Knee,NaN,NaN,NaN,SG
48,66298-16196,C/PF,Dwight,Dwight Powell,Powell,26.0,6.0,4800,MIA@DAL,DAL,MIA,NaN,NaN,NaN,NaN,NaN,PF/C
49,66298-42156,PF/C,Bobby,Bobby Portis,Portis,22.7,2.0,4700,MIL@DET,MIL,DET,NaN,NaN,NaN,NaN,NaN,PF/C
50,66298-59318,SG/SF,Joe,Joe Ingles,Ingles,19.9,6.0,4700,SAC@UTA,UTA,SAC,NaN,NaN,NaN,NaN,NaN,SG/SF
51,66298-84681,SG,Donte,Donte DiVincenzo,DiVincenzo,NaN,69.0,4700,MIL@DET,MIL,DET,O,Ankle,NaN,NaN,NaN,SG
52,66298-15684,SG/PG,Victor,Victor Oladipo,Oladipo,NaN,33.0,4600,MIA@DAL,MIA,DAL,O,Quadriceps,NaN,NaN,NaN,PG/SG
53,66298-9577,PF/SF,Rudy,Rudy Gay,Gay,NaN,64.0,4600,SAC@UTA,UTA,SAC,O,Heel,NaN,NaN,NaN,SF/PF
54,66298-84690,PG/SG,Jalen,Jalen Brunson,Brunson,24.0,6.0,4600,MIA@DAL,DAL,MIA,NaN,NaN,NaN,NaN,NaN,PG/SG
55,66298-9703,PG,George,George Hill,Hill,23.6,7.0,4600,MIL@DET,MIL,DET,NaN,NaN,NaN,NaN,NaN,PG
56,66298-12363,C,Hassan,Hassan Whiteside,Whiteside,16.6,6.0,4500,SAC@UTA,UTA,SAC,NaN,NaN,NaN,NaN,NaN,C
57,66298-145489,PG,Killian,Killian Hayes,Hayes,18.6,6.0,4500,MIL@DET,DET,MIL,NaN,NaN,NaN,NaN,NaN,PG
58,66298-145313,PF/SF,Jordan,Jordan Nwora,Nwora,19.4,7.0,4500,MIL@DET,MIL,DET,NaN,NaN,NaN,NaN,NaN,SF/PF
59,66298-16301,C,Dewayne,Dewayne Dedmon,Dedmon,15.8,6.0,4500,MIA@DAL,MIA,DAL,NaN,NaN,NaN,NaN,NaN,C
60,66298-110340,PF,Jaxson,Jaxson Hayes,Hayes,13.1,7.0,4400,NO@PHO,NO,PHO,NaN,NaN,NaN,NaN,NaN,PF
61,66298-85137,SG/SF,Duncan,Duncan Robinson,Robinson,21.0,6.0,4400,MIA@DAL,MIA,DAL,NaN,NaN,NaN,NaN,NaN,SG/SF
62,66298-80809,SG,Josh,Josh Jackson,Jackson,17.7,6.0,4400,MIL@DET,DET,MIL,NaN,NaN,NaN,NaN,NaN,SG
63,66298-101329,SG/PG,Kendrick,Kendrick Nunn,Nunn,NaN,60.0,4400,HOU@LAL,LAL,HOU,O,Knee,NaN,NaN,NaN,PG/SG
64,66298-110337,SG/SF,Talen,Talen Horton-Tucker,Horton-Tucker,NaN,70.0,4300,HOU@LAL,LAL,HOU,O,Thumb,NaN,NaN,NaN,SG/SF
65,66298-9739,C,JaVale,JaVale McGee,McGee,19.1,5.0,4300,NO@PHO,PHO,NO,NaN,NaN,NaN,NaN,NaN,C
66,66298-9538,PF/SF,Trevor,Trevor Ariza,Ariza,NaN,34.0,4300,HOU@LAL,LAL,HOU,O,Ankle,NaN,NaN,NaN,SF/PF
67,66298-18338,SF/PF,Royce,Royce O'Neale,O'Neale,20.9,6.0,4300,SAC@UTA,UTA,SAC,NaN,NaN,NaN,NaN,NaN,SF/PF
68,66298-111372,SF/PF,Thanasis,Thanasis Antetokounmpo,Antetokounmpo,21.7,7.0,4200,MIL@DET,MIL,DET,NaN,NaN,NaN,NaN,NaN,SF/PF
69,66298-9556,SF/SG,Eric,Eric Gordon,Gordon,27.1,6.0,4200,HOU@LAL,HOU,LAL,NaN,NaN,NaN,NaN,NaN,SG/SF
70,66298-23407,PF/C,P.J.,P.J. Tucker,Tucker,14.4,6.0,4200,MIA@DAL,MIA,DAL,NaN,NaN,NaN,NaN,NaN,PF/C
71,66298-15800,PF/SF,Jae,Jae Crowder,Crowder,22.2,5.0,4200,NO@PHO,PHO,NO,NaN,NaN,NaN,NaN,NaN,SF/PF
72,66298-14529,PG,Cory,Cory Joseph,Joseph,14.9,6.0,4200,MIL@DET,DET,MIL,NaN,NaN,NaN,NaN,NaN,PG
73,66298-19138,PG,Elfrid,Elfrid Payton,Payton,10.5,3.0,4200,NO@PHO,PHO,NO,NaN,NaN,NaN,NaN,NaN,PG
74,66298-15904,SG/SF,Rodney,Rodney Hood,Hood,6.3,4.0,4100,MIL@DET,MIL,DET,GTD,Hand,NaN,NaN,NaN,SG/SF
75,66298-81621,PF,Maxi,Maxi Kleber,Kleber,0.0,6.0,4100,MIA@DAL,DAL,MIA,O,Back,NaN,NaN,NaN,PF
76,66298-110316,SF,Cameron,Cameron Johnson,Johnson,19.3,5.0,4100,NO@PHO,PHO,NO,NaN,NaN,NaN,NaN,NaN,SF
77,66298-19781,SF/SG,Kent,Kent Bazemore,Bazemore,20.6,7.0,4000,HOU@LAL,LAL,HOU,NaN,NaN,NaN,NaN,NaN,SG/SF
78,66298-157812,PG,Davion,Davion Mitchell,Mitchell,24.2,6.0,4000,SAC@UTA,SAC,UTA,NaN,NaN,NaN,NaN,NaN,PG
79,66298-81529,PF/C,Daniel,Daniel Theis,Theis,19.4,6.0,4000,HOU@LAL,HOU,LAL,GTD,Toe,NaN,NaN,NaN,PF/C
80,66298-157848,PF,Herbert,Herbert Jones,Jones,25.0,7.0,4000,NO@PHO,NO,PHO,NaN,NaN,NaN,NaN,NaN,PF
81,66298-80816,SG,Malik,Malik Monk,Monk,0.0,7.0,4000,HOU@LAL,LAL,HOU,NaN,NaN,NaN,NaN,NaN,SG
82,66298-12334,SG,Avery,Avery Bradley,Bradley,16.5,6.0,3900,HOU@LAL,LAL,HOU,NaN,NaN,NaN,NaN,NaN,SG
83,66298-48567,PG/SG,Cameron,Cameron Payne,Payne,0.0,2.0,3900,NO@PHO,PHO,NO,O,Hamstring,NaN,NaN,NaN,PG/SG
84,66298-84699,SG/SF,Hamidou,Hamidou Diallo,Diallo,0.0,5.0,3900,MIL@DET,DET,MIL,NaN,NaN,NaN,NaN,NaN,SG/SF
85,66298-110323,C/PF,Eric,Eric Paschall,Paschall,13.2,6.0,3900,SAC@UTA,UTA,SAC,NaN,NaN,NaN,NaN,NaN,PF/C
86,66298-23823,C/PF,Willie,Willie Cauley-Stein,Cauley-Stein,13.7,6.0,3800,MIA@DAL,DAL,MIA,NaN,NaN,NaN,NaN,NaN,PF/C
87,66298-9561,C,DeAndre,DeAndre Jordan,Jordan,0.0,7.0,3800,HOU@LAL,LAL,HOU,NaN,NaN,NaN,NaN,NaN,C
88,66298-58461,PF,Trey,Trey Lyles,Lyles,10.3,6.0,3800,MIL@DET,DET,MIL,NaN,NaN,NaN,NaN,NaN,PF
89,66298-9956,SG,Wayne,Wayne Ellington,Ellington,9.3,46.0,3800,HOU@LAL,LAL,HOU,GTD,Hamstring,NaN,NaN,NaN,SG
90,66298-9455,PG,Rajon,Rajon Rondo,Rondo,11.2,4.0,3800,HOU@LAL,LAL,HOU,NaN,NaN,NaN,NaN,NaN,PG
91,66298-16178,SF/PF,Maurice,Maurice Harkless,Harkless,15.4,5.0,3700,SAC@UTA,SAC,UTA,NaN,NaN,NaN,NaN,NaN,SF/PF
92,66298-11074,SF,Garrett,Garrett Temple,Temple,7.2,5.0,3700,NO@PHO,NO,PHO,GTD,Ankle,NaN,NaN,NaN,SF
93,66298-15947,SG,Reggie,Reggie Bullock,Bullock,18.5,6.0,3700,MIA@DAL,DAL,MIA,NaN,NaN,NaN,NaN,NaN,SG
94,66298-63826,C,Boban,Boban Marjanovic,Marjanovic,5.6,2.0,3700,MIA@DAL,DAL,MIA,NaN,NaN,NaN,NaN,NaN,C
95,66298-157801,SG,Jared,Jared Butler,Butler,0.0,6.0,3700,SAC@UTA,UTA,SAC,NaN,NaN,NaN,NaN,NaN,SG
96,66298-145533,SF/PF,KJ,KJ Martin,Martin,NaN,5.0,3700,HOU@LAL,HOU,LAL,NaN,NaN,NaN,NaN,NaN,SF/PF
97,66298-157847,SF,Trey,Trey Murphy,Murphy,NaN,7.0,3700,NO@PHO,NO,PHO,NaN,NaN,NaN,NaN,NaN,SF
98,66298-145819,SF,Naji,Naji Marshall,Marshall,19.0,7.0,3700,NO@PHO,NO,PHO,NaN,NaN,NaN,NaN,NaN,SF
99,66298-145316,PG,Kira,Kira Lewis,Lewis,NaN,7.0,3700,NO@PHO,NO,PHO,NaN,NaN,NaN,NaN,NaN,PG
100,66298-80813,PG,Frank,Frank Ntilikina,Ntilikina,12.9,5.0,3700,MIA@DAL,DAL,MIA,NaN,NaN,NaN,NaN,NaN,PG
101,66298-14511,PF/SF,Markieff,Markieff Morris,Morris,16.5,6.0,3700,MIA@DAL,MIA,DAL,NaN,NaN,NaN,NaN,NaN,SF/PF
102,66298-80824,PG,Frank,Frank Jackson,Jackson,12.0,6.0,3700,MIL@DET,DET,MIL,NaN,NaN,NaN,NaN,NaN,PG
103,66298-9660,C,Dwight,Dwight Howard,Howard,15.3,6.0,3700,HOU@LAL,LAL,HOU,GTD,Neck,NaN,NaN,NaN,C
104,66298-15814,C/PF,Alex,Alex Len,Len,0.0,3.0,3700,SAC@UTA,SAC,UTA,NaN,NaN,NaN,NaN,NaN,PF/C
105,66298-15843,PG/SG,Trey,Trey Burke,Burke,0.0,3.0,3700,MIA@DAL,DAL,MIA,O,Covid-19,NaN,NaN,NaN,PG/SG
106,66298-42733,SF/SG,David,David Nwaba,Nwaba,14.1,6.0,3700,HOU@LAL,HOU,LAL,NaN,NaN,NaN,NaN,NaN,SG/SF
107,66298-84724,SG,Landry,Landry Shamet,Shamet,13.3,5.0,3700,NO@PHO,PHO,NO,NaN,NaN,NaN,NaN,NaN,SG
108,66298-23294,SF,Danuel,Danuel House,House,NaN,3.0,3700,HOU@LAL,HOU,LAL,O,Ankle,NaN,NaN,NaN,SF
109,66298-111371,PG,Justin,Justin Robinson,Robinson,12.3,7.0,3600,MIL@DET,MIL,DET,NaN,NaN,NaN,NaN,NaN,PG
110,66298-112708,SG,Max,Max Strus,Strus,0.0,6.0,3600,MIA@DAL,MIA,DAL,O,Knee,NaN,NaN,NaN,SG
111,66298-14501,C/PF,Tristan,Tristan Thompson,Thompson,17.8,4.0,3600,SAC@UTA,SAC,UTA,NaN,NaN,NaN,NaN,NaN,PF/C
112,66298-158136,SG,Austin,Austin Reaves,Reaves,9.7,6.0,3600,HOU@LAL,LAL,HOU,NaN,NaN,NaN,NaN,NaN,SG
113,66298-111622,SF,Garrison,Garrison Mathews,Mathews,0.0,69.0,3500,HOU@LAL,HOU,LAL,NaN,NaN,NaN,NaN,NaN,SF
114,66298-101387,PG,Gabe,Gabe Vincent,Vincent,0.0,5.0,3500,MIA@DAL,MIA,DAL,NaN,NaN,NaN,NaN,NaN,PG
115,66298-19726,SF,Abdel,Abdel Nader,Nader,8.1,4.0,3500,NO@PHO,PHO,NO,NaN,NaN,NaN,NaN,NaN,SF
116,66298-55056,PF,Dario,Dario Saric,Saric,0.0,64.0,3500,NO@PHO,PHO,NO,O,Knee,NaN,NaN,NaN,PF
117,66298-117782,SF,Daulton,Daulton Hommes,Hommes,NaN,NaN,3500,NO@PHO,NO,PHO,O,Leg,NaN,NaN,NaN,SF
118,66298-158243,SF,Ish,Ish Wainright,Wainright,NaN,NaN,3500,NO@PHO,PHO,NO,NaN,NaN,NaN,NaN,NaN,SF
119,66298-117286,C,Moses,Moses Brown,Brown,6.6,3.0,3500,MIA@DAL,DAL,MIA,NaN,NaN,NaN,NaN,NaN,C
120,66298-117291,SG,Armoni,Armoni Brooks,Brooks,0.0,4.0,3500,HOU@LAL,HOU,LAL,NaN,NaN,NaN,NaN,NaN,SG
121,66298-12332,PG/SG,John,John Wall,Wall,0.0,40.0,3500,HOU@LAL,HOU,LAL,O,Not injury related,NaN,NaN,NaN,PG/SG
122,66298-110639,SG/SF,Sekou,Sekou Doumbouya,Doumbouya,0.0,56.0,3500,HOU@LAL,LAL,HOU,NaN,NaN,NaN,NaN,NaN,SG/SF
123,66298-110641,SG,Didi,Didi Louzada,Louzada,0.0,3.0,3500,NO@PHO,NO,PHO,NaN,NaN,NaN,NaN,NaN,SG
124,66298-117297,SF/PF,Louis,Louis King,King,0.0,6.0,3500,SAC@UTA,SAC,UTA,NaN,NaN,NaN,NaN,NaN,SF/PF
125,66298-23097,PG,Tomas,Tomas Satoransky,Satoransky,0.7,3.0,3500,NO@PHO,NO,PHO,NaN,NaN,NaN,NaN,NaN,PG
126,66298-16448,PF/C,Frank,Frank Kaminsky,Kaminsky,0.0,1.0,3500,NO@PHO,PHO,NO,NaN,NaN,NaN,NaN,NaN,PF/C
127,66298-40262,SG,Sterling,Sterling Brown,Brown,7.5,4.0,3500,MIA@DAL,DAL,MIA,NaN,NaN,NaN,NaN,NaN,SG
128,66298-157803,SG,Josh,Josh Christopher,Christopher,0.0,5.0,3500,HOU@LAL,HOU,LAL,NaN,NaN,NaN,NaN,NaN,SG
129,66298-157807,C,Luka,Luka Garza,Garza,0.0,4.0,3500,MIL@DET,DET,MIL,NaN,NaN,NaN,NaN,NaN,C
130,66298-157810,PF,Isaiah,Isaiah Livers,Livers,0.0,NaN,3500,MIL@DET,DET,MIL,NaN,NaN,NaN,NaN,NaN,PF
131,66298-157811,C,Neemias,Neemias Queta,Queta,0.0,NaN,3500,SAC@UTA,SAC,UTA,NaN,NaN,NaN,NaN,NaN,C
132,66298-113267,SG/SF,Caleb,Caleb Martin,Martin,9.6,3.0,3500,MIA@DAL,MIA,DAL,NaN,NaN,NaN,NaN,NaN,SG/SF
133,66298-9589,PF,Udonis,Udonis Haslem,Haslem,0.0,1.0,3500,MIA@DAL,MIA,DAL,NaN,NaN,NaN,NaN,NaN,PF
134,66298-116340,SG/SF,Terence,Terence Davis,Davis,7.6,6.0,3500,SAC@UTA,SAC,UTA,NaN,NaN,NaN,NaN,NaN,SG/SF
135,66298-41082,C,Damian,Damian Jones,Jones,0.0,39.0,3500,SAC@UTA,SAC,UTA,NaN,NaN,NaN,NaN,NaN,C
136,66298-159097,C,Jay,Jay Huff,Huff,NaN,NaN,3500,HOU@LAL,LAL,HOU,NaN,NaN,NaN,NaN,NaN,C
137,66298-15744,SG,Rodney,Rodney McGruder,McGruder,0.0,3.0,3500,MIL@DET,DET,MIL,NaN,NaN,NaN,NaN,NaN,SG
138,66298-161665,SF,Jamorko,Jamorko Pickett,Pickett,0.0,3.0,3500,MIL@DET,DET,MIL,NaN,NaN,NaN,NaN,NaN,SF
139,66298-158853,PF,Chris,Chris Smith,Smith,NaN,NaN,3500,MIL@DET,DET,MIL,O,Knee,NaN,NaN,NaN,PF
140,66298-157846,PF/C,Sandro,Sandro Mamukelashvili,Mamukelashvili,0.2,6.0,3500,MIL@DET,MIL,DET,NaN,NaN,NaN,NaN,NaN,PF/C
141,66298-63127,PF/C,Willy,Willy Hernangomez,Hernangomez,0.0,1.0,3500,NO@PHO,NO,PHO,NaN,NaN,NaN,NaN,NaN,PF/C
142,66298-145310,PG,Saben,Saben Lee,Lee,0.0,3.0,3500,MIL@DET,DET,MIL,NaN,NaN,NaN,NaN,NaN,PG
143,66298-145309,C,Udoka,Udoka Azubuike,Azubuike,NaN,16.0,3500,SAC@UTA,UTA,SAC,NaN,NaN,NaN,NaN,NaN,C
144,66298-145315,SF,Elijah,Elijah Hughes,Hughes,0.0,2.0,3500,SAC@UTA,UTA,SAC,NaN,NaN,NaN,NaN,NaN,SF
145,66298-145825,PF,Malik,Malik Fitts,Fitts,NaN,2.0,3500,SAC@UTA,UTA,SAC,NaN,NaN,NaN,NaN,NaN,PF
146,66298-158373,PG,Jose,Jose Alvarado,Alvarado,NaN,NaN,3500,NO@PHO,NO,PHO,NaN,NaN,NaN,NaN,NaN,PG
147,66298-145322,PF/C,Jalen,Jalen Smith,Smith,0.0,2.0,3500,NO@PHO,PHO,NO,NaN,NaN,NaN,NaN,NaN,PF/C
148,66298-161452,PG,JaQuori,JaQuori McLaughlin,McLaughlin,NaN,NaN,3500,MIA@DAL,DAL,MIA,NaN,NaN,NaN,NaN,NaN,PG
149,66298-145325,SG,Josh,Josh Green,Green,0.0,3.0,3500,MIA@DAL,DAL,MIA,NaN,NaN,NaN,NaN,NaN,SG
150,66298-145338,PG,Jahmi'us,Jahmi'us Ramsey,Ramsey,0.0,13.0,3500,SAC@UTA,SAC,UTA,NaN,NaN,NaN,NaN,NaN,PG
151,66298-160963,PG,Daishen,Daishen Nix,Nix,NaN,NaN,3500,HOU@LAL,HOU,LAL,NaN,NaN,NaN,NaN,NaN,PG
152,66298-145350,PF,Robert,Robert Woodard,Woodard,NaN,13.0,3500,SAC@UTA,SAC,UTA,NaN,NaN,NaN,NaN,NaN,PF
153,66298-145351,C,Omer,Omer Yurtseven,Yurtseven,0.0,4.0,3500,MIA@DAL,MIA,DAL,NaN,NaN,NaN,NaN,NaN,C
154,66298-84679,PF/C,Marvin,Marvin Bagley,Bagley,NaN,1.0,3500,SAC@UTA,SAC,UTA,NaN,NaN,NaN,NaN,NaN,PF/C
155,66298-145352,SG,Trent,Trent Forrest,Forrest,0.0,3.0,3500,SAC@UTA,UTA,SAC,NaN,NaN,NaN,NaN,NaN,SG
156,66298-157906,PF,Usman,Usman Garuba,Garuba,0.0,4.0,3500,HOU@LAL,HOU,LAL,NaN,NaN,NaN,NaN,NaN,PF
157,66298-159702,SF,Eugene,Eugene Omoruyi,Omoruyi,NaN,1.0,3500,MIA@DAL,DAL,MIA,NaN,NaN,NaN,NaN,NaN,SF
158,66298-48598,SF,Semi,Semi Ojeleye,Ojeleye,7.0,2.0,3500,MIL@DET,MIL,DET,NaN,NaN,NaN,NaN,NaN,SF
159,66298-157909,SF,Georgios,Georgios Kalaitzakis,Kalaitzakis,NaN,4.0,3500,MIL@DET,MIL,DET,NaN,NaN,NaN,NaN,NaN,SF
160,66298-84701,C,Chimezie,Chimezie Metu,Metu,0.0,36.0,3500,SAC@UTA,SAC,UTA,NaN,NaN,NaN,NaN,NaN,C
161,66298-84707,SF,Chandler,Chandler Hutchison,Hutchison,NaN,1.0,3500,NO@PHO,PHO,NO,NaN,NaN,NaN,NaN,NaN,SF
162,66298-110309,SF,KZ,KZ Okpala,Okpala,0.0,4.0,3500,MIA@DAL,MIA,DAL,O,Ankle,NaN,NaN,NaN,SF
163,66298-110324,SG,Miye,Miye Oni,Oni,0.0,2.0,3500,SAC@UTA,UTA,SAC,NaN,NaN,NaN,NaN,NaN,SG
164,66298-9466,PG/SG,D.J.,D.J. Augustin,Augustin,12.1,6.0,3500,HOU@LAL,HOU,LAL,NaN,NaN,NaN,NaN,NaN,PG/SG

In [10]:
df_fd['FPPG'] = df_fd.FP
dropped_cols = ['FP', 'Value', 'Min']#, 'expts', 'rkpts', 'vlpts', 'new_expts']
df_fd.drop(dropped_cols, axis=1, inplace=True)
df_fd.head()

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
0,66298-40199,PF/SF,Giannis,Giannis Antetokounmpo,Antetokounmpo,57.8,7.0,11300,MIL@DET,MIL,DET,NaN,NaN,NaN,NaN,NaN,SF/PF
1,66298-84669,PG/SG,Luka,Luka Doncic,Doncic,48.7,6.0,10400,MIA@DAL,DAL,MIA,NaN,NaN,NaN,NaN,NaN,PG/SG
2,66298-15755,PF/C,Anthony,Anthony Davis,Davis,46.0,7.0,10000,HOU@LAL,LAL,HOU,NaN,NaN,NaN,NaN,NaN,PF/C
3,66298-14528,SF/SG,Jimmy,Jimmy Butler,Butler,43.8,6.0,10000,MIA@DAL,MIA,DAL,NaN,NaN,NaN,NaN,NaN,SG/SF
4,66298-9488,SF/PF,LeBron,LeBron James,James,43.6,5.0,9800,HOU@LAL,LAL,HOU,GTD,Ankle,NaN,NaN,NaN,SF/PF

In [11]:
df_fd.to_csv('data/nba/FD_proj.csv')

In [11]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [14]:
from pydfs_lineup_optimizer import Site, Sport, get_optimizer, PlayerFilter, AfterEachExposureStrategy, TeamStack

optimizer = get_optimizer(Site.FANDUEL, Sport.BASKETBALL)
optimizer.load_players_from_csv("data/nba/FD_proj.csv")
p1 = optimizer.player_pool.get_player_by_name("De'Aaron Fox")
p2 = optimizer.player_pool.get_player_by_name('Kevin Porter')
p3 = optimizer.player_pool.get_player_by_name('Anthony Davis')
p4 = optimizer.player_pool.get_player_by_name('Christian Wood')
p5 = optimizer.player_pool.get_player_by_name('Giannis Antetokounmpo')

p1.max_exposure = 0.75
p1.min_exposure = 0.35
p2.max_exposure = 0.75 
p2.min_exposure = 0.34
p3.max_exposure = 0.75
p3.min_exposure = 0.32
p4.max_exposure = 0.75
p4.min_exposure = 0.30
p5.max_exposure = 0.75
p5.min_exposure = 0.30

optimizer.player_pool.exclude_teams(['NO'])

# optimizer.player_pool.remove_player('Zach LaVine')
# optimizer.player_pool.remove_player('Zach LaVine')
# optimizer.player_pool.remove_player('Zach LaVine')
for lineup in optimizer.optimize(40, max_exposure=.75, exposure_strategy=AfterEachExposureStrategy):
    print(lineup)
optimizer.export('data/nba/fd_result.csv')

 1. PG      Davion Mitchell               PG    SAC            SAC@UTA  24.2           4000.0$
 2. PG      Mike Conley                   PG    UTA            SAC@UTA  30.2           5500.0$
 3. SG      Donovan Mitchell              PG/SG UTA            SAC@UTA  39.9           8000.0$
 4. SG      Tyrese Haliburton             PG/SG SAC            SAC@UTA  29.5           6000.0$
 5. SF      Eric Gordon                   SF/SG HOU            HOU@LAL  27.1           4200.0$
 6. SF      Giannis Antetokounmpo         PF/SF MIL            MIL@DET  57.8           11300.0$
 7. PF      Christian Wood                C/PF  HOU            HOU@LAL  40.0           7900.0$
 8. PF      Dwight Powell                 C/PF  DAL            MIA@DAL  26.0           4800.0$
 9. C       Rudy Gobert                   C     UTA            SAC@UTA  39.9           8200.0$

Fantasy Points 314.60
Salary 59900.00

 1. PG      De'Aaron Fox                  PG    SAC            SAC@UTA  38.7           7700.0$
 2. PG      Kyle Lowry                    PG    MIA            MIA@DAL  30.9           5900.0$
 3. SG      Jalen Brunson                 PG/SG DAL            MIA@DAL  24.0           4600.0$
 4. SG      Russell Westbrook             PG/SG LAL            HOU@LAL  45.2           9200.0$
 5. SF      Jae Crowder                   PF/SF PHO            NO@PHO   22.2           4200.0$
 6. SF      Mikal Bridges                 PF/SF PHO            NO@PHO   27.3           5700.0$
 7. PF      Anthony Davis                 C/PF  LAL            HOU@LAL  46.0           10000.0$
 8. PF      Thanasis Antetokounmpo        PF/SF MIL            MIL@DET  21.7           4200.0$
 9. C       Bam Adebayo                   C/PF  MIA            MIA@DAL  39.7           8500.0$

Fantasy Points 295.70
Salary 60000.00

 1. PG      Davion Mitchell               PG    SAC            SAC@UTA  24.2           4000.0$
 2. PG      Mike Conley                   PG    UTA            SAC@UTA  30.2           5500.0$
 3. SG      Jalen Brunson                 PG/SG DAL            MIA@DAL  24.0           4600.0$
 4. SG      Russell Westbrook             PG/SG LAL            HOU@LAL  45.2           9200.0$
 5. SF      Eric Gordon                   SF/SG HOU            HOU@LAL  27.1           4200.0$
 6. SF      Giannis Antetokounmpo         PF/SF MIL            MIL@DET  57.8           11300.0$
 7. PF      Christian Wood                C/PF  HOU            HOU@LAL  40.0           7900.0$
 8. PF      Dwight Powell                 C/PF  DAL            MIA@DAL  26.0           4800.0$
 9. C       Rudy Gobert                   C     UTA            SAC@UTA  39.9           8200.0$

Fantasy Points 314.40
Salary 59700.00

 1. PG      Davion Mitchell               PG    SAC            SAC@UTA  24.2           4000.0$
 2. PG      Mike Conley                   PG    UTA            SAC@UTA  30.2           5500.0$
 3. SG      Jalen Brunson                 PG/SG DAL            MIA@DAL  24.0           4600.0$
 4. SG      Russell Westbrook             PG/SG LAL            HOU@LAL  45.2           9200.0$
 5. SF      Eric Gordon                   SF/SG HOU            HOU@LAL  27.1           4200.0$
 6. SF      Giannis Antetokounmpo         PF/SF MIL            MIL@DET  57.8           11300.0$
 7. PF      Bam Adebayo                   C/PF  MIA            MIA@DAL  39.7           8500.0$
 8. PF      Christian Wood                C/PF  HOU            HOU@LAL  40.0           7900.0$
 9. C       Dwight Powell                 C/PF  DAL            MIA@DAL  26.0           4800.0$

Fantasy Points 314.20
Salary 60000.00

 1. PG      De'Aaron Fox                  PG    SAC            SAC@UTA  38.7           7700.0$
 2. PG      Kyle Lowry                    PG    MIA            MIA@DAL  30.9           5900.0$
 3. SG      Donovan Mitchell              PG/SG UTA            SAC@UTA  39.9           8000.0$
 4. SG      Tyrese Haliburton             PG/SG SAC            SAC@UTA  29.5           6000.0$
 5. SF      Jae Crowder                   PF/SF PHO            NO@PHO   22.2           4200.0$
 6. SF      Mikal Bridges                 PF/SF PHO            NO@PHO   27.3           5700.0$
 7. PF      Anthony Davis                 C/PF  LAL            HOU@LAL  46.0           10000.0$
 8. PF      Thanasis Antetokounmpo        PF/SF MIL            MIL@DET  21.7           4200.0$
 9. C       Rudy Gobert                   C     UTA            SAC@UTA  39.9           8200.0$

Fantasy Points 296.10
Salary 59900.00

 1. PG      Kyle Lowry                    PG    MIA            MIA@DAL  30.9           5900.0$
 2. PG      Mike Conley                   PG    UTA            SAC@UTA  30.2           5500.0$
 3. SG      Donovan Mitchell              PG/SG UTA            SAC@UTA  39.9           8000.0$
 4. SG      Eric Gordon                   SF/SG HOU            HOU@LAL  27.1           4200.0$
 5. SF      Giannis Antetokounmpo         PF/SF MIL            MIL@DET  57.8           11300.0$
 6. SF      Jae Crowder                   PF/SF PHO            NO@PHO   22.2           4200.0$
 7. PF      Christian Wood                C/PF  HOU            HOU@LAL  40.0           7900.0$
 8. PF      Dwight Powell                 C/PF  DAL            MIA@DAL  26.0           4800.0$
 9. C       Rudy Gobert                   C     UTA            SAC@UTA  39.9           8200.0$

Fantasy Points 314.00
Salary 60000.00

 1. PG      Davion Mitchell               PG    SAC            SAC@UTA  24.2           4000.0$
 2. PG      Mike Conley                   PG    UTA            SAC@UTA  30.2           5500.0$
 3. SG      Donovan Mitchell              PG/SG UTA            SAC@UTA  39.9           8000.0$
 4. SG      Russell Westbrook             PG/SG LAL            HOU@LAL  45.2           9200.0$
 5. SF      Eric Gordon                   SF/SG HOU            HOU@LAL  27.1           4200.0$
 6. SF      Giannis Antetokounmpo         PF/SF MIL            MIL@DET  57.8           11300.0$
 7. PF      Jae Crowder                   PF/SF PHO            NO@PHO   22.2           4200.0$
 8. PF      Mikal Bridges                 PF/SF PHO            NO@PHO   27.3           5700.0$
 9. C       Christian Wood                C/PF  HOU            HOU@LAL  40.0           7900.0$

Fantasy Points 313.90
Salary 60000.00

 1. PG      Davion Mitchell               PG    SAC            SAC@UTA  24.2           4000.0$
 2. PG      Kyle Lowry                    PG    MIA            MIA@DAL  30.9           5900.0$
 3. SG      Donovan Mitchell              PG/SG UTA            SAC@UTA  39.9           8000.0$
 4. SG      Russell Westbrook             PG/SG LAL            HOU@LAL  45.2           9200.0$
 5. SF      Eric Gordon                   SF/SG HOU            HOU@LAL  27.1           4200.0$
 6. SF      Giannis Antetokounmpo         PF/SF MIL            MIL@DET  57.8           11300.0$
 7. PF      Bobby Portis                  C/PF  MIL            MIL@DET  22.7           4700.0$
 8. PF      Christian Wood                C/PF  HOU            HOU@LAL  40.0           7900.0$
 9. C       Dwight Powell                 C/PF  DAL            MIA@DAL  26.0           4800.0$

Fantasy Points 313.80
Salary 60000.00

 1. PG      Kyle Lowry                    PG    MIA            MIA@DAL  30.9           5900.0$
 2. PG      Mike Conley                   PG    UTA            SAC@UTA  30.2           5500.0$
 3. SG      Donovan Mitchell              PG/SG UTA            SAC@UTA  39.9           8000.0$
 4. SG      Russell Westbrook             PG/SG LAL            HOU@LAL  45.2           9200.0$
 5. SF      Jae Crowder                   PF/SF PHO            NO@PHO   22.2           4200.0$
 6. SF      Thanasis Antetokounmpo        PF/SF MIL            MIL@DET  21.7           4200.0$
 7. PF      Anthony Davis                 C/PF  LAL            HOU@LAL  46.0           10000.0$
 8. PF      Dwight Powell                 C/PF  DAL            MIA@DAL  26.0           4800.0$
 9. C       Rudy Gobert                   C     UTA            SAC@UTA  39.9           8200.0$

Fantasy Points 302.00
Salary 60000.00

 1. PG      Kyle Lowry                    PG    MIA            MIA@DAL  30.9           5900.0$
 2. PG      Mike Conley                   PG    UTA            SAC@UTA  30.2           5500.0$
 3. SG      Donovan Mitchell              PG/SG UTA            SAC@UTA  39.9           8000.0$
 4. SG      Eric Gordon                   SF/SG HOU            HOU@LAL  27.1           4200.0$
 5. SF      Giannis Antetokounmpo         PF/SF MIL            MIL@DET  57.8           11300.0$
 6. SF      Thanasis Antetokounmpo        PF/SF MIL            MIL@DET  21.7           4200.0$
 7. PF      Christian Wood                C/PF  HOU            HOU@LAL  40.0           7900.0$
 8. PF      Dwight Powell                 C/PF  DAL            MIA@DAL  26.0           4800.0$
 9. C       Rudy Gobert                   C     UTA            SAC@UTA  39.9           8200.0$

Fantasy Points 313.50
Salary 60000.00

 1. PG      Davion Mitchell               PG    SAC            SAC@UTA  24.2           4000.0$
 2. PG      Mike Conley                   PG    UTA            SAC@UTA  30.2           5500.0$
 3. SG      Donovan Mitchell              PG/SG UTA            SAC@UTA  39.9           8000.0$
 4. SG      Eric Gordon                   SF/SG HOU            HOU@LAL  27.1           4200.0$
 5. SF      Giannis Antetokounmpo         PF/SF MIL            MIL@DET  57.8           11300.0$
 6. SF      Jae Crowder                   PF/SF PHO            NO@PHO   22.2           4200.0$
 7. PF      Anthony Davis                 C/PF  LAL            HOU@LAL  46.0           10000.0$
 8. PF      Christian Wood                C/PF  HOU            HOU@LAL  40.0           7900.0$
 9. C       Dwight Powell                 C/PF  DAL            MIA@DAL  26.0           4800.0$

Fantasy Points 313.40
Salary 59900.00

 1. PG      Davion Mitchell               PG    SAC            SAC@UTA  24.2           4000.0$
 2. PG      Mike Conley                   PG    UTA            SAC@UTA  30.2           5500.0$
 3. SG      Donovan Mitchell              PG/SG UTA            SAC@UTA  39.9           8000.0$
 4. SG      Russell Westbrook             PG/SG LAL            HOU@LAL  45.2           9200.0$
 5. SF      Eric Gordon                   SF/SG HOU            HOU@LAL  27.1           4200.0$
 6. SF      Giannis Antetokounmpo         PF/SF MIL            MIL@DET  57.8           11300.0$
 7. PF      Mikal Bridges                 PF/SF PHO            NO@PHO   27.3           5700.0$
 8. PF      Thanasis Antetokounmpo        PF/SF MIL            MIL@DET  21.7           4200.0$
 9. C       Christian Wood                C/PF  HOU            HOU@LAL  40.0           7900.0$

Fantasy Points 313.40
Salary 60000.00

 1. PG      De'Aaron Fox                  PG    SAC            SAC@UTA  38.7           7700.0$
 2. PG      Kyle Lowry                    PG    MIA            MIA@DAL  30.9           5900.0$
 3. SG      Russell Westbrook             PG/SG LAL            HOU@LAL  45.2           9200.0$
 4. SG      Tyrese Haliburton             PG/SG SAC            SAC@UTA  29.5           6000.0$
 5. SF      Jae Crowder                   PF/SF PHO            NO@PHO   22.2           4200.0$
 6. SF      Kent Bazemore                 SF/SG LAL            HOU@LAL  20.6           4000.0$
 7. PF      Anthony Davis                 C/PF  LAL            HOU@LAL  46.0           10000.0$
 8. PF      Dwight Powell                 C/PF  DAL            MIA@DAL  26.0           4800.0$
 9. C       Rudy Gobert                   C     UTA            SAC@UTA  39.9           8200.0$

Fantasy Points 299.00
Salary 60000.00

 1. PG      Davion Mitchell               PG    SAC            SAC@UTA  24.2           4000.0$
 2. PG      Kyle Lowry                    PG    MIA            MIA@DAL  30.9           5900.0$
 3. SG      Eric Gordon                   SF/SG HOU            HOU@LAL  27.1           4200.0$
 4. SG      Russell Westbrook             PG/SG LAL            HOU@LAL  45.2           9200.0$
 5. SF      Giannis Antetokounmpo         PF/SF MIL            MIL@DET  57.8           11300.0$
 6. SF      Jae Crowder                   PF/SF PHO            NO@PHO   22.2           4200.0$
 7. PF      Christian Wood                C/PF  HOU            HOU@LAL  40.0           7900.0$
 8. PF      Dwight Powell                 C/PF  DAL            MIA@DAL  26.0           4800.0$
 9. C       Rudy Gobert                   C     UTA            SAC@UTA  39.9           8200.0$

Fantasy Points 313.30
Salary 59700.00

 1. PG      Davion Mitchell               PG    SAC            SAC@UTA  24.2           4000.0$
 2. PG      Kyle Lowry                    PG    MIA            MIA@DAL  30.9           5900.0$
 3. SG      Donovan Mitchell              PG/SG UTA            SAC@UTA  39.9           8000.0$
 4. SG      Russell Westbrook             PG/SG LAL            HOU@LAL  45.2           9200.0$
 5. SF      Eric Gordon                   SF/SG HOU            HOU@LAL  27.1           4200.0$
 6. SF      Giannis Antetokounmpo         PF/SF MIL            MIL@DET  57.8           11300.0$
 7. PF      Christian Wood                C/PF  HOU            HOU@LAL  40.0           7900.0$
 8. PF      Jae Crowder                   PF/SF PHO            NO@PHO   22.2           4200.0$
 9. C       Dwight Powell                 C/PF  DAL            MIA@DAL  26.0           4800.0$

Fantasy Points 313.30
Salary 59500.00

 1. PG      Davion Mitchell               PG    SAC            SAC@UTA  24.2           4000.0$
 2. PG      Kyle Lowry                    PG    MIA            MIA@DAL  30.9           5900.0$
 3. SG      Donovan Mitchell              PG/SG UTA            SAC@UTA  39.9           8000.0$
 4. SG      Russell Westbrook             PG/SG LAL            HOU@LAL  45.2           9200.0$
 5. SF      Eric Gordon                   SF/SG HOU            HOU@LAL  27.1           4200.0$
 6. SF      Giannis Antetokounmpo         PF/SF MIL            MIL@DET  57.8           11300.0$
 7. PF      Dwight Powell                 C/PF  DAL            MIA@DAL  26.0           4800.0$
 8. PF      Jae Crowder                   PF/SF PHO            NO@PHO   22.2           4200.0$
 9. C       Rudy Gobert                   C     UTA            SAC@UTA  39.9           8200.0$

Fantasy Points 313.20
Salary 59800.00

 1. PG      Davion Mitchell               PG    SAC            SAC@UTA  24.2           4000.0$
 2. PG      Mike Conley                   PG    UTA            SAC@UTA  30.2           5500.0$
 3. SG      Donovan Mitchell              PG/SG UTA            SAC@UTA  39.9           8000.0$
 4. SG      Russell Westbrook             PG/SG LAL            HOU@LAL  45.2           9200.0$
 5. SF      Jae Crowder                   PF/SF PHO            NO@PHO   22.2           4200.0$
 6. SF      Thanasis Antetokounmpo        PF/SF MIL            MIL@DET  21.7           4200.0$
 7. PF      Bam Adebayo                   C/PF  MIA            MIA@DAL  39.7           8500.0$
 8. PF      Christian Wood                C/PF  HOU            HOU@LAL  40.0           7900.0$
 9. C       Rudy Gobert                   C     UTA            SAC@UTA  39.9           8200.0$

Fantasy Points 303.00
Salary 59700.00

 1. PG      Davion Mitchell               PG    SAC            SAC@UTA  24.2           4000.0$
 2. PG      Mike Conley                   PG    UTA            SAC@UTA  30.2           5500.0$
 3. SG      Donovan Mitchell              PG/SG UTA            SAC@UTA  39.9           8000.0$
 4. SG      Russell Westbrook             PG/SG LAL            HOU@LAL  45.2           9200.0$
 5. SF      Eric Gordon                   SF/SG HOU            HOU@LAL  27.1           4200.0$
 6. SF      Giannis Antetokounmpo         PF/SF MIL            MIL@DET  57.8           11300.0$
 7. PF      Alperen Sengun                C/PF  HOU            HOU@LAL  22.8           5100.0$
 8. PF      Christian Wood                C/PF  HOU            HOU@LAL  40.0           7900.0$
 9. C       Dwight Powell                 C/PF  DAL            MIA@DAL  26.0           4800.0$

Fantasy Points 313.20
Salary 60000.00

 1. PG      Davion Mitchell               PG    SAC            SAC@UTA  24.2           4000.0$
 2. PG      Mike Conley                   PG    UTA            SAC@UTA  30.2           5500.0$
 3. SG      Donovan Mitchell              PG/SG UTA            SAC@UTA  39.9           8000.0$
 4. SG      Russell Westbrook             PG/SG LAL            HOU@LAL  45.2           9200.0$
 5. SF      Eric Gordon                   SF/SG HOU            HOU@LAL  27.1           4200.0$
 6. SF      Giannis Antetokounmpo         PF/SF MIL            MIL@DET  57.8           11300.0$
 7. PF      Bobby Portis                  C/PF  MIL            MIL@DET  22.7           4700.0$
 8. PF      Christian Wood                C/PF  HOU            HOU@LAL  40.0           7900.0$
 9. C       Dwight Powell                 C/PF  DAL            MIA@DAL  26.0           4800.0$

Fantasy Points 313.10
Salary 59600.00

 1. PG      Davion Mitchell               PG    SAC            SAC@UTA  24.2           4000.0$
 2. PG      Kyle Lowry                    PG    MIA            MIA@DAL  30.9           5900.0$
 3. SG      Eric Gordon                   SF/SG HOU            HOU@LAL  27.1           4200.0$
 4. SG      Russell Westbrook             PG/SG LAL            HOU@LAL  45.2           9200.0$
 5. SF      Giannis Antetokounmpo         PF/SF MIL            MIL@DET  57.8           11300.0$
 6. SF      Jae Crowder                   PF/SF PHO            NO@PHO   22.2           4200.0$
 7. PF      Bam Adebayo                   C/PF  MIA            MIA@DAL  39.7           8500.0$
 8. PF      Christian Wood                C/PF  HOU            HOU@LAL  40.0           7900.0$
 9. C       Dwight Powell                 C/PF  DAL            MIA@DAL  26.0           4800.0$

Fantasy Points 313.10
Salary 60000.00

 1. PG      Davion Mitchell               PG    SAC            SAC@UTA  24.2           4000.0$
 2. PG      Mike Conley                   PG    UTA            SAC@UTA  30.2           5500.0$
 3. SG      Donovan Mitchell              PG/SG UTA            SAC@UTA  39.9           8000.0$
 4. SG      Luka Doncic                   PG/SG DAL            MIA@DAL  48.7           10400.0$
 5. SF      Jae Crowder                   PF/SF PHO            NO@PHO   22.2           4200.0$
 6. SF      Kent Bazemore                 SF/SG LAL            HOU@LAL  20.6           4000.0$
 7. PF      Anthony Davis                 C/PF  LAL            HOU@LAL  46.0           10000.0$
 8. PF      Mikal Bridges                 PF/SF PHO            NO@PHO   27.3           5700.0$
 9. C       Rudy Gobert                   C     UTA            SAC@UTA  39.9           8200.0$

Fantasy Points 299.00
Salary 60000.00

 1. PG      Davion Mitchell               PG    SAC            SAC@UTA  24.2           4000.0$
 2. PG      Kyle Lowry                    PG    MIA            MIA@DAL  30.9           5900.0$
 3. SG      Donovan Mitchell              PG/SG UTA            SAC@UTA  39.9           8000.0$
 4. SG      Eric Gordon                   SF/SG HOU            HOU@LAL  27.1           4200.0$
 5. SF      Giannis Antetokounmpo         PF/SF MIL            MIL@DET  57.8           11300.0$
 6. SF      Mikal Bridges                 PF/SF PHO            NO@PHO   27.3           5700.0$
 7. PF      Christian Wood                C/PF  HOU            HOU@LAL  40.0           7900.0$
 8. PF      Dwight Powell                 C/PF  DAL            MIA@DAL  26.0           4800.0$
 9. C       Rudy Gobert                   C     UTA            SAC@UTA  39.9           8200.0$

Fantasy Points 313.10
Salary 60000.00

 1. PG      Davion Mitchell               PG    SAC            SAC@UTA  24.2           4000.0$
 2. PG      Mike Conley                   PG    UTA            SAC@UTA  30.2           5500.0$
 3. SG      Donovan Mitchell              PG/SG UTA            SAC@UTA  39.9           8000.0$