In [1]:
import requests
from bs4 import BeautifulSoup as soup
import pandas as pd
from functions.nba_clean_data import archive_files
from functions.nba_proj_ceil import nba_proj_ceil

ImportError: cannot import name 'nba_proj_ceil' from 'functions.nba_proj_scape' (/home/michael/code/fan_fact/lineupopt/functions/nba_proj_scape.py)

archive_files()

# %load functions/get_nba_spread

def get_spread_page():
    url = "https://rotogrinders.com/lineups/nba?site=fanduel"
    html = requests.get(url).text
    page = soup(html)
    return page
page = get_spread_page()

team_list = page.find_all("span", {"class": "shrt"})
teams = [i.text for i in team_list]
odds_list = page.find_all("a", {"href": "/nba/odds"})
odds = [i.text for i in odds_list]
teams.sort()
print(teams)

In [2]:
df_fd = pd.read_csv('data/nba/FanDuel-NBA-2021 ET-11 ET-12 ET-66867-players-list.csv')
# teams2 = list(df_fd.Team.unique())
# teams2.sort()
# print(teams2)

In [3]:
# replace_dict = {"GSW":"GS", "NYK":"NY", "NOP":"NO", "SAS":"SA"}
# clean_teams = [replace_dict.get(item,item) for item in teams]
# print(clean_teams)

df_fd.query("Nickname == 'Mo Bamba'")

df_odds = dict(zip(clean_teams, odds))
#print(df_odds)
print(dict(sorted(df_odds.items(), key=lambda item: item[1])))

In [8]:
stats_df = nba_proj_scape()
stats_df

              Nickname    FP Value    Min
0         Nikola Jokic  52.9  4.64  34.22
1          Luka Doncic  50.6  4.96  34.99
2        Anthony Davis  50.5  4.67  34.97
3         Jayson Tatum  47.8  4.98  37.87
4    Russell Westbrook  47.4  4.79  34.92
..                 ...   ...   ...    ...
325     Brandon Ingram   0.0     0   0.00
326    Nicolas Claxton   0.0     0   0.00
327       Didi Louzada   0.0     0   0.02
328     Cameron Thomas   0.0     0   0.00
329       Usman Garuba   0.0     0   0.05

[330 rows x 4 columns]

stats_df.replace("Mohamed Bamba", "Mo Bamba", regex=True, inplace=True)
stats_df.query("Nickname == 'Mo Bamba'")

In [9]:
df_fd = pd.merge(df_fd, stats_df, how='left', on='Nickname')
df_fd

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position,FP,Value,Min
0,66867-40199,PF/SF,Giannis,Giannis Antetokounmpo,Antetokounmpo,55.283335,12.0,11600,MIL@BOS,MIL,BOS,GTD,Ankle,NaN,NaN,NaN,SF/PF,0.0,0,0.00
1,66867-55062,C,Nikola,Nikola Jokic,Jokic,54.470001,10.0,11400,ATL@DEN,DEN,ATL,NaN,NaN,NaN,NaN,NaN,C,52.9,4.64,34.22
2,66867-15755,PF/C,Anthony,Anthony Davis,Davis,49.000000,12.0,10800,MIN@LAL,LAL,MIN,GTD,Thumb,NaN,NaN,NaN,PF/C,50.5,4.67,34.97
3,66867-9646,SF/PF,Kevin,Kevin Durant,Durant,47.450002,12.0,10300,BKN@NO,BKN,NO,NaN,NaN,NaN,NaN,NaN,SF/PF,46.6,4.52,34.11
4,66867-84669,PG/SG,Luka,Luka Doncic,Doncic,45.645455,11.0,10200,DAL@SA,DAL,SA,NaN,NaN,NaN,NaN,NaN,PG/SG,50.6,4.96,34.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364,66867-159702,SF,Eugene,Eugene Omoruyi,Omoruyi,7.250000,2.0,3500,DAL@SA,DAL,SA,NaN,NaN,NaN,NaN,NaN,SF,0.4,0.12,0.64
365,66867-48598,SF,Semi,Semi Ojeleye,Ojeleye,10.028571,7.0,3500,MIL@BOS,MIL,BOS,NaN,NaN,NaN,NaN,NaN,SF,16.8,4.79,26.43
366,66867-49115,SG,Wayne,Wayne Selden,Selden,0.000000,1.0,3500,NY@CHA,NY,CHA,NaN,NaN,NaN,NaN,NaN,SG,NaN,NaN,NaN
367,66867-24546,SG/SF,Denzel,Denzel Valentine,Valentine,1.533333,6.0,3500,DET@CLE,CLE,DET,NaN,NaN,NaN,NaN,NaN,SG/SF,0.1,0.03,0.19
368,66867-15843,PG/SG,Trey,Trey Burke,Burke,6.600000,4.0,3500,DAL@SA,DAL,SA,NaN,NaN,NaN,NaN,NaN,PG/SG,0.0,0,0.00

In [10]:
pd.set_option('display.max_rows', df_fd.shape[0]+1)
cols = ['FP', 'Value', 'Min']
df_fd[cols] = df_fd[cols].astype(float).fillna(0.0)
df_fd = df_fd[df_fd.FP > 15.0]
df_fd

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position,FP,Value,Min
1,66867-55062,C,Nikola,Nikola Jokic,Jokic,54.470001,10.0,11400,ATL@DEN,DEN,ATL,NaN,NaN,NaN,NaN,NaN,C,52.9,4.64,34.22
2,66867-15755,PF/C,Anthony,Anthony Davis,Davis,49.000000,12.0,10800,MIN@LAL,LAL,MIN,GTD,Thumb,NaN,NaN,NaN,PF/C,50.5,4.67,34.97
3,66867-9646,SF/PF,Kevin,Kevin Durant,Durant,47.450002,12.0,10300,BKN@NO,BKN,NO,NaN,NaN,NaN,NaN,NaN,SF/PF,46.6,4.52,34.11
4,66867-84669,PG/SG,Luka,Luka Doncic,Doncic,45.645455,11.0,10200,DAL@SA,DAL,SA,NaN,NaN,NaN,NaN,NaN,PG/SG,50.6,4.96,34.99
5,66867-9524,PG,Stephen,Stephen Curry,Curry,48.654547,11.0,10100,CHI@GS,GS,CHI,NaN,NaN,NaN,NaN,NaN,PG,46.5,4.60,34.22
7,66867-9642,PG/SG,Russell,Russell Westbrook,Westbrook,43.524999,12.0,9900,MIN@LAL,LAL,MIN,NaN,NaN,NaN,NaN,NaN,PG/SG,47.4,4.79,34.92
8,66867-58462,C,Karl-Anthony,Karl-Anthony Towns,Towns,44.289999,10.0,9700,MIN@LAL,MIN,LAL,NaN,NaN,NaN,NaN,NaN,C,45.8,4.72,36.10
9,66867-80808,SF/PF,Jayson,Jayson Tatum,Tatum,42.272727,11.0,9600,MIL@BOS,BOS,MIL,NaN,NaN,NaN,NaN,NaN,SF/PF,47.8,4.98,37.87
10,66867-9644,SG/PG,James,James Harden,Harden,41.975001,12.0,9600,BKN@NO,BKN,NO,NaN,NaN,NaN,NaN,NaN,PG/SG,45.7,4.76,35.42
11,66867-67708,PG/SG,Dejounte,Dejounte Murray,Murray,45.945454,11.0,9500,DAL@SA,SA,DAL,NaN,NaN,NaN,NaN,NaN,PG/SG,40.3,4.24,33.42
12,66867-42669,PF/C,Julius,Julius Randle,Randle,44.266668,12.0,9400,NY@CHA,NY,CHA,NaN,NaN,NaN,NaN,NaN,PF/C,44.4,4.73,36.00
13,66867-110344,PG,Ja,Ja Morant,Morant,46.327273,11.0,9300,PHO@MEM,MEM,PHO,NaN,NaN,NaN,NaN,NaN,PG,41.8,4.49,34.89
14,66867-84671,PG,Trae,Trae Young,Young,41.108332,12.0,9200,ATL@DEN,ATL,DEN,NaN,NaN,NaN,NaN,NaN,PG,43.9,4.77,34.05
16,66867-145485,PG,LaMelo,LaMelo Ball,Ball,42.369230,13.0,8800,NY@CHA,CHA,NY,NaN,NaN,NaN,NaN,NaN,PG,41.5,4.72,34.23
17,66867-9714,SG/SF,DeMar,DeMar DeRozan,DeRozan,40.981817,11.0,8700,CHI@GS,CHI,GS,NaN,NaN,NaN,NaN,NaN,SG/SF,43.4,4.98,34.98
18,66867-14503,C,Jonas,Jonas Valanciunas,Valanciunas,43.633331,12.0,8600,BKN@NO,NO,BKN,NaN,NaN,NaN,NaN,NaN,C,43.7,5.08,34.07
19,66867-20848,PG,Damian,Damian Lillard,Lillard,37.000000,12.0,8500,POR@HOU,POR,HOU,NaN,NaN,NaN,NaN,NaN,PG,42.7,5.03,35.59
20,66867-58460,SG,Devin,Devin Booker,Booker,39.110001,10.0,8400,PHO@MEM,PHO,MEM,NaN,NaN,NaN,NaN,NaN,SG,37.2,4.43,34.21
21,66867-40783,SG/PG,Zach,Zach LaVine,LaVine,39.000000,11.0,8400,CHI@GS,CHI,GS,NaN,NaN,NaN,NaN,NaN,PG/SG,41.0,4.88,34.60
23,66867-9623,PG,Chris,Chris Paul,Paul,41.329999,10.0,8300,PHO@MEM,PHO,MEM,NaN,NaN,NaN,NaN,NaN,PG,39.3,4.73,32.83
26,66867-42202,PF/C,Christian,Christian Wood,Wood,38.263636,11.0,8200,POR@HOU,HOU,POR,NaN,NaN,NaN,NaN,NaN,PF/C,39.3,4.79,34.73
27,66867-145321,SF/SG,Anthony,Anthony Edwards,Edwards,41.710001,10.0,8100,MIN@LAL,MIN,LAL,NaN,NaN,NaN,NaN,NaN,SG/SF,39.6,4.89,35.99
28,66867-84678,SF,Miles,Miles Bridges,Bridges,41.699998,13.0,8000,NY@CHA,CHA,NY,NaN,NaN,NaN,NaN,NaN,SF,34.5,4.32,34.38
29,66867-84680,SG/PG,Shai,Shai Gilgeous-Alexander,Gilgeous-Alexander,37.629999,10.0,7900,SAC@OKC,OKC,SAC,NaN,NaN,NaN,NaN,NaN,PG/SG,39.1,4.95,34.99
30,66867-80810,PG,De'Aaron,De'Aaron Fox,Fox,37.016668,12.0,7900,SAC@OKC,SAC,OKC,NaN,NaN,NaN,NaN,NaN,PG,39.7,5.02,35.86
33,66867-80821,C/PF,Jarrett,Jarrett Allen,Allen,36.216667,12.0,7700,DET@CLE,CLE,DET,NaN,NaN,NaN,NaN,NaN,PF/C,38.6,5.02,35.53
36,66867-15946,SF/PF,Harrison,Harrison Barnes,Barnes,37.341667,12.0,7400,SAC@OKC,SAC,OKC,NaN,NaN,NaN,NaN,NaN,SF/PF,33.4,4.51,36.73
37,66867-9453,PF/C,Al,Al Horford,Horford,37.466668,9.0,7300,MIL@BOS,BOS,MIL,NaN,NaN,NaN,NaN,NaN,PF/C,31.5,4.31,29.22
38,66867-23831,PF,Jerami,Jerami Grant,Grant,33.944444,9.0,7200,DET@CLE,DET,CLE,NaN,NaN,NaN,NaN,NaN,PF,34.4,4.78,33.47
39,66867-63122,PF/C,Kristaps,Kristaps Porzingis,Porzingis,31.000000,6.0,7100,DAL@SA,DAL,SA,NaN,NaN,NaN,NaN,NaN,PF/C,32.9,4.64,28.93
40,66867-58312,SG/PG,D'Angelo,D'Angelo Russell,Russell,30.537500,8.0,7100,MIN@LAL,MIN,LAL,NaN,NaN,NaN,NaN,NaN,PG/SG,33.9,4.77,31.81
42,66867-15860,PF/C,Draymond,Draymond Green,Green,31.954545,11.0,7000,CHI@GS,GS,CHI,GTD,Thigh,NaN,NaN,NaN,PF/C,35.1,5.02,32.22
43,66867-55057,C,Jusuf,Jusuf Nurkic,Nurkic,32.633334,12.0,6900,POR@HOU,POR,HOU,NaN,NaN,NaN,NaN,NaN,C,34.6,5.01,28.03
44,66867-23447,C/PF,Richaun,Richaun Holmes,Holmes,31.175001,12.0,6900,SAC@OKC,SAC,OKC,NaN,NaN,NaN,NaN,NaN,PF/C,34.5,5.00,32.33
45,66867-157845,C/PF,Evan,Evan Mobley,Mobley,33.250000,12.0,6800,DET@CLE,CLE,DET,NaN,NaN,NaN,NaN,NaN,PF/C,38.0,5.58,35.93
46,66867-145337,PG/SG,Tyrese,Tyrese Haliburton,Haliburton,31.700000,10.0,6800,SAC@OKC,SAC,OKC,GTD,Back,NaN,NaN,NaN,PG/SG,29.2,4.30,31.59
47,66867-9663,PG/SG,Jrue,Jrue Holiday,Holiday,24.850001,6.0,6800,MIL@BOS,MIL,BOS,NaN,NaN,NaN,NaN,NaN,PG/SG,39.6,5.82,33.38
48,66867-17333,SG/SF,Will,Will Barton,Barton,33.836365,11.0,6700,ATL@DEN,DEN,ATL,NaN,NaN,NaN,NaN,NaN,SG/SF,29.5,4.41,32.07
49,66867-66236,PF/C,John,John Collins,Collins,32.449999,12.0,6600,ATL@DEN,ATL,DEN,NaN,NaN,NaN,NaN,NaN,PF/C,31.4,4.76,33.35
50,66867-84683,PF/C,Jaren,Jaren Jackson,Jackson,29.654547,11.0,6500,PHO@MEM,MEM,PHO,NaN,NaN,NaN,NaN,NaN,PF/C,32.7,5.02,30.21
51,66867-55059,C,Clint,Clint Capela,Capela,29.949999,12.0,6400,ATL@DEN,ATL,DEN,NaN,NaN,NaN,NaN,NaN,C,32.9,5.14,32.12
52,66867-16293,SF/SG,Norman,Norman Powell,Powell,27.939999,10.0,6400,POR@HOU,POR,HOU,GTD,Quadriceps,NaN,NaN,NaN,SG/SF,24.3,3.79,30.37
53,66867-110322,PG/SG,Jordan,Jordan Poole,Poole,29.081818,11.0,6300,CHI@GS,GS,CHI,NaN,NaN,NaN,NaN,NaN,PG/SG,28.3,4.49,30.21
54,66867-110342,PG/SG,Darius,Darius Garland,Garland,29.139999,10.0,6300,DET@CLE,CLE,DET,NaN,NaN,NaN,NaN,NaN,PG/SG,33.8,5.36,35.95
55,66867-110347,PF/SF,Keldon,Keldon Johnson,Johnson,29.772727,11.0,6300,DAL@SA,SA,DAL,NaN,NaN,NaN,NaN,NaN,SF/PF,30.9,4.90,32.35
57,66867-12366,SF/SG,Gordon,Gordon Hayward,Hayward,29.923077,13.0,6100,NY@CHA,CHA,NY,NaN,NaN,NaN,NaN,NaN,SG/SF,30.6,5.01,32.55
58,66867-84706,PG/SG,Devonte',Devonte' Graham,Graham,30.133334,12.0,6100,BKN@NO,NO,BKN,NaN,NaN,NaN,NaN,NaN,PG/SG,30.8,5.05,31.55
59,66867-110356,SG/SF,Nickeil,Nickeil Alexander-Walker,Alexander-Walker,29.666667,12.0,6100,BKN@NO,NO,BKN,NaN,NaN,NaN,NaN,NaN,SG/SF,31.4,5.15,31.86
60,66867-23665,SG/SF,Buddy,Buddy Hield,Hield,27.583333,12.0,6000,SAC@OKC,SAC,OKC,NaN,NaN,NaN,NaN,NaN,SG/SF,26.4,4.39,29.67
61,66867-42677,SG/PG,Terry,Terry Rozier,Rozier,25.562500,8.0,6000,NY@CHA,CHA,NY,NaN,NaN,NaN,NaN,NaN,PG/SG,30.6,5.10,32.11
62,66867-157905,SG,Josh,Josh Giddey,Giddey,30.439999,10.0,6000,SAC@OKC,OKC,SAC,NaN,NaN,NaN,NaN,NaN,SG,29.3,4.88,29.90
63,66867-110345,SF/PG,Kevin,Kevin Porter,Porter,25.863636,11.0,6000,POR@HOU,HOU,POR,GTD,Thigh,NaN,NaN,NaN,PG/SF,29.4,4.90,33.91
64,66867-40201,PG/SG,Dennis,Dennis Schroder,Schroder,29.127272,11.0,6000,MIL@BOS,BOS,MIL,NaN,NaN,NaN,NaN,NaN,PG/SG,30.7,5.12,33.21
66,66867-49675,PG/SG,Derrick,Derrick White,White,28.963637,11.0,5900,DAL@SA,SA,DAL,NaN,NaN,NaN,NaN,NaN,PG/SG,30.1,5.09,32.24
67,66867-14496,PG/SG,Ricky,Ricky Rubio,Rubio,30.100001,12.0,5900,DET@CLE,CLE,DET,NaN,NaN,NaN,NaN,NaN,PG/SG,27.3,4.63,27.35
69,66867-110357,SF/SG,RJ,RJ Barrett,Barrett,27.550001,12.0,5900,NY@CHA,NY,CHA,NaN,NaN,NaN,NaN,NaN,SG/SF,28.2,4.78,33.93
70,66867-42156,PF/C,Bobby,Bobby Portis,Portis,27.414285,7.0,5800,MIL@BOS,MIL,BOS,NaN,NaN,NaN,NaN,NaN,PF/C,35.7,6.15,30.45
71,66867-84708,PF/C,Robert,Robert Williams,Williams,30.860001,10.0,5800,MIL@BOS,BOS,MIL,NaN,NaN,NaN,NaN,NaN,PF/C,30.8,5.31,29.86
72,66867-9508,SF/PF,Carmelo,Carmelo Anthony,Anthony,27.433334,12.0,5800,MIN@LAL,LAL,MIN,NaN,NaN,NaN,NaN,NaN,SF/PF,26.3,4.53,29.00
74,66867-80806,PG,Lonzo,Lonzo Ball,Ball,31.000000,11.0,5800,CHI@GS,CHI,GS,NaN,NaN,NaN,NaN,NaN,PG,32.6,5.62,35.00
75,66867-157808,PG/SG,Cade,Cade Cunningham,Cunningham,23.480000,5.0,5700,DET@CLE,DET,CLE,NaN,NaN,NaN,NaN,NaN,PG/SG,30.2,5.30,32.08
76,66867-84690,PG/SG,Jalen,Jalen Brunson,Brunson,28.818182,11.0,5700,DAL@SA,DAL,SA,NaN,NaN,NaN,NaN,NaN,PG/SG,25.3,4.45,29.32
79,66867-110637,PF/SF,Darius,Darius Bazley,Bazley,24.960001,10.0,5600,SAC@OKC,OKC,SAC,NaN,NaN,NaN,NaN,NaN,SF/PF,24.3,4.35,29.36
80,66867-23670,SG/PG,Marcus,Marcus Smart,Smart,25.580000,10.0,5600,MIL@BOS,BOS,MIL,NaN,NaN,NaN,NaN,NaN,PG/SG,27.6,4.93,34.17
81,66867-145576,SF/PF,Jae'Sean,Jae'Sean Tate,Tate,24.909091,11.0,5600,POR@HOU,HOU,POR,NaN,NaN,NaN,NaN,NaN,SF/PF,25.8,4.60,29.26
82,66867-9666,PF/C,Thaddeus,Thaddeus Young,Young,22.475000,8.0,5600,DAL@SA,SA,DAL,NaN,NaN,NaN,NaN,NaN,PF/C,30.8,5.50,26.29
83,66867-84711,SG,Grayson,Grayson Allen,Allen,25.658333,12.0,5500,MIL@BOS,MIL,BOS,NaN,NaN,NaN,NaN,NaN,SG,28.0,5.09,32.35
84,66867-145328,SF,Saddiq,Saddiq Bey,Bey,29.300000,10.0,5500,DET@CLE,DET,CLE,NaN,NaN,NaN,NaN,NaN,SF,28.2,5.13,34.29
85,66867-49116,SG/SF,Andrew,Andrew Wiggins,Wiggins,26.581818,11.0,5500,CHI@GS,GS,CHI,NaN,NaN,NaN,NaN,NaN,SG/SF,30.7,5.58,32.22
86,66867-9475,PG/SG,Derrick,Derrick Rose,Rose,25.016668,12.0,5400,NY@CHA,NY,CHA,NaN,NaN,NaN,NaN,NaN,PG/SG,24.0,4.44,22.94
88,66867-145324,SG,Devin,Devin Vassell,Vassell,24.154547,11.0,5300,DAL@SA,SA,DAL,NaN,NaN,NaN,NaN,NaN,SG,20.6,3.89,26.02
89,66867-9688,C/PF,LaMarcus,LaMarcus Aldridge,Aldridge,24.500000,11.0,5300,BKN@NO,BKN,NO,NaN,NaN,NaN,NaN,NaN,PF/C,23.5,4.44,24.39
91,66867-16448,PF/C,Frank,Frank Kaminsky,Kaminsky,24.866666,6.0,5200,PHO@MEM,PHO,MEM,NaN,NaN,NaN,NaN,NaN,PF/C,28.3,5.43,27.02
92,66867-40562,SG/SF,Josh,Josh Hart,Hart,22.437500,8.0,5200,BKN@NO,NO,BKN,NaN,NaN,NaN,NaN,NaN,SG/SF,24.0,4.62,27.43
93,66867-84709,C,Mitchell,Mitchell Robinson,Robinson,23.727273,11.0,5200,NY@CHA,NY,CHA,NaN,NaN,NaN,NaN,NaN,C,23.6,4.54,26.96
94,66867-97263,C/PF,Drew,Drew Eubanks,Eubanks,17.990909,11.0,5200,DAL@SA,SA,DAL,NaN,NaN,NaN,NaN,NaN,PF/C,25.5,4.90,23.22
95,66867-20491,PF/SF,Robert,Robert Covington,Covington,19.066667,12.0,5100,POR@HOU,POR,HOU,NaN,NaN,NaN,NaN,NaN,SF/PF,23.6,4.64,29.90
96,66867-23169,C,Steven,Steven Adams,Adams,25.154547,11.0,5100,PHO@MEM,MEM,PHO,GTD,Ankle,NaN,NaN,NaN,C,22.2,4.35,24.87
97,66867-84670,SF/PF,Mikal,Mikal Bridges,Bridges,25.310001,10.0,5100,PHO@MEM,PHO,MEM,NaN,NaN,NaN,NaN,NaN,SF/PF,27.9,5.47,34.01
98,66867-157907,SG/PG,Jalen,Jalen Green,Green,23.200000,11.0,5100,POR@HOU,HOU,POR,NaN,NaN,NaN,NaN,NaN,PG/SG,25.4,4.99,34.69
99,66867-58153,SF/SG,Kelly,Kelly Oubre,Oubre,23.607692,13.0,5100,NY@CHA,CHA,NY,NaN,NaN,NaN,NaN,NaN,SG/SF,24.1,4.72,26.21
100,66867-23096,SF/SG,Evan,Evan Fournier,Fournier,23.433334,12.0,5000,NY@CHA,NY,CHA,NaN,NaN,NaN,NaN,NaN,SG/SF,23.7,4.74,30.05
101,66867-15993,SG/SF,Pat,Pat Connaughton,Connaughton,22.000000,12.0,5000,MIL@BOS,MIL,BOS,NaN,NaN,NaN,NaN,NaN,SG/SF,23.1,4.61,28.46
102,66867-41594,PF,Aaron,Aaron Gordon,Gordon,23.963637,11.0,5000,ATL@DEN,DEN,ATL,NaN,NaN,NaN,NaN,NaN,PF,26.5,5.31,30.03
103,66867-157908,C/PF,Alperen,Alperen Sengun,Sengun,21.980000,10.0,5000,POR@HOU,HOU,POR,NaN,NaN,NaN,NaN,NaN,PF/C,20.9,4.19,19.26
104,66867-84703,SG/PG,De'Anthony,De'Anthony Melton,Melton,27.945454,11.0,5000,PHO@MEM,MEM,PHO,NaN,NaN,NaN,NaN,NaN,PG/SG,27.3,5.46,29.59
105,66867-15590,C,Mason,Mason Plumlee,Plumlee,24.930770,13.0,5000,NY@CHA,CHA,NY,NaN,NaN,NaN,NaN,NaN,C,25.9,5.17,26.01
106,66867-23716,SF/PF,Kyle,Kyle Anderson,Anderson,23.000000,11.0,4900,PHO@MEM,MEM,PHO,NaN,NaN,NaN,NaN,NaN,SF/PF,26.1,5.33,24.93
107,66867-111273,SF/SG,Luguentz,Luguentz Dort,Dort,23.155555,9.0,4900,SAC@OKC,OKC,SAC,NaN,NaN,NaN,NaN,NaN,SG/SF,23.9,4.87,31.95
109,66867-84702,SG/SF,Lonnie,Lonnie Walker,Walker,21.263636,11.0,4900,DAL@SA,SA,DAL,NaN,NaN,NaN,NaN,NaN,SG/SF,19.6,3.99,26.08
110,66867-12474,PG,Patrick,Patrick Beverley,Beverley,24.424999,8.0,4800,MIN@LAL,MIN,LAL,NaN,NaN,NaN,NaN,NaN,PG,22.5,4.68,29.11
111,66867-55060,SF/SG,Bogdan,Bogdan Bogdanovic,Bogdanovic,21.981818,11.0,4800,ATL@DEN,ATL,DEN,GTD,Ankle,NaN,NaN,NaN,SG/SF,26.8,5.59,30.22
112,66867-16233,SF/SG,Josh,Josh Richardson,Richardson,16.344445,9.0,4800,MIL@BOS,BOS,MIL,NaN,NaN,NaN,NaN,NaN,SG/SF,16.8,3.50,22.17
113,66867-145307,PF,Isaiah,Isaiah Stewart,Stewart,21.970000,10.0,4800,DET@CLE,DET,CLE,NaN,NaN,NaN,NaN,NaN,PF,28.6,5.96,31.14
114,66867-15800,PF/SF,Jae,Jae Crowder,Crowder,22.780000,10.0,4800,PHO@MEM,PHO,MEM,NaN,NaN,NaN,NaN,NaN,SF/PF,22.6,4.70,30.23
115,66867-157812,PG,Davion,Davion Mitchell,Mitchell,20.449999,12.0,4700,SAC@OKC,SAC,OKC,NaN,NaN,NaN,NaN,NaN,PG,21.8,4.63,26.69
119,66867-18256,PF/SF,Doug,Doug McDermott,McDermott,14.275000,8.0,4700,DAL@SA,SA,DAL,NaN,NaN,NaN,NaN,NaN,SF/PF,18.5,3.93,26.21
120,66867-145334,SG,Desmond,Desmond Bane,Bane,23.763636,11.0,4700,PHO@MEM,MEM,PHO,NaN,NaN,NaN,NaN,NaN,SG,24.1,5.12,29.63
121,66867-14507,PG,Kemba,Kemba Walker,Walker,22.181818,11.0,4600,NY@CHA,NY,CHA,NaN,NaN,NaN,NaN,NaN,PG,23.2,5.04,28.09
122,66867-84718,PF,Alize,Alize Johnson,Johnson,6.885714,7.0,4600,CHI@GS,CHI,GS,NaN,NaN,NaN,NaN,NaN,PF,18.9,4.11,17.99
123,66867-110338,SF,De'Andre,De'Andre Hunter,Hunter,17.710001,10.0,4600,ATL@DEN,ATL,DEN,GTD,Wrist,NaN,NaN,NaN,SF,24.2,5.25,31.51
124,66867-110351,SG,Cody,Cody Martin,Martin,21.038462,13.0,4600,NY@CHA,CHA,NY,NaN,NaN,NaN,NaN,NaN,SG,20.6,4.48,26.03
125,66867-23981,PG/SG,Alex,Alex Caruso,Caruso,24.145455,11.0,4600,CHI@GS,CHI,GS,NaN,NaN,NaN,NaN,NaN,PG/SG,23.4,5.08,30.99
126,66867-66064,SF/SG,Malik,Malik Beasley,Beasley,17.420000,10.0,4500,MIN@LAL,MIN,LAL,NaN,NaN,NaN,NaN,NaN,SG/SF,18.3,4.06,23.34
127,66867-63126,SF/PF,Cedi,Cedi Osman,Osman,15.036363,11.0,4500,DET@CLE,CLE,DET,NaN,NaN,NaN,NaN,NaN,SF/PF,23.8,5.30,28.52
128,66867-84721,PF,Jarred,Jarred Vanderbilt,Vanderbilt,17.050000,10.0,4500,MIN@LAL,MIN,LAL,NaN,NaN,NaN,NaN,NaN,PF,20.5,4.56,20.85
130,66867-110339,SG/SF,Cam,Cam Reddish,Reddish,19.033333,12.0,4500,ATL@DEN,ATL,DEN,NaN,NaN,NaN,NaN,NaN,SG/SF,18.4,4.09,25.03
132,66867-16376,SF/SG,Dorian,Dorian Finney-Smith,Finney-Smith,20.390909,11.0,4500,DAL@SA,DAL,SA,NaN,NaN,NaN,NaN,NaN,SG/SF,20.7,4.59,32.00
133,66867-9739,C,JaVale,JaVale McGee,McGee,19.380000,10.0,4400,PHO@MEM,PHO,MEM,NaN,NaN,NaN,NaN,NaN,C,25.0,5.68,20.91
134,66867-145489,PG,Killian,Killian Hayes,Hayes,16.066667,9.0,4400,DET@CLE,DET,CLE,NaN,NaN,NaN,NaN,NaN,PG,18.6,4.22,26.91
136,66867-16196,C/PF,Dwight,Dwight Powell,Powell,19.500000,11.0,4400,DAL@SA,DAL,SA,NaN,NaN,NaN,NaN,NaN,PF/C,19.8,4.50,23.12
137,66867-80809,SG,Josh,Josh Jackson,Jackson,18.689999,10.0,4400,DET@CLE,DET,CLE,NaN,NaN,NaN,NaN,NaN,SG,18.7,4.24,19.87
138,66867-80816,SG,Malik,Malik Monk,Monk,15.358334,12.0,4400,MIN@LAL,LAL,MIN,NaN,NaN,NaN,NaN,NaN,SG,18.7,4.25,22.95
139,66867-80823,PF/C,Tony,Tony Bradley,Bradley,10.212500,8.0,4400,CHI@GS,CHI,GS,NaN,NaN,NaN,NaN,NaN,PF/C,27.5,6.24,26.09
142,66867-84694,SG,Bruce,Bruce Brown,Brown,18.218181,11.0,4300,BKN@NO,BKN,NO,NaN,NaN,NaN,NaN,NaN,SG,20.8,4.83,26.16
143,66867-110995,C,Naz,Naz Reid,Reid,18.560001,10.0,4300,MIN@LAL,MIN,LAL,NaN,NaN,NaN,NaN,NaN,C,20.4,4.74,19.08
144,66867-40396,PG,Monte,Monte Morris,Morris,20.272727,11.0,4300,ATL@DEN,DEN,ATL,NaN,NaN,NaN,NaN,NaN,PG,21.9,5.09,29.15
145,66867-9703,PG,George,George Hill,Hill,19.050001,12.0,4300,MIL@BOS,MIL,BOS,NaN,NaN,NaN,NaN,NaN,PG,21.2,4.94,30.62
146,66867-16363,SG/SF,Joe,Joe Harris,Harris,18.058333,12.0,4300,BKN@NO,BKN,NO,NaN,NaN,NaN,NaN,NaN,SG/SF,19.6,4.57,30.72
147,66867-81529,PF/C,Daniel,Daniel Theis,Theis,18.311111,9.0,4200,POR@HOU,HOU,POR,NaN,NaN,NaN,NaN,NaN,PF/C,21.8,5.20,25.18
149,66867-84717,PG/SG,Anfernee,Anfernee Simons,Simons,19.091667,12.0,4200,POR@HOU,POR,HOU,NaN,NaN,NaN,NaN,NaN,PG/SG,18.5,4.40,24.48
152,66867-145313,PF/SF,Jordan,Jordan Nwora,Nwora,15.958333,12.0,4200,MIL@BOS,MIL,BOS,NaN,NaN,NaN,NaN,NaN,SF/PF,21.2,5.05,21.34
156,66867-111372,SF/PF,Thanasis,Thanasis Antetokounmpo,Antetokounmpo,13.263636,11.0,4100,MIL@BOS,MIL,BOS,NaN,NaN,NaN,NaN,NaN,SF/PF,15.9,3.87,18.27
157,66867-11074,SF,Garrett,Garrett Temple,Temple,17.030000,10.0,4100,BKN@NO,NO,BKN,NaN,NaN,NaN,NaN,NaN,SF,18.2,4.44,26.71
158,66867-18376,SG/PG,Damion,Damion Lee,Lee,17.744444,9.0,4100,CHI@GS,GS,CHI,GTD,Hip,NaN,NaN,NaN,PG/SG,18.4,4.49,24.05
160,66867-157848,PF,Herbert,Herbert Jones,Jones,15.588889,9.0,4000,BKN@NO,NO,BKN,NaN,NaN,NaN,NaN,NaN,PF,19.7,4.93,27.47
163,66867-9561,C,DeAndre,DeAndre Jordan,Jordan,16.058333,12.0,4000,MIN@LAL,LAL,MIN,NaN,NaN,NaN,NaN,NaN,C,15.6,3.90,15.93
164,66867-9660,C,Dwight,Dwight Howard,Howard,13.839999,10.0,4000,MIN@LAL,LAL,MIN,NaN,NaN,NaN,NaN,NaN,C,16.6,4.16,14.99
165,66867-145341,SF,Isaac,Isaac Okoro,Okoro,14.880000,5.0,4000,DET@CLE,CLE,DET,NaN,NaN,NaN,NaN,NaN,SF,17.8,4.46,29.07
166,66867-15814,C/PF,Alex,Alex Len,Len,17.512501,8.0,4000,SAC@OKC,SAC,OKC,NaN,NaN,NaN,NaN,NaN,PF/C,16.9,4.22,16.50
168,66867-12351,C/PF,Derrick,Derrick Favors,Favors,16.144445,9.0,3900,SAC@OKC,OKC,SAC,NaN,NaN,NaN,NaN,NaN,PF/C,22.9,5.87,21.77
170,66867-58081,PG,Tyus,Tyus Jones,Jones,15.672727,11.0,3900,PHO@MEM,MEM,PHO,NaN,NaN,NaN,NaN,NaN,PG,17.1,4.38,17.96
171,66867-9481,C,Taj,Taj Gibson,Gibson,15.842857,7.0,3900,NY@CHA,NY,CHA,NaN,NaN,NaN,NaN,NaN,C,18.4,4.71,19.96
172,66867-15628,SF/PF,Otto,Otto Porter,Porter,18.080000,10.0,3900,CHI@GS,GS,CHI,NaN,NaN,NaN,NaN,NaN,SF/PF,17.7,4.54,18.12
176,66867-85305,SF,Kenrich,Kenrich Williams,Williams,13.839999,10.0,3900,SAC@OKC,OKC,SAC,NaN,NaN,NaN,NaN,NaN,SF,17.4,4.46,21.38
177,66867-19781,SF/SG,Kent,Kent Bazemore,Bazemore,13.574999,12.0,3900,MIN@LAL,LAL,MIN,NaN,NaN,NaN,NaN,NaN,SG/SF,18.8,4.82,26.98
178,66867-15691,C,Cody,Cody Zeller,Zeller,14.108334,12.0,3900,POR@HOU,POR,HOU,NaN,NaN,NaN,NaN,NaN,C,15.2,3.89,15.59
179,66867-9556,SF/SG,Eric,Eric Gordon,Gordon,18.433333,9.0,3900,POR@HOU,HOU,POR,NaN,NaN,NaN,NaN,NaN,SG/SF,23.0,5.89,26.54
180,66867-9560,PF/C,Blake,Blake Griffin,Griffin,16.790909,11.0,3900,BKN@NO,BKN,NO,NaN,NaN,NaN,NaN,NaN,PF/C,17.6,4.51,21.77
183,66867-9664,SF/SG,Andre,Andre Iguodala,Iguodala,18.744444,9.0,3900,CHI@GS,GS,CHI,NaN,NaN,NaN,NaN,NaN,SG/SF,15.3,3.91,19.33
184,66867-15405,PF/C,JaMychal,JaMychal Green,Green,11.745454,11.0,3800,ATL@DEN,DEN,ATL,NaN,NaN,NaN,NaN,NaN,PF/C,15.6,4.10,17.39
186,66867-14510,SG/SF,Alec,Alec Burks,Burks,16.608334,12.0,3800,NY@CHA,NY,CHA,NaN,NaN,NaN,NaN,NaN,SG/SF,15.8,4.15,16.44
189,66867-110353,PF,Brandon,Brandon Clarke,Clarke,14.312500,8.0,3800,PHO@MEM,MEM,PHO,NaN,NaN,NaN,NaN,NaN,PF,17.2,4.53,17.82
191,66867-145319,PF,Jaden,Jaden McDaniels,McDaniels,15.100000,10.0,3800,MIN@LAL,MIN,LAL,NaN,NaN,NaN,NaN,NaN,PF,18.4,4.84,29.57
192,66867-48567,PG/SG,Cameron,Cameron Payne,Payne,16.639999,5.0,3800,PHO@MEM,PHO,MEM,NaN,NaN,NaN,NaN,NaN,PG/SG,19.3,5.08,19.95
196,66867-12334,SG,Avery,Avery Bradley,Bradley,11.336363,11.0,3700,MIN@LAL,LAL,MIN,NaN,NaN,NaN,NaN,NaN,SG,15.9,4.30,27.90
198,66867-112709,SG/SF,Javonte,Javonte Green,Green,14.981818,11.0,3700,CHI@GS,CHI,GS,NaN,NaN,NaN,NaN,NaN,SG/SF,15.8,4.27,24.10
200,66867-58461,PF,Trey,Trey Lyles,Lyles,15.550000,10.0,3700,DET@CLE,DET,CLE,NaN,NaN,NaN,NaN,NaN,PF,17.6,4.75,20.99
205,66867-110316,SF,Cameron,Cameron Johnson,Johnson,14.580000,10.0,3700,PHO@MEM,PHO,MEM,NaN,NaN,NaN,NaN,NaN,SF,17.2,4.66,23.40
213,66867-9648,PF/SF,Jeff,Jeff Green,Green,11.272727,11.0,3700,ATL@DEN,DEN,ATL,NaN,NaN,NaN,NaN,NaN,SF/PF,24.1,6.51,32.15
234,66867-9637,SF/PF,Danilo,Danilo Gallinari,Gallinari,12.044445,9.0,3600,ATL@DEN,ATL,DEN,NaN,NaN,NaN,NaN,NaN,SF/PF,16.2,4.49,19.16
348,66867-145819,SF,Naji,Naji Marshall,Marshall,10.672727,11.0,3500,BKN@NO,NO,BKN,GTD,Knee,NaN,NaN,NaN,SF,15.7,4.48,17.73
365,66867-48598,SF,Semi,Semi Ojeleye,Ojeleye,10.028571,7.0,3500,MIL@BOS,MIL,BOS,NaN,NaN,NaN,NaN,NaN,SF,16.8,4.79,26.43

In [11]:
df_fd['FPPG'] = df_fd.FP
dropped_cols = ['FP', 'Value', 'Min']#, 'expts', 'rkpts', 'vlpts', 'new_expts']
df_fd.drop(dropped_cols, axis=1, inplace=True)
df_fd

/tmp/ipykernel_55352/3747236435.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fd['FPPG'] = df_fd.FP
/home/michael/.local/share/virtualenvs/fan_fact-icAuygf9/lib/python3.8/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
1,66867-55062,C,Nikola,Nikola Jokic,Jokic,52.9,10.0,11400,ATL@DEN,DEN,ATL,NaN,NaN,NaN,NaN,NaN,C
2,66867-15755,PF/C,Anthony,Anthony Davis,Davis,50.5,12.0,10800,MIN@LAL,LAL,MIN,GTD,Thumb,NaN,NaN,NaN,PF/C
3,66867-9646,SF/PF,Kevin,Kevin Durant,Durant,46.6,12.0,10300,BKN@NO,BKN,NO,NaN,NaN,NaN,NaN,NaN,SF/PF
4,66867-84669,PG/SG,Luka,Luka Doncic,Doncic,50.6,11.0,10200,DAL@SA,DAL,SA,NaN,NaN,NaN,NaN,NaN,PG/SG
5,66867-9524,PG,Stephen,Stephen Curry,Curry,46.5,11.0,10100,CHI@GS,GS,CHI,NaN,NaN,NaN,NaN,NaN,PG
7,66867-9642,PG/SG,Russell,Russell Westbrook,Westbrook,47.4,12.0,9900,MIN@LAL,LAL,MIN,NaN,NaN,NaN,NaN,NaN,PG/SG
8,66867-58462,C,Karl-Anthony,Karl-Anthony Towns,Towns,45.8,10.0,9700,MIN@LAL,MIN,LAL,NaN,NaN,NaN,NaN,NaN,C
9,66867-80808,SF/PF,Jayson,Jayson Tatum,Tatum,47.8,11.0,9600,MIL@BOS,BOS,MIL,NaN,NaN,NaN,NaN,NaN,SF/PF
10,66867-9644,SG/PG,James,James Harden,Harden,45.7,12.0,9600,BKN@NO,BKN,NO,NaN,NaN,NaN,NaN,NaN,PG/SG
11,66867-67708,PG/SG,Dejounte,Dejounte Murray,Murray,40.3,11.0,9500,DAL@SA,SA,DAL,NaN,NaN,NaN,NaN,NaN,PG/SG
12,66867-42669,PF/C,Julius,Julius Randle,Randle,44.4,12.0,9400,NY@CHA,NY,CHA,NaN,NaN,NaN,NaN,NaN,PF/C
13,66867-110344,PG,Ja,Ja Morant,Morant,41.8,11.0,9300,PHO@MEM,MEM,PHO,NaN,NaN,NaN,NaN,NaN,PG
14,66867-84671,PG,Trae,Trae Young,Young,43.9,12.0,9200,ATL@DEN,ATL,DEN,NaN,NaN,NaN,NaN,NaN,PG
16,66867-145485,PG,LaMelo,LaMelo Ball,Ball,41.5,13.0,8800,NY@CHA,CHA,NY,NaN,NaN,NaN,NaN,NaN,PG
17,66867-9714,SG/SF,DeMar,DeMar DeRozan,DeRozan,43.4,11.0,8700,CHI@GS,CHI,GS,NaN,NaN,NaN,NaN,NaN,SG/SF
18,66867-14503,C,Jonas,Jonas Valanciunas,Valanciunas,43.7,12.0,8600,BKN@NO,NO,BKN,NaN,NaN,NaN,NaN,NaN,C
19,66867-20848,PG,Damian,Damian Lillard,Lillard,42.7,12.0,8500,POR@HOU,POR,HOU,NaN,NaN,NaN,NaN,NaN,PG
20,66867-58460,SG,Devin,Devin Booker,Booker,37.2,10.0,8400,PHO@MEM,PHO,MEM,NaN,NaN,NaN,NaN,NaN,SG
21,66867-40783,SG/PG,Zach,Zach LaVine,LaVine,41.0,11.0,8400,CHI@GS,CHI,GS,NaN,NaN,NaN,NaN,NaN,PG/SG
23,66867-9623,PG,Chris,Chris Paul,Paul,39.3,10.0,8300,PHO@MEM,PHO,MEM,NaN,NaN,NaN,NaN,NaN,PG
26,66867-42202,PF/C,Christian,Christian Wood,Wood,39.3,11.0,8200,POR@HOU,HOU,POR,NaN,NaN,NaN,NaN,NaN,PF/C
27,66867-145321,SF/SG,Anthony,Anthony Edwards,Edwards,39.6,10.0,8100,MIN@LAL,MIN,LAL,NaN,NaN,NaN,NaN,NaN,SG/SF
28,66867-84678,SF,Miles,Miles Bridges,Bridges,34.5,13.0,8000,NY@CHA,CHA,NY,NaN,NaN,NaN,NaN,NaN,SF
29,66867-84680,SG/PG,Shai,Shai Gilgeous-Alexander,Gilgeous-Alexander,39.1,10.0,7900,SAC@OKC,OKC,SAC,NaN,NaN,NaN,NaN,NaN,PG/SG
30,66867-80810,PG,De'Aaron,De'Aaron Fox,Fox,39.7,12.0,7900,SAC@OKC,SAC,OKC,NaN,NaN,NaN,NaN,NaN,PG
33,66867-80821,C/PF,Jarrett,Jarrett Allen,Allen,38.6,12.0,7700,DET@CLE,CLE,DET,NaN,NaN,NaN,NaN,NaN,PF/C
36,66867-15946,SF/PF,Harrison,Harrison Barnes,Barnes,33.4,12.0,7400,SAC@OKC,SAC,OKC,NaN,NaN,NaN,NaN,NaN,SF/PF
37,66867-9453,PF/C,Al,Al Horford,Horford,31.5,9.0,7300,MIL@BOS,BOS,MIL,NaN,NaN,NaN,NaN,NaN,PF/C
38,66867-23831,PF,Jerami,Jerami Grant,Grant,34.4,9.0,7200,DET@CLE,DET,CLE,NaN,NaN,NaN,NaN,NaN,PF
39,66867-63122,PF/C,Kristaps,Kristaps Porzingis,Porzingis,32.9,6.0,7100,DAL@SA,DAL,SA,NaN,NaN,NaN,NaN,NaN,PF/C
40,66867-58312,SG/PG,D'Angelo,D'Angelo Russell,Russell,33.9,8.0,7100,MIN@LAL,MIN,LAL,NaN,NaN,NaN,NaN,NaN,PG/SG
42,66867-15860,PF/C,Draymond,Draymond Green,Green,35.1,11.0,7000,CHI@GS,GS,CHI,GTD,Thigh,NaN,NaN,NaN,PF/C
43,66867-55057,C,Jusuf,Jusuf Nurkic,Nurkic,34.6,12.0,6900,POR@HOU,POR,HOU,NaN,NaN,NaN,NaN,NaN,C
44,66867-23447,C/PF,Richaun,Richaun Holmes,Holmes,34.5,12.0,6900,SAC@OKC,SAC,OKC,NaN,NaN,NaN,NaN,NaN,PF/C
45,66867-157845,C/PF,Evan,Evan Mobley,Mobley,38.0,12.0,6800,DET@CLE,CLE,DET,NaN,NaN,NaN,NaN,NaN,PF/C
46,66867-145337,PG/SG,Tyrese,Tyrese Haliburton,Haliburton,29.2,10.0,6800,SAC@OKC,SAC,OKC,GTD,Back,NaN,NaN,NaN,PG/SG
47,66867-9663,PG/SG,Jrue,Jrue Holiday,Holiday,39.6,6.0,6800,MIL@BOS,MIL,BOS,NaN,NaN,NaN,NaN,NaN,PG/SG
48,66867-17333,SG/SF,Will,Will Barton,Barton,29.5,11.0,6700,ATL@DEN,DEN,ATL,NaN,NaN,NaN,NaN,NaN,SG/SF
49,66867-66236,PF/C,John,John Collins,Collins,31.4,12.0,6600,ATL@DEN,ATL,DEN,NaN,NaN,NaN,NaN,NaN,PF/C
50,66867-84683,PF/C,Jaren,Jaren Jackson,Jackson,32.7,11.0,6500,PHO@MEM,MEM,PHO,NaN,NaN,NaN,NaN,NaN,PF/C
51,66867-55059,C,Clint,Clint Capela,Capela,32.9,12.0,6400,ATL@DEN,ATL,DEN,NaN,NaN,NaN,NaN,NaN,C
52,66867-16293,SF/SG,Norman,Norman Powell,Powell,24.3,10.0,6400,POR@HOU,POR,HOU,GTD,Quadriceps,NaN,NaN,NaN,SG/SF
53,66867-110322,PG/SG,Jordan,Jordan Poole,Poole,28.3,11.0,6300,CHI@GS,GS,CHI,NaN,NaN,NaN,NaN,NaN,PG/SG
54,66867-110342,PG/SG,Darius,Darius Garland,Garland,33.8,10.0,6300,DET@CLE,CLE,DET,NaN,NaN,NaN,NaN,NaN,PG/SG
55,66867-110347,PF/SF,Keldon,Keldon Johnson,Johnson,30.9,11.0,6300,DAL@SA,SA,DAL,NaN,NaN,NaN,NaN,NaN,SF/PF
57,66867-12366,SF/SG,Gordon,Gordon Hayward,Hayward,30.6,13.0,6100,NY@CHA,CHA,NY,NaN,NaN,NaN,NaN,NaN,SG/SF
58,66867-84706,PG/SG,Devonte',Devonte' Graham,Graham,30.8,12.0,6100,BKN@NO,NO,BKN,NaN,NaN,NaN,NaN,NaN,PG/SG
59,66867-110356,SG/SF,Nickeil,Nickeil Alexander-Walker,Alexander-Walker,31.4,12.0,6100,BKN@NO,NO,BKN,NaN,NaN,NaN,NaN,NaN,SG/SF
60,66867-23665,SG/SF,Buddy,Buddy Hield,Hield,26.4,12.0,6000,SAC@OKC,SAC,OKC,NaN,NaN,NaN,NaN,NaN,SG/SF
61,66867-42677,SG/PG,Terry,Terry Rozier,Rozier,30.6,8.0,6000,NY@CHA,CHA,NY,NaN,NaN,NaN,NaN,NaN,PG/SG
62,66867-157905,SG,Josh,Josh Giddey,Giddey,29.3,10.0,6000,SAC@OKC,OKC,SAC,NaN,NaN,NaN,NaN,NaN,SG
63,66867-110345,SF/PG,Kevin,Kevin Porter,Porter,29.4,11.0,6000,POR@HOU,HOU,POR,GTD,Thigh,NaN,NaN,NaN,PG/SF
64,66867-40201,PG/SG,Dennis,Dennis Schroder,Schroder,30.7,11.0,6000,MIL@BOS,BOS,MIL,NaN,NaN,NaN,NaN,NaN,PG/SG
66,66867-49675,PG/SG,Derrick,Derrick White,White,30.1,11.0,5900,DAL@SA,SA,DAL,NaN,NaN,NaN,NaN,NaN,PG/SG
67,66867-14496,PG/SG,Ricky,Ricky Rubio,Rubio,27.3,12.0,5900,DET@CLE,CLE,DET,NaN,NaN,NaN,NaN,NaN,PG/SG
69,66867-110357,SF/SG,RJ,RJ Barrett,Barrett,28.2,12.0,5900,NY@CHA,NY,CHA,NaN,NaN,NaN,NaN,NaN,SG/SF
70,66867-42156,PF/C,Bobby,Bobby Portis,Portis,35.7,7.0,5800,MIL@BOS,MIL,BOS,NaN,NaN,NaN,NaN,NaN,PF/C
71,66867-84708,PF/C,Robert,Robert Williams,Williams,30.8,10.0,5800,MIL@BOS,BOS,MIL,NaN,NaN,NaN,NaN,NaN,PF/C
72,66867-9508,SF/PF,Carmelo,Carmelo Anthony,Anthony,26.3,12.0,5800,MIN@LAL,LAL,MIN,NaN,NaN,NaN,NaN,NaN,SF/PF
74,66867-80806,PG,Lonzo,Lonzo Ball,Ball,32.6,11.0,5800,CHI@GS,CHI,GS,NaN,NaN,NaN,NaN,NaN,PG
75,66867-157808,PG/SG,Cade,Cade Cunningham,Cunningham,30.2,5.0,5700,DET@CLE,DET,CLE,NaN,NaN,NaN,NaN,NaN,PG/SG
76,66867-84690,PG/SG,Jalen,Jalen Brunson,Brunson,25.3,11.0,5700,DAL@SA,DAL,SA,NaN,NaN,NaN,NaN,NaN,PG/SG
79,66867-110637,PF/SF,Darius,Darius Bazley,Bazley,24.3,10.0,5600,SAC@OKC,OKC,SAC,NaN,NaN,NaN,NaN,NaN,SF/PF
80,66867-23670,SG/PG,Marcus,Marcus Smart,Smart,27.6,10.0,5600,MIL@BOS,BOS,MIL,NaN,NaN,NaN,NaN,NaN,PG/SG
81,66867-145576,SF/PF,Jae'Sean,Jae'Sean Tate,Tate,25.8,11.0,5600,POR@HOU,HOU,POR,NaN,NaN,NaN,NaN,NaN,SF/PF
82,66867-9666,PF/C,Thaddeus,Thaddeus Young,Young,30.8,8.0,5600,DAL@SA,SA,DAL,NaN,NaN,NaN,NaN,NaN,PF/C
83,66867-84711,SG,Grayson,Grayson Allen,Allen,28.0,12.0,5500,MIL@BOS,MIL,BOS,NaN,NaN,NaN,NaN,NaN,SG
84,66867-145328,SF,Saddiq,Saddiq Bey,Bey,28.2,10.0,5500,DET@CLE,DET,CLE,NaN,NaN,NaN,NaN,NaN,SF
85,66867-49116,SG/SF,Andrew,Andrew Wiggins,Wiggins,30.7,11.0,5500,CHI@GS,GS,CHI,NaN,NaN,NaN,NaN,NaN,SG/SF
86,66867-9475,PG/SG,Derrick,Derrick Rose,Rose,24.0,12.0,5400,NY@CHA,NY,CHA,NaN,NaN,NaN,NaN,NaN,PG/SG
88,66867-145324,SG,Devin,Devin Vassell,Vassell,20.6,11.0,5300,DAL@SA,SA,DAL,NaN,NaN,NaN,NaN,NaN,SG
89,66867-9688,C/PF,LaMarcus,LaMarcus Aldridge,Aldridge,23.5,11.0,5300,BKN@NO,BKN,NO,NaN,NaN,NaN,NaN,NaN,PF/C
91,66867-16448,PF/C,Frank,Frank Kaminsky,Kaminsky,28.3,6.0,5200,PHO@MEM,PHO,MEM,NaN,NaN,NaN,NaN,NaN,PF/C
92,66867-40562,SG/SF,Josh,Josh Hart,Hart,24.0,8.0,5200,BKN@NO,NO,BKN,NaN,NaN,NaN,NaN,NaN,SG/SF
93,66867-84709,C,Mitchell,Mitchell Robinson,Robinson,23.6,11.0,5200,NY@CHA,NY,CHA,NaN,NaN,NaN,NaN,NaN,C
94,66867-97263,C/PF,Drew,Drew Eubanks,Eubanks,25.5,11.0,5200,DAL@SA,SA,DAL,NaN,NaN,NaN,NaN,NaN,PF/C
95,66867-20491,PF/SF,Robert,Robert Covington,Covington,23.6,12.0,5100,POR@HOU,POR,HOU,NaN,NaN,NaN,NaN,NaN,SF/PF
96,66867-23169,C,Steven,Steven Adams,Adams,22.2,11.0,5100,PHO@MEM,MEM,PHO,GTD,Ankle,NaN,NaN,NaN,C
97,66867-84670,SF/PF,Mikal,Mikal Bridges,Bridges,27.9,10.0,5100,PHO@MEM,PHO,MEM,NaN,NaN,NaN,NaN,NaN,SF/PF
98,66867-157907,SG/PG,Jalen,Jalen Green,Green,25.4,11.0,5100,POR@HOU,HOU,POR,NaN,NaN,NaN,NaN,NaN,PG/SG
99,66867-58153,SF/SG,Kelly,Kelly Oubre,Oubre,24.1,13.0,5100,NY@CHA,CHA,NY,NaN,NaN,NaN,NaN,NaN,SG/SF
100,66867-23096,SF/SG,Evan,Evan Fournier,Fournier,23.7,12.0,5000,NY@CHA,NY,CHA,NaN,NaN,NaN,NaN,NaN,SG/SF
101,66867-15993,SG/SF,Pat,Pat Connaughton,Connaughton,23.1,12.0,5000,MIL@BOS,MIL,BOS,NaN,NaN,NaN,NaN,NaN,SG/SF
102,66867-41594,PF,Aaron,Aaron Gordon,Gordon,26.5,11.0,5000,ATL@DEN,DEN,ATL,NaN,NaN,NaN,NaN,NaN,PF
103,66867-157908,C/PF,Alperen,Alperen Sengun,Sengun,20.9,10.0,5000,POR@HOU,HOU,POR,NaN,NaN,NaN,NaN,NaN,PF/C
104,66867-84703,SG/PG,De'Anthony,De'Anthony Melton,Melton,27.3,11.0,5000,PHO@MEM,MEM,PHO,NaN,NaN,NaN,NaN,NaN,PG/SG
105,66867-15590,C,Mason,Mason Plumlee,Plumlee,25.9,13.0,5000,NY@CHA,CHA,NY,NaN,NaN,NaN,NaN,NaN,C
106,66867-23716,SF/PF,Kyle,Kyle Anderson,Anderson,26.1,11.0,4900,PHO@MEM,MEM,PHO,NaN,NaN,NaN,NaN,NaN,SF/PF
107,66867-111273,SF/SG,Luguentz,Luguentz Dort,Dort,23.9,9.0,4900,SAC@OKC,OKC,SAC,NaN,NaN,NaN,NaN,NaN,SG/SF
109,66867-84702,SG/SF,Lonnie,Lonnie Walker,Walker,19.6,11.0,4900,DAL@SA,SA,DAL,NaN,NaN,NaN,NaN,NaN,SG/SF
110,66867-12474,PG,Patrick,Patrick Beverley,Beverley,22.5,8.0,4800,MIN@LAL,MIN,LAL,NaN,NaN,NaN,NaN,NaN,PG
111,66867-55060,SF/SG,Bogdan,Bogdan Bogdanovic,Bogdanovic,26.8,11.0,4800,ATL@DEN,ATL,DEN,GTD,Ankle,NaN,NaN,NaN,SG/SF
112,66867-16233,SF/SG,Josh,Josh Richardson,Richardson,16.8,9.0,4800,MIL@BOS,BOS,MIL,NaN,NaN,NaN,NaN,NaN,SG/SF
113,66867-145307,PF,Isaiah,Isaiah Stewart,Stewart,28.6,10.0,4800,DET@CLE,DET,CLE,NaN,NaN,NaN,NaN,NaN,PF
114,66867-15800,PF/SF,Jae,Jae Crowder,Crowder,22.6,10.0,4800,PHO@MEM,PHO,MEM,NaN,NaN,NaN,NaN,NaN,SF/PF
115,66867-157812,PG,Davion,Davion Mitchell,Mitchell,21.8,12.0,4700,SAC@OKC,SAC,OKC,NaN,NaN,NaN,NaN,NaN,PG
119,66867-18256,PF/SF,Doug,Doug McDermott,McDermott,18.5,8.0,4700,DAL@SA,SA,DAL,NaN,NaN,NaN,NaN,NaN,SF/PF
120,66867-145334,SG,Desmond,Desmond Bane,Bane,24.1,11.0,4700,PHO@MEM,MEM,PHO,NaN,NaN,NaN,NaN,NaN,SG
121,66867-14507,PG,Kemba,Kemba Walker,Walker,23.2,11.0,4600,NY@CHA,NY,CHA,NaN,NaN,NaN,NaN,NaN,PG
122,66867-84718,PF,Alize,Alize Johnson,Johnson,18.9,7.0,4600,CHI@GS,CHI,GS,NaN,NaN,NaN,NaN,NaN,PF
123,66867-110338,SF,De'Andre,De'Andre Hunter,Hunter,24.2,10.0,4600,ATL@DEN,ATL,DEN,GTD,Wrist,NaN,NaN,NaN,SF
124,66867-110351,SG,Cody,Cody Martin,Martin,20.6,13.0,4600,NY@CHA,CHA,NY,NaN,NaN,NaN,NaN,NaN,SG
125,66867-23981,PG/SG,Alex,Alex Caruso,Caruso,23.4,11.0,4600,CHI@GS,CHI,GS,NaN,NaN,NaN,NaN,NaN,PG/SG
126,66867-66064,SF/SG,Malik,Malik Beasley,Beasley,18.3,10.0,4500,MIN@LAL,MIN,LAL,NaN,NaN,NaN,NaN,NaN,SG/SF
127,66867-63126,SF/PF,Cedi,Cedi Osman,Osman,23.8,11.0,4500,DET@CLE,CLE,DET,NaN,NaN,NaN,NaN,NaN,SF/PF
128,66867-84721,PF,Jarred,Jarred Vanderbilt,Vanderbilt,20.5,10.0,4500,MIN@LAL,MIN,LAL,NaN,NaN,NaN,NaN,NaN,PF
130,66867-110339,SG/SF,Cam,Cam Reddish,Reddish,18.4,12.0,4500,ATL@DEN,ATL,DEN,NaN,NaN,NaN,NaN,NaN,SG/SF
132,66867-16376,SF/SG,Dorian,Dorian Finney-Smith,Finney-Smith,20.7,11.0,4500,DAL@SA,DAL,SA,NaN,NaN,NaN,NaN,NaN,SG/SF
133,66867-9739,C,JaVale,JaVale McGee,McGee,25.0,10.0,4400,PHO@MEM,PHO,MEM,NaN,NaN,NaN,NaN,NaN,C
134,66867-145489,PG,Killian,Killian Hayes,Hayes,18.6,9.0,4400,DET@CLE,DET,CLE,NaN,NaN,NaN,NaN,NaN,PG
136,66867-16196,C/PF,Dwight,Dwight Powell,Powell,19.8,11.0,4400,DAL@SA,DAL,SA,NaN,NaN,NaN,NaN,NaN,PF/C
137,66867-80809,SG,Josh,Josh Jackson,Jackson,18.7,10.0,4400,DET@CLE,DET,CLE,NaN,NaN,NaN,NaN,NaN,SG
138,66867-80816,SG,Malik,Malik Monk,Monk,18.7,12.0,4400,MIN@LAL,LAL,MIN,NaN,NaN,NaN,NaN,NaN,SG
139,66867-80823,PF/C,Tony,Tony Bradley,Bradley,27.5,8.0,4400,CHI@GS,CHI,GS,NaN,NaN,NaN,NaN,NaN,PF/C
142,66867-84694,SG,Bruce,Bruce Brown,Brown,20.8,11.0,4300,BKN@NO,BKN,NO,NaN,NaN,NaN,NaN,NaN,SG
143,66867-110995,C,Naz,Naz Reid,Reid,20.4,10.0,4300,MIN@LAL,MIN,LAL,NaN,NaN,NaN,NaN,NaN,C
144,66867-40396,PG,Monte,Monte Morris,Morris,21.9,11.0,4300,ATL@DEN,DEN,ATL,NaN,NaN,NaN,NaN,NaN,PG
145,66867-9703,PG,George,George Hill,Hill,21.2,12.0,4300,MIL@BOS,MIL,BOS,NaN,NaN,NaN,NaN,NaN,PG
146,66867-16363,SG/SF,Joe,Joe Harris,Harris,19.6,12.0,4300,BKN@NO,BKN,NO,NaN,NaN,NaN,NaN,NaN,SG/SF
147,66867-81529,PF/C,Daniel,Daniel Theis,Theis,21.8,9.0,4200,POR@HOU,HOU,POR,NaN,NaN,NaN,NaN,NaN,PF/C
149,66867-84717,PG/SG,Anfernee,Anfernee Simons,Simons,18.5,12.0,4200,POR@HOU,POR,HOU,NaN,NaN,NaN,NaN,NaN,PG/SG
152,66867-145313,PF/SF,Jordan,Jordan Nwora,Nwora,21.2,12.0,4200,MIL@BOS,MIL,BOS,NaN,NaN,NaN,NaN,NaN,SF/PF
156,66867-111372,SF/PF,Thanasis,Thanasis Antetokounmpo,Antetokounmpo,15.9,11.0,4100,MIL@BOS,MIL,BOS,NaN,NaN,NaN,NaN,NaN,SF/PF
157,66867-11074,SF,Garrett,Garrett Temple,Temple,18.2,10.0,4100,BKN@NO,NO,BKN,NaN,NaN,NaN,NaN,NaN,SF
158,66867-18376,SG/PG,Damion,Damion Lee,Lee,18.4,9.0,4100,CHI@GS,GS,CHI,GTD,Hip,NaN,NaN,NaN,PG/SG
160,66867-157848,PF,Herbert,Herbert Jones,Jones,19.7,9.0,4000,BKN@NO,NO,BKN,NaN,NaN,NaN,NaN,NaN,PF
163,66867-9561,C,DeAndre,DeAndre Jordan,Jordan,15.6,12.0,4000,MIN@LAL,LAL,MIN,NaN,NaN,NaN,NaN,NaN,C
164,66867-9660,C,Dwight,Dwight Howard,Howard,16.6,10.0,4000,MIN@LAL,LAL,MIN,NaN,NaN,NaN,NaN,NaN,C
165,66867-145341,SF,Isaac,Isaac Okoro,Okoro,17.8,5.0,4000,DET@CLE,CLE,DET,NaN,NaN,NaN,NaN,NaN,SF
166,66867-15814,C/PF,Alex,Alex Len,Len,16.9,8.0,4000,SAC@OKC,SAC,OKC,NaN,NaN,NaN,NaN,NaN,PF/C
168,66867-12351,C/PF,Derrick,Derrick Favors,Favors,22.9,9.0,3900,SAC@OKC,OKC,SAC,NaN,NaN,NaN,NaN,NaN,PF/C
170,66867-58081,PG,Tyus,Tyus Jones,Jones,17.1,11.0,3900,PHO@MEM,MEM,PHO,NaN,NaN,NaN,NaN,NaN,PG
171,66867-9481,C,Taj,Taj Gibson,Gibson,18.4,7.0,3900,NY@CHA,NY,CHA,NaN,NaN,NaN,NaN,NaN,C
172,66867-15628,SF/PF,Otto,Otto Porter,Porter,17.7,10.0,3900,CHI@GS,GS,CHI,NaN,NaN,NaN,NaN,NaN,SF/PF
176,66867-85305,SF,Kenrich,Kenrich Williams,Williams,17.4,10.0,3900,SAC@OKC,OKC,SAC,NaN,NaN,NaN,NaN,NaN,SF
177,66867-19781,SF/SG,Kent,Kent Bazemore,Bazemore,18.8,12.0,3900,MIN@LAL,LAL,MIN,NaN,NaN,NaN,NaN,NaN,SG/SF
178,66867-15691,C,Cody,Cody Zeller,Zeller,15.2,12.0,3900,POR@HOU,POR,HOU,NaN,NaN,NaN,NaN,NaN,C
179,66867-9556,SF/SG,Eric,Eric Gordon,Gordon,23.0,9.0,3900,POR@HOU,HOU,POR,NaN,NaN,NaN,NaN,NaN,SG/SF
180,66867-9560,PF/C,Blake,Blake Griffin,Griffin,17.6,11.0,3900,BKN@NO,BKN,NO,NaN,NaN,NaN,NaN,NaN,PF/C
183,66867-9664,SF/SG,Andre,Andre Iguodala,Iguodala,15.3,9.0,3900,CHI@GS,GS,CHI,NaN,NaN,NaN,NaN,NaN,SG/SF
184,66867-15405,PF/C,JaMychal,JaMychal Green,Green,15.6,11.0,3800,ATL@DEN,DEN,ATL,NaN,NaN,NaN,NaN,NaN,PF/C
186,66867-14510,SG/SF,Alec,Alec Burks,Burks,15.8,12.0,3800,NY@CHA,NY,CHA,NaN,NaN,NaN,NaN,NaN,SG/SF
189,66867-110353,PF,Brandon,Brandon Clarke,Clarke,17.2,8.0,3800,PHO@MEM,MEM,PHO,NaN,NaN,NaN,NaN,NaN,PF
191,66867-145319,PF,Jaden,Jaden McDaniels,McDaniels,18.4,10.0,3800,MIN@LAL,MIN,LAL,NaN,NaN,NaN,NaN,NaN,PF
192,66867-48567,PG/SG,Cameron,Cameron Payne,Payne,19.3,5.0,3800,PHO@MEM,PHO,MEM,NaN,NaN,NaN,NaN,NaN,PG/SG
196,66867-12334,SG,Avery,Avery Bradley,Bradley,15.9,11.0,3700,MIN@LAL,LAL,MIN,NaN,NaN,NaN,NaN,NaN,SG
198,66867-112709,SG/SF,Javonte,Javonte Green,Green,15.8,11.0,3700,CHI@GS,CHI,GS,NaN,NaN,NaN,NaN,NaN,SG/SF
200,66867-58461,PF,Trey,Trey Lyles,Lyles,17.6,10.0,3700,DET@CLE,DET,CLE,NaN,NaN,NaN,NaN,NaN,PF
205,66867-110316,SF,Cameron,Cameron Johnson,Johnson,17.2,10.0,3700,PHO@MEM,PHO,MEM,NaN,NaN,NaN,NaN,NaN,SF
213,66867-9648,PF/SF,Jeff,Jeff Green,Green,24.1,11.0,3700,ATL@DEN,DEN,ATL,NaN,NaN,NaN,NaN,NaN,SF/PF
234,66867-9637,SF/PF,Danilo,Danilo Gallinari,Gallinari,16.2,9.0,3600,ATL@DEN,ATL,DEN,NaN,NaN,NaN,NaN,NaN,SF/PF
348,66867-145819,SF,Naji,Naji Marshall,Marshall,15.7,11.0,3500,BKN@NO,NO,BKN,GTD,Knee,NaN,NaN,NaN,SF
365,66867-48598,SF,Semi,Semi Ojeleye,Ojeleye,16.8,7.0,3500,MIL@BOS,MIL,BOS,NaN,NaN,NaN,NaN,NaN,SF

In [20]:
df_fd.query('Nickname == "Gordon Hayward"')

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
45,66635-12366,SF/SG,Gordon,Gordon Hayward,Hayward,29.5,11.0,6100,CHA@LAL,CHA,LAL,NaN,NaN,NaN,NaN,NaN,SG/SF

In [12]:
df_fd.to_csv('data/nba/FD_proj.csv')

In [13]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [14]:
from pydfs_lineup_optimizer import Site, Sport, get_optimizer, PlayerFilter, AfterEachExposureStrategy, TeamStack

optimizer = get_optimizer(Site.FANDUEL, Sport.BASKETBALL)
optimizer.load_players_from_csv("data/nba/FD_proj.csv")

p1 = optimizer.player_pool.get_player_by_name("Kevin Porter")
p2 = optimizer.player_pool.get_player_by_name("Jarret Allen")
p3 = optimizer.player_pool.get_player_by_name("Lonzo Ball")
p4 = optimizer.player_pool.get_player_by_name("Evan Mobley")
p5 = optimizer.player_pool.get_player_by_name("Isaiah Stewart")

p1.max_exposure = 0.7
p1.min_exposure = 0.3
p2.max_exposure = 0.7 
p2.min_exposure = 0.3
p3.max_exposure = 0.65
p3.min_exposure = 0.3
p4.max_exposure = 0.65
p4.min_exposure = 0.3
p5.max_exposure = 0.6
p5.min_exposure = 0.3     

# optimizer.add_stack(TeamStack(3, for_teams=['CLE','LAC'], 
#                               max_exposure_per_team={'CLE':0.6, 'LAC':0.55}))                                                                                                                                                                                                           

# optimizer.player_pool.remove_player('Zach LaVine')
optimizer.set_max_repeating_players(5)
for lineup in optimizer.optimize(40, max_exposure=.75, exposure_strategy=AfterEachExposureStrategy):
    print(lineup)
optimizer.export('data/nba/fd_result.csv')

 1. PG      Darius Garland                PG/SG CLE            DET@CLE  33.8           6300.0$
 2. PG      Lonzo Ball                    PG    CHI            CHI@GS   32.6           5800.0$
 3. SG      Jrue Holiday                  PG/SG MIL            MIL@BOS  39.6           6800.0$
 4. SG      Luka Doncic                   PG/SG DAL            DAL@SA   50.6           10200.0$
 5. SF      Jayson Tatum                  PF/SF BOS            MIL@BOS  47.8           9600.0$
 6. SF      Jeff Green                    PF/SF DEN            ATL@DEN  24.1           3700.0$
 7. PF      Bobby Portis                  C/PF  MIL            MIL@BOS  35.7           5800.0$
 8. PF      Isaiah Stewart                PF    DET            DET@CLE  28.6           4800.0$
 9. C       Evan Mobley                   C/PF  CLE            DET@CLE  38.0           6800.0$

Fantasy Points 330.80
Salary 59800.00

 1. PG      Damian Lillard                PG    POR            POR@HOU  42.7           8500.0$
 2. PG      De'Aaron Fox                  PG    SAC            SAC@OKC  39.7           7900.0$
 3. SG      Andrew Wiggins                SF/SG GS             CHI@GS   30.7           5500.0$
 4. SG      Cade Cunningham               PG/SG DET            DET@CLE  30.2           5700.0$
 5. SF      DeMar DeRozan                 SF/SG CHI            CHI@GS   43.4           8700.0$
 6. SF      Mikal Bridges                 PF/SF PHO            PHO@MEM  27.9           5100.0$
 7. PF      Thaddeus Young                C/PF  SA             DAL@SA   30.8           5600.0$
 8. PF      Tony Bradley                  C/PF  CHI            CHI@GS   27.5           4400.0$
 9. C       Jonas Valanciunas             C     NO             BKN@NO   43.7           8600.0$

Fantasy Points 316.60
Salary 60000.00

 1. PG      Damian Lillard                PG    POR            POR@HOU  42.7           8500.0$
 2. PG      Jrue Holiday                  PG/SG MIL            MIL@BOS  39.6           6800.0$
 3. SG      Andrew Wiggins                SF/SG GS             CHI@GS   30.7           5500.0$
 4. SG      DeMar DeRozan                 SF/SG CHI            CHI@GS   43.4           8700.0$
 5. SF      Jayson Tatum                  PF/SF BOS            MIL@BOS  47.8           9600.0$
 6. SF      Jeff Green                    PF/SF DEN            ATL@DEN  24.1           3700.0$
 7. PF      Bobby Portis                  C/PF  MIL            MIL@BOS  35.7           5800.0$
 8. PF      Evan Mobley                   C/PF  CLE            DET@CLE  38.0           6800.0$
 9. C       Tony Bradley                  C/PF  CHI            CHI@GS   27.5           4400.0$

Fantasy Points 329.50
Salary 59800.00

 1. PG      Lonzo Ball                    PG    CHI            CHI@GS   32.6           5800.0$
 2. PG      Trae Young                    PG    ATL            ATL@DEN  43.9           9200.0$
 3. SG      Jrue Holiday                  PG/SG MIL            MIL@BOS  39.6           6800.0$
 4. SG      Luka Doncic                   PG/SG DAL            DAL@SA   50.6           10200.0$
 5. SF      Andrew Wiggins                SF/SG GS             CHI@GS   30.7           5500.0$
 6. SF      Jeff Green                    PF/SF DEN            ATL@DEN  24.1           3700.0$
 7. PF      Bobby Portis                  C/PF  MIL            MIL@BOS  35.7           5800.0$
 8. PF      Tony Bradley                  C/PF  CHI            CHI@GS   27.5           4400.0$
 9. C       Jonas Valanciunas             C     NO             BKN@NO   43.7           8600.0$

Fantasy Points 328.40
Salary 60000.00

 1. PG      Damian Lillard                PG    POR            POR@HOU  42.7           8500.0$
 2. PG      Lonzo Ball                    PG    CHI            CHI@GS   32.6           5800.0$
 3. SG      Darius Garland                PG/SG CLE            DET@CLE  33.8           6300.0$
 4. SG      Luka Doncic                   PG/SG DAL            DAL@SA   50.6           10200.0$
 5. SF      Eric Gordon                   SF/SG HOU            POR@HOU  23.0           3900.0$
 6. SF      Mikal Bridges                 PF/SF PHO            PHO@MEM  27.9           5100.0$
 7. PF      Evan Mobley                   C/PF  CLE            DET@CLE  38.0           6800.0$
 8. PF      Isaiah Stewart                PF    DET            DET@CLE  28.6           4800.0$
 9. C       Jonas Valanciunas             C     NO             BKN@NO   43.7           8600.0$

Fantasy Points 320.90
Salary 60000.00

 1. PG      Cade Cunningham               PG/SG DET            DET@CLE  30.2           5700.0$
 2. PG      Lonzo Ball                    PG    CHI            CHI@GS   32.6           5800.0$
 3. SG      Darius Garland                PG/SG CLE            DET@CLE  33.8           6300.0$
 4. SG      Jrue Holiday                  PG/SG MIL            MIL@BOS  39.6           6800.0$
 5. SF      Andrew Wiggins                SF/SG GS             CHI@GS   30.7           5500.0$
 6. SF      DeMar DeRozan                 SF/SG CHI            CHI@GS   43.4           8700.0$
 7. PF      Bobby Portis                  C/PF  MIL            MIL@BOS  35.7           5800.0$
 8. PF      Evan Mobley                   C/PF  CLE            DET@CLE  38.0           6800.0$
 9. C       Jonas Valanciunas             C     NO             BKN@NO   43.7           8600.0$

Fantasy Points 327.70
Salary 60000.00

 1. PG      De'Aaron Fox                  PG    SAC            SAC@OKC  39.7           7900.0$
 2. PG      De'Anthony Melton             PG/SG MEM            PHO@MEM  27.3           5000.0$
 3. SG      Jrue Holiday                  PG/SG MIL            MIL@BOS  39.6           6800.0$
 4. SG      Luka Doncic                   PG/SG DAL            DAL@SA   50.6           10200.0$
 5. SF      Andrew Wiggins                SF/SG GS             CHI@GS   30.7           5500.0$
 6. SF      Jayson Tatum                  PF/SF BOS            MIL@BOS  47.8           9600.0$
 7. PF      Bobby Portis                  C/PF  MIL            MIL@BOS  35.7           5800.0$
 8. PF      Isaiah Stewart                PF    DET            DET@CLE  28.6           4800.0$
 9. C       Tony Bradley                  C/PF  CHI            CHI@GS   27.5           4400.0$

Fantasy Points 327.50
Salary 60000.00

 1. PG      Cade Cunningham               PG/SG DET            DET@CLE  30.2           5700.0$
 2. PG      Damian Lillard                PG    POR            POR@HOU  42.7           8500.0$
 3. SG      Jrue Holiday                  PG/SG MIL            MIL@BOS  39.6           6800.0$
 4. SG      Luka Doncic                   PG/SG DAL            DAL@SA   50.6           10200.0$
 5. SF      Eric Gordon                   SF/SG HOU            POR@HOU  23.0           3900.0$
 6. SF      Jeff Green                    PF/SF DEN            ATL@DEN  24.1           3700.0$
 7. PF      Bobby Portis                  C/PF  MIL            MIL@BOS  35.7           5800.0$
 8. PF      Evan Mobley                   C/PF  CLE            DET@CLE  38.0           6800.0$
 9. C       Jonas Valanciunas             C     NO             BKN@NO   43.7           8600.0$

Fantasy Points 327.60
Salary 60000.00

 1. PG      Damian Lillard                PG    POR            POR@HOU  42.7           8500.0$
 2. PG      Lonzo Ball                    PG    CHI            CHI@GS   32.6           5800.0$
 3. SG      Darius Garland                PG/SG CLE            DET@CLE  33.8           6300.0$
 4. SG      Luka Doncic                   PG/SG DAL            DAL@SA   50.6           10200.0$
 5. SF      DeMar DeRozan                 SF/SG CHI            CHI@GS   43.4           8700.0$
 6. SF      Jeff Green                    PF/SF DEN            ATL@DEN  24.1           3700.0$
 7. PF      Evan Mobley                   C/PF  CLE            DET@CLE  38.0           6800.0$
 8. PF      Thaddeus Young                C/PF  SA             DAL@SA   30.8           5600.0$
 9. C       Tony Bradley                  C/PF  CHI            CHI@GS   27.5           4400.0$

Fantasy Points 323.50
Salary 60000.00

 1. PG      Cade Cunningham               PG/SG DET            DET@CLE  30.2           5700.0$
 2. PG      Jrue Holiday                  PG/SG MIL            MIL@BOS  39.6           6800.0$
 3. SG      Luka Doncic                   PG/SG DAL            DAL@SA   50.6           10200.0$
 4. SG      Russell Westbrook             PG/SG LAL            MIN@LAL  47.4           9900.0$
 5. SF      DeMar DeRozan                 SF/SG CHI            CHI@GS   43.4           8700.0$
 6. SF      Jeff Green                    PF/SF DEN            ATL@DEN  24.1           3700.0$
 7. PF      Bobby Portis                  C/PF  MIL            MIL@BOS  35.7           5800.0$
 8. PF      Isaiah Stewart                PF    DET            DET@CLE  28.6           4800.0$
 9. C       Tony Bradley                  C/PF  CHI            CHI@GS   27.5           4400.0$

Fantasy Points 327.10
Salary 60000.00

 1. PG      Damian Lillard                PG    POR            POR@HOU  42.7           8500.0$
 2. PG      Darius Garland                PG/SG CLE            DET@CLE  33.8           6300.0$
 3. SG      Jrue Holiday                  PG/SG MIL            MIL@BOS  39.6           6800.0$
 4. SG      Luka Doncic                   PG/SG DAL            DAL@SA   50.6           10200.0$
 5. SF      Mikal Bridges                 PF/SF PHO            PHO@MEM  27.9           5100.0$
 6. SF      Nickeil Alexander-Walker      SF/SG NO             BKN@NO   31.4           6100.0$
 7. PF      Bobby Portis                  C/PF  MIL            MIL@BOS  35.7           5800.0$
 8. PF      Evan Mobley                   C/PF  CLE            DET@CLE  38.0           6800.0$
 9. C       Tony Bradley                  C/PF  CHI            CHI@GS   27.5           4400.0$

Fantasy Points 327.20
Salary 60000.00

 1. PG      De'Aaron Fox                  PG    SAC            SAC@OKC  39.7           7900.0$
 2. PG      Lonzo Ball                    PG    CHI            CHI@GS   32.6           5800.0$
 3. SG      Jrue Holiday                  PG/SG MIL            MIL@BOS  39.6           6800.0$
 4. SG      Russell Westbrook             PG/SG LAL            MIN@LAL  47.4           9900.0$
 5. SF      DeMar DeRozan                 SF/SG CHI            CHI@GS   43.4           8700.0$
 6. SF      Eric Gordon                   SF/SG HOU            POR@HOU  23.0           3900.0$
 7. PF      Bobby Portis                  C/PF  MIL            MIL@BOS  35.7           5800.0$
 8. PF      Evan Mobley                   C/PF  CLE            DET@CLE  38.0           6800.0$
 9. C       Tony Bradley                  C/PF  CHI            CHI@GS   27.5           4400.0$

Fantasy Points 326.90
Salary 60000.00

 1. PG      Damian Lillard                PG    POR            POR@HOU  42.7           8500.0$
 2. PG      De'Aaron Fox                  PG    SAC            SAC@OKC  39.7           7900.0$
 3. SG      Darius Garland                PG/SG CLE            DET@CLE  33.8           6300.0$
 4. SG      Luka Doncic                   PG/SG DAL            DAL@SA   50.6           10200.0$
 5. SF      Andrew Wiggins                SF/SG GS             CHI@GS   30.7           5500.0$
 6. SF      Jeff Green                    PF/SF DEN            ATL@DEN  24.1           3700.0$
 7. PF      Isaiah Stewart                PF    DET            DET@CLE  28.6           4800.0$
 8. PF      Tony Bradley                  C/PF  CHI            CHI@GS   27.5           4400.0$
 9. C       Jonas Valanciunas             C     NO             BKN@NO   43.7           8600.0$

Fantasy Points 321.40
Salary 59900.00

 1. PG      Jrue Holiday                  PG/SG MIL            MIL@BOS  39.6           6800.0$
 2. PG      Lonzo Ball                    PG    CHI            CHI@GS   32.6           5800.0$
 3. SG      Luka Doncic                   PG/SG DAL            DAL@SA   50.6           10200.0$
 4. SG      Zach LaVine                   PG/SG CHI            CHI@GS   41.0           8400.0$
 5. SF      Andrew Wiggins                SF/SG GS             CHI@GS   30.7           5500.0$
 6. SF      Mikal Bridges                 PF/SF PHO            PHO@MEM  27.9           5100.0$
 7. PF      Bobby Portis                  C/PF  MIL            MIL@BOS  35.7           5800.0$
 8. PF      Evan Mobley                   C/PF  CLE            DET@CLE  38.0           6800.0$
 9. C       Thaddeus Young                C/PF  SA             DAL@SA   30.8           5600.0$

Fantasy Points 326.90
Salary 60000.00

 1. PG      Damian Lillard                PG    POR            POR@HOU  42.7           8500.0$
 2. PG      Lonzo Ball                    PG    CHI            CHI@GS   32.6           5800.0$
 3. SG      Jrue Holiday                  PG/SG MIL            MIL@BOS  39.6           6800.0$
 4. SG      Luka Doncic                   PG/SG DAL            DAL@SA   50.6           10200.0$
 5. SF      Andrew Wiggins                SF/SG GS             CHI@GS   30.7           5500.0$
 6. SF      DeMar DeRozan                 SF/SG CHI            CHI@GS   43.4           8700.0$
 7. PF      Bobby Portis                  C/PF  MIL            MIL@BOS  35.7           5800.0$
 8. PF      Isaiah Stewart                PF    DET            DET@CLE  28.6           4800.0$
 9. C       Derrick Favors                C/PF  OKC            SAC@OKC  22.9           3900.0$

Fantasy Points 326.80
Salary 60000.00

 1. PG      Jrue Holiday                  PG/SG MIL            MIL@BOS  39.6           6800.0$
 2. PG      Lonzo Ball                    PG    CHI            CHI@GS   32.6           5800.0$
 3. SG      Luka Doncic                   PG/SG DAL            DAL@SA   50.6           10200.0$
 4. SG      Shai Gilgeous-Alexander       PG/SG OKC            SAC@OKC  39.1           7900.0$
 5. SF      Eric Gordon                   SF/SG HOU            POR@HOU  23.0           3900.0$
 6. SF      Jayson Tatum                  PF/SF BOS            MIL@BOS  47.8           9600.0$
 7. PF      Bobby Portis                  C/PF  MIL            MIL@BOS  35.7           5800.0$
 8. PF      Thaddeus Young                C/PF  SA             DAL@SA   30.8           5600.0$
 9. C       Tony Bradley                  C/PF  CHI            CHI@GS   27.5           4400.0$

Fantasy Points 326.70
Salary 60000.00

 1. PG      De'Aaron Fox                  PG    SAC            SAC@OKC  39.7           7900.0$
 2. PG      Lonzo Ball                    PG    CHI            CHI@GS   32.6           5800.0$
 3. SG      Andrew Wiggins                SF/SG GS             CHI@GS   30.7           5500.0$
 4. SG      Darius Garland                PG/SG CLE            DET@CLE  33.8           6300.0$
 5. SF      DeMar DeRozan                 SF/SG CHI            CHI@GS   43.4           8700.0$
 6. SF      Jayson Tatum                  PF/SF BOS            MIL@BOS  47.8           9600.0$
 7. PF      Evan Mobley                   C/PF  CLE            DET@CLE  38.0           6800.0$
 8. PF      Isaiah Stewart                PF    DET            DET@CLE  28.6           4800.0$
 9. C       Tony Bradley                  C/PF  CHI            CHI@GS   27.5           4400.0$

Fantasy Points 322.10
Salary 59800.00

 1. PG      De'Aaron Fox                  PG    SAC            SAC@OKC  39.7           7900.0$
 2. PG      Lonzo Ball                    PG    CHI            CHI@GS   32.6           5800.0$
 3. SG      Jrue Holiday                  PG/SG MIL            MIL@BOS  39.6           6800.0$
 4. SG      Shai Gilgeous-Alexander       PG/SG OKC            SAC@OKC  39.1           7900.0$
 5. SF      DeMar DeRozan                 SF/SG CHI            CHI@GS   43.4           8700.0$
 6. SF      Jeff Green                    PF/SF DEN            ATL@DEN  24.1           3700.0$
 7. PF      Bobby Portis                  C/PF  MIL            MIL@BOS  35.7           5800.0$
 8. PF      Isaiah Stewart                PF    DET            DET@CLE  28.6           4800.0$
 9. C       Jonas Valanciunas             C     NO             BKN@NO   43.7           8600.0$

Fantasy Points 326.50
Salary 60000.00

 1. PG      Darius Garland                PG/SG CLE            DET@CLE  33.8           6300.0$
 2. PG      De'Aaron Fox                  PG    SAC            SAC@OKC  39.7           7900.0$
 3. SG      Jrue Holiday                  PG/SG MIL            MIL@BOS  39.6           6800.0$
 4. SG      Russell Westbrook             PG/SG LAL            MIN@LAL  47.4           9900.0$
 5. SF      Jayson Tatum                  PF/SF BOS            MIL@BOS  47.8           9600.0$
 6. SF      Jeff Green                    PF/SF DEN            ATL@DEN  24.1           3700.0$
 7. PF      Bobby Portis                  C/PF  MIL            MIL@BOS  35.7           5800.0$
 8. PF      Thaddeus Young                C/PF  SA             DAL@SA   30.8           5600.0$
 9. C       Tony Bradley                  C/PF  CHI            CHI@GS   27.5           4400.0$

Fantasy Points 326.40
Salary 60000.00

 1. PG      De'Aaron Fox                  PG    SAC            SAC@OKC  39.7           7900.0$
 2. PG      De'Anthony Melton             PG/SG MEM            PHO@MEM  27.3           5000.0$
 3. SG      Jrue Holiday                  PG/SG MIL            MIL@BOS  39.6           6800.0$
 4. SG      Luka Doncic                   PG/SG DAL            DAL@SA   50.6           10200.0$
 5. SF      DeMar DeRozan                 SF/SG CHI            CHI@GS   43.4           8700.0$
 6. SF      Jeff Green                    PF/SF DEN            ATL@DEN  24.1           3700.0$
 7. PF      Bobby Portis                  C/PF  MIL            MIL@BOS  35.7           5800.0$
 8. PF      Mikal Bridges                 PF/SF PHO            PHO@MEM  27.9           5100.0$
 9. C       Evan Mobley                   C/PF  CLE            DET@CLE  38.0           6800.0$

Fantasy Points 326.30
Salary 60000.00

 1. PG      Luka Doncic                   PG/SG DAL            DAL@SA   50.6           10200.0$
 2. PG      Shai Gilgeous-Alexander       PG/SG OKC            SAC@OKC  39.1           7900.0$
 3. SG      DeMar DeRozan                 SF/SG CHI            CHI@GS   43.4           8700.0$
 4. SG      Eric Gordon                   SF/SG HOU            POR@HOU  23.0           3900.0$
 5. SF      Jayson Tatum                  PF/SF BOS            MIL@BOS  47.8           9600.0$
 6. SF      Jeff Green                    PF/SF DEN            ATL@DEN  24.1           3700.0$
 7. PF      Evan Mobley                   C/PF  CLE            DET@CLE  38.0           6800.0$
 8. PF      Isaiah Stewart                PF    DET            DET@CLE  28.6           4800.0$
 9. C       Tony Bradley                  C/PF  CHI            CHI@GS   27.5           4400.0$

Fantasy Points 322.10
Salary 60000.00

 1. PG      De'Aaron Fox                  PG    SAC            SAC@OKC  39.7           7900.0$
 2. PG      Jrue Holiday                  PG/SG MIL            MIL@BOS  39.6           6800.0$
 3. SG      Andrew Wiggins                SF/SG GS             CHI@GS   30.7           5500.0$
 4. SG      Eric Gordon                   SF/SG HOU            POR@HOU  23.0           3900.0$
 5. SF      Jayson Tatum                  PF/SF BOS            MIL@BOS  47.8           9600.0$
 6. SF      Mikal Bridges                 PF/SF PHO            PHO@MEM  27.9           5100.0$
 7. PF      Bobby Portis                  C/PF  MIL            MIL@BOS  35.7           5800.0$
 8. PF      Evan Mobley                   C/PF  CLE            DET@CLE  38.0           6800.0$
 9. C       Jonas Valanciunas             C     NO             BKN@NO   43.7           8600.0$

Fantasy Points 326.10
Salary 60000.00

 1. PG      Damian Lillard                PG    POR            POR@HOU  42.7           8500.0$
 2. PG      Lonzo Ball                    PG    CHI            CHI@GS   32.6           5800.0$
 3. SG      De'Anthony Melton             PG/SG MEM            PHO@MEM  27.3           5000.0$