In [1]:
import requests
from bs4 import BeautifulSoup as soup
import pandas as pd
from functions.nba_clean_data import archive_files
from functions.nba_proj_scape import nba_proj_scape

In [2]:
archive_files()

/home/micheal/code/fan_fact/lineupopt/data/nba/FanDuel-NBA-2021 ET-12 ET-29 ET-69397-players-list.csv
/home/micheal/code/fan_fact/lineupopt/data/nba/FanDuel-NBA-2021 ET-11 ET-02 ET-66298-players-list.csv
/home/micheal/code/fan_fact/lineupopt/data/nba/FD_proj.csv
/home/micheal/code/fan_fact/lineupopt/data/nba/fd_result.csv

In [6]:
df_fd = pd.read_csv('data/nba/FanDuel-NBA-2022 ET-01 ET-06 ET-69815-players-list.csv')

In [11]:
stats_df = nba_proj_scape()
stats_df

           Nickname    FP Value    Min
0         Ja Morant  43.1  4.23  34.45
1     Julius Randle  41.2  4.58  36.36
2      Jayson Tatum  40.9  4.17  35.87
3      Devin Booker  39.8  4.52  36.06
4        Chris Paul  39.3  5.04  33.26
..              ...   ...   ...    ...
129      Luka Garza   0.0     0   0.03
130  Draymond Green   0.0     0   0.00
131   Stephen Curry   0.0     0   0.00
132    Xavier Sneed   0.0     0   0.01
133    Tyrell Terry   0.0     0   0.05

[134 rows x 4 columns]

In [12]:
df_fd = pd.merge(df_fd, stats_df, how='left', on='Nickname')
df_fd.head()

             Id Position First Name  ...    FP Value    Min
0    69815-9524       PG    Stephen  ...   0.0     0   0.00
1  69815-110344       PG         Ja  ...  43.1  4.23  34.45
2   69815-80808    SF/PF     Jayson  ...  40.9  4.17  35.87
3  69815-110310       PF       Zion  ...   NaN   NaN    NaN
4   69815-12341    SG/SF       Paul  ...   NaN   NaN    NaN

[5 rows x 20 columns]

In [14]:
pd.set_option('display.max_rows', df_fd.shape[0]+1)
cols = ['FP', 'Value', 'Min']
df_fd[cols] = df_fd[cols].astype(float).fillna(0.0)
df_fd = df_fd[df_fd.FP > 15.0]
df_fd

               Id Position  First Name  ...    FP Value    Min
1    69815-110344       PG          Ja  ...  43.1  4.23  34.45
2     69815-80808    SF/PF      Jayson  ...  40.9  4.17  35.87
5     69815-42669     PF/C      Julius  ...  41.2  4.58  36.36
6     69815-67026    SF/SG      Jaylen  ...  37.8  4.20  34.87
7     69815-58460       SG       Devin  ...  39.8  4.52  36.06
8    69815-145328       SF      Saddiq  ...  32.3  3.80  38.35
10    69815-66048       SF     Brandon  ...  37.8  4.78  36.78
11    69815-14503        C       Jonas  ...  37.6  4.76  30.40
12     69815-9623       PG       Chris  ...  39.3  5.04  33.26
14    69815-40562    SG/SF        Josh  ...  29.4  3.87  34.66
15    69815-84708     PF/C      Robert  ...  28.4  3.73  25.91
17    69815-84699    SG/SF     Hamidou  ...  29.9  3.99  32.32
19    69815-49116       SF      Andrew  ...  33.6  4.67  32.26
20    69815-23670    SG/PG      Marcus  ...  28.5  4.08  34.87
21    69815-14512    PF/SF      Marcus  ...  31.8  4.61  33.79
22   69815-157808    PG/SG        Cade  ...  36.3  5.34  35.07
23     69815-9453     PF/C          Al  ...  28.4  4.17  28.89
24   69815-157848       PF     Herbert  ...  22.9  3.42  30.93
25    69815-84683     PF/C       Jaren  ...  33.9  5.13  30.80
26    69815-84706    PG/SG    Devonte'  ...  26.4  4.19  29.79
27    69815-60233    SG/SF      Dillon  ...  29.4  4.75  32.22
29    69815-84703    SG/PG  De'Anthony  ...  27.9  4.50  27.38
30    69815-14510    SG/SF        Alec  ...  30.6  5.09  35.59
31   69815-110357    SF/SG          RJ  ...  27.6  4.67  28.52
32   69815-145322     PF/C       Jalen  ...  29.0  4.91  26.90
33    69815-15628    SF/PF        Otto  ...  30.4  5.24  31.93
34    69815-14523       PG      Reggie  ...  30.0  5.25  33.17
35   69815-110322    PG/SG      Jordan  ...  31.3  5.49  33.26
36   69815-110353       PF     Brandon  ...  26.0  4.64  25.32
38   69815-110316       SF     Cameron  ...  25.1  4.56  30.87
39   69815-110340       PF      Jaxson  ...  19.1  3.54  20.52
41    69815-12355    SG/PG        Eric  ...  26.4  4.89  29.51
42    69815-23169        C      Steven  ...  25.6  4.75  26.36
43   69815-145307       PF      Isaiah  ...  31.3  5.79  27.89
45    69815-84670    SF/PF       Mikal  ...  24.3  4.50  32.33
46    69815-58084       SF     Justise  ...  23.1  4.27  20.88
47    69815-84709        C    Mitchell  ...  24.6  4.55  27.38
48    69815-40201    PG/SG      Dennis  ...  21.8  4.12  26.90
54   69815-111492       PF        Amir  ...  16.9  3.32  20.18
58    69815-23096    SF/SG        Evan  ...  20.7  4.13  25.53
59    69815-16233    SF/SG        Josh  ...  18.9  3.77  26.90
62   69815-110315    SG/SF     Terance  ...  27.6  5.52  34.11
63    69815-58461       PF        Trey  ...  17.8  3.63  17.90
64    69815-48567    PG/SG     Cameron  ...  26.0  5.31  24.92
65    69815-58576     C/PF       Kevon  ...  18.0  3.67  20.52
69   69815-145348    SG/PG    Immanuel  ...  24.0  5.10  28.58
73   69815-157826       SG     Quentin  ...  17.3  3.75  23.79
74    69815-80809       SG        Josh  ...  23.6  5.12  21.81
75    69815-23825        C     Nerlens  ...  18.0  4.00  20.98
78   69815-145310       PG       Saben  ...  15.3  3.47  14.66
81   69815-110356    SG/SF     Nickeil  ...  24.6  5.85  28.12
84    69815-18376       SG      Damion  ...  16.8  4.00  21.73
85     69815-9957     PF/C       Serge  ...  20.8  4.95  18.69
88   69815-145489       PG     Killian  ...  18.9  4.72  25.58
90     69815-9664    SF/SG       Andre  ...  20.8  5.19  25.44
99    69815-12368       PF     Nemanja  ...  16.2  4.38  16.85
105    69815-9809    SF/PF     Nicolas  ...  22.9  6.35  25.35
111  69815-111371       PG      Justin  ...  18.3  5.22  23.02

[58 rows x 20 columns]

In [15]:
df_fd['FPPG'] = df_fd.FP

In [16]:
dropped_cols = ['FP', 'Value', 'Min']
df_fd.drop(dropped_cols, axis=1, inplace=True)

In [17]:
df_fd.to_csv('data/nba/FD_proj.csv')

In [18]:
from pydfs_lineup_optimizer import Site, Sport, get_optimizer, PlayerFilter, AfterEachExposureStrategy, TeamStack, RandomFantasyPointsStrategy
optimizer = get_optimizer(Site.FANDUEL, Sport.BASKETBALL)
optimizer.load_players_from_csv("data/nba/FD_proj.csv")

In [20]:
for lineup in optimizer.optimize(1, max_exposure=.75, exposure_strategy=AfterEachExposureStrategy):
    print(lineup)
optimizer.export('data/nba/fd_result.csv')

 1. PG      Cade Cunningham               PG/SG DET            DET@MEM  36.3           6800.0$
 2. PG      Chris Paul                    PG    PHO            LAC@PHO  39.3           7800.0$
 3. SG      Jordan Poole                  PG/SG GS             GS@NO    31.3           5700.0$
 4. SG      Terance Mann                  SF/SG LAC            LAC@PHO  27.6           5000.0$
 5. SF      Brandon Ingram                SF    NO             GS@NO    37.8           7900.0$
 6. SF      Otto Porter                   PF/SF GS             GS@NO    30.4           5800.0$
 7. PF      Isaiah Stewart                PF    DET            DET@MEM  31.3           5400.0$
 8. PF      Jaren Jackson                 C/PF  MEM            DET@MEM  33.9           6600.0$
 9. C       Julius Randle                 C/PF  NY             BOS@NY   41.2           9000.0$

Fantasy Points 309.10
Salary 60000.00