In [3]:
import requests
from bs4 import BeautifulSoup as soup
import pandas as pd
from functions.nba_clean_data import archive_files
from functions.nba_proj_scape import nba_proj_scape

archive_files()

In [4]:
# %load functions/get_nba_spread

In [5]:
def get_spread_page():
    url = "https://rotogrinders.com/lineups/nba?site=fanduel"
    html = requests.get(url).text
    page = soup(html)
    return page
page = get_spread_page()

team_list = page.find_all("span", {"class": "shrt"})
teams = [i.text for i in team_list]
odds_list = page.find_all("a", {"href": "/nba/odds"})
odds = [i.text for i in odds_list]
teams.sort()
print(teams)

['ATL', 'BOS', 'CHA', 'CHI', 'DAL', 'DET', 'IND', 'LAC', 'LAL', 'MEM', 'MIA', 'NYK', 'OKC', 'PHO', 'POR', 'SAC', 'SAS', 'UTA']

In [6]:
df_fd = pd.read_csv('data/nba/FanDuel-NBA-2021 ET-12 ET-29 ET-69397-players-list.csv')
teams2 = list(df_fd.Team.unique())
teams2.sort()
print(teams2)

['ATL', 'BOS', 'CHA', 'CHI', 'DAL', 'DET', 'IND', 'LAC', 'LAL', 'MEM', 'MIA', 'NY', 'OKC', 'PHO', 'POR', 'SA', 'SAC', 'UTA']

In [7]:
replace_dict = {"GSW":"GS", "NYK":"NY", "NOP":"NO", "SAS":"SA"}
clean_teams = [replace_dict.get(item,item) for item in teams]
print(clean_teams)

['ATL', 'BOS', 'CHA', 'CHI', 'DAL', 'DET', 'IND', 'LAC', 'LAL', 'MEM', 'MIA', 'NY', 'OKC', 'PHO', 'POR', 'SAC', 'SA', 'UTA']

df_fd = df_fd[(df_fd.Team == 'MIA') | (df_fd.Team == 'SA')]
df_fd

df_fd.query("Nickname == 'Mo Bamba'")

In [8]:
df_odds = dict(zip(clean_teams, odds))
#print(df_odds)
print(dict(sorted(df_odds.items(), key=lambda item: item[1])))

{'DAL': '102.25', 'OKC': '102.50', 'CHI': '103.00', 'MIA': '105.25', 'DET': '108.75', 'LAL': '109.50', 'UTA': '109.50', 'IND': '109.75', 'SAC': '110.50', 'CHA': '111.00', 'SA': '111.00', 'ATL': '111.25', 'NY': '111.75', 'BOS': '115.25', 'LAC': '115.75', 'PHO': '117.00', 'MEM': '117.50', 'POR': '117.50'}

In [9]:
stats_df = nba_proj_scape()
stats_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Nickname  230 non-null    object
 1   FP        230 non-null    object
 2   Value     230 non-null    object
 3   Min       230 non-null    object
dtypes: object(4)
memory usage: 7.3+ KB

In [10]:
try:
    stats_df.replace("Mohamed Bamba", "Mo Bamba", regex=True, inplace=True)
    stats_df.query("Nickname == 'Mo Bamba'")
except:
    print('no mo bamba')

In [11]:
df_fd = pd.merge(df_fd, stats_df, how='left', on='Nickname')
df_fd

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position,FP,Value,Min
0,69397-9488,SF/PF,LeBron,LeBron James,James,50.717391,23.0,11200,LAL@MEM,LAL,MEM,GTD,Abdomen,NaN,NaN,NaN,SF/PF,52.8,4.71,38.29
1,69397-67708,PG/SG,Dejounte,Dejounte Murray,Murray,45.961292,31.0,10200,MIA@SA,SA,MIA,O,Postponed,NaN,NaN,NaN,PG/SG,NaN,NaN,NaN
2,69397-84669,PG/SG,Luka,Luka Doncic,Doncic,48.076189,21.0,10000,DAL@SAC,DAL,SAC,O,Covid-19,NaN,NaN,NaN,PG/SG,NaN,NaN,NaN
3,69397-80808,SF/PF,Jayson,Jayson Tatum,Tatum,44.212121,33.0,9900,LAC@BOS,BOS,LAC,O,Covid-19,NaN,NaN,NaN,SF/PF,NaN,NaN,NaN
4,69397-9642,PG,Russell,Russell Westbrook,Westbrook,41.462856,35.0,9800,LAL@MEM,LAL,MEM,NaN,NaN,NaN,NaN,NaN,PG,44.3,4.52,36.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344,69397-145354,SG,Devon,Devon Dotson,Dotson,6.866667,6.0,3500,ATL@CHI,CHI,ATL,NaN,NaN,NaN,NaN,NaN,SG,0.0,0,0.05
345,69397-101330,SF,Emanuel,Emanuel Terry,Terry,NaN,NaN,3500,OKC@PHO,PHO,OKC,NaN,NaN,NaN,NaN,NaN,SF,0.0,0,0.02
346,69397-49115,SG,Wayne,Wayne Selden,Selden,2.566667,3.0,3500,NY@DET,NY,DET,O,Covid-19,NaN,NaN,NaN,SG,NaN,NaN,NaN
347,69397-97263,C/PF,Drew,Drew Eubanks,Eubanks,13.843750,32.0,3500,MIA@SA,SA,MIA,O,Postponed,NaN,NaN,NaN,PF/C,NaN,NaN,NaN
348,69397-9725,SF,C.J.,C.J. Miles,Miles,0.000000,1.0,3500,LAC@BOS,BOS,LAC,O,Covid-19,NaN,NaN,NaN,SF,NaN,NaN,NaN

In [12]:
pd.set_option('display.max_rows', df_fd.shape[0]+1)
cols = ['FP', 'Value', 'Min']
df_fd[cols] = df_fd[cols].astype(float).fillna(0.0)
df_fd = df_fd[df_fd.FP > 15.0]
df_fd

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position,FP,Value,Min
0,69397-9488,SF/PF,LeBron,LeBron James,James,50.717391,23.0,11200,LAL@MEM,LAL,MEM,GTD,Abdomen,NaN,NaN,NaN,SF/PF,52.8,4.71,38.29
4,69397-9642,PG,Russell,Russell Westbrook,Westbrook,41.462856,35.0,9800,LAL@MEM,LAL,MEM,NaN,NaN,NaN,NaN,NaN,PG,44.3,4.52,36.16
5,69397-84671,PG,Trae,Trae Young,Young,45.253333,30.0,9700,ATL@CHI,ATL,CHI,NaN,NaN,NaN,NaN,NaN,PG,50.0,5.15,37.29
7,69397-145485,PG,LaMelo,LaMelo Ball,Ball,44.482759,29.0,9400,CHA@IND,CHA,IND,NaN,NaN,NaN,NaN,NaN,PG,44.9,4.78,33.65
9,69397-84680,SG/PG,Shai,Shai Gilgeous-Alexander,Gilgeous-Alexander,39.026668,30.0,9300,OKC@PHO,OKC,PHO,NaN,NaN,NaN,NaN,NaN,PG/SG,42.1,4.53,34.31
10,69397-9714,SG/SF,DeMar,DeMar DeRozan,DeRozan,41.282144,28.0,9200,ATL@CHI,CHI,ATL,NaN,NaN,NaN,NaN,NaN,SG/SF,42.6,4.63,34.06
11,69397-40203,C,Rudy,Rudy Gobert,Gobert,42.445453,33.0,9100,UTA@POR,UTA,POR,NaN,NaN,NaN,NaN,NaN,C,42.9,4.71,33.09
12,69397-20848,PG,Damian,Damian Lillard,Lillard,40.055556,27.0,9000,UTA@POR,POR,UTA,NaN,NaN,NaN,NaN,NaN,PG,47.7,5.30,38.08
13,69397-63122,PF/C,Kristaps,Kristaps Porzingis,Porzingis,38.966667,24.0,8900,DAL@SAC,DAL,SAC,NaN,NaN,NaN,NaN,NaN,PF/C,47.8,5.37,34.66
14,69397-67026,SF/SG,Jaylen,Jaylen Brown,Brown,35.675000,20.0,8800,LAC@BOS,BOS,LAC,NaN,NaN,NaN,NaN,NaN,SG/SF,42.4,4.82,36.21
15,69397-42669,PF/C,Julius,Julius Randle,Randle,39.655884,34.0,8700,NY@DET,NY,DET,NaN,NaN,NaN,NaN,NaN,PF/C,40.2,4.61,35.99
16,69397-110344,PG,Ja,Ja Morant,Morant,42.660870,23.0,8600,LAL@MEM,MEM,LAL,NaN,NaN,NaN,NaN,NaN,PG,42.0,4.89,32.82
17,69397-40783,SG/PG,Zach,Zach LaVine,LaVine,39.248274,29.0,8600,ATL@CHI,CHI,ATL,NaN,NaN,NaN,NaN,NaN,PG/SG,41.6,4.84,34.70
20,69397-59358,PF/C,Domantas,Domantas Sabonis,Sabonis,39.678789,33.0,8400,CHA@IND,IND,CHA,NaN,NaN,NaN,NaN,NaN,PF/C,44.4,5.28,35.33
21,69397-14514,C,Nikola,Nikola Vucevic,Vucevic,39.133334,24.0,8300,ATL@CHI,CHI,ATL,NaN,NaN,NaN,NaN,NaN,C,42.1,5.07,34.06
24,69397-9623,PG,Chris,Chris Paul,Paul,38.803030,33.0,8200,OKC@PHO,PHO,OKC,NaN,NaN,NaN,NaN,NaN,PG,37.4,4.56,31.60
27,69397-145337,PG/SG,Tyrese,Tyrese Haliburton,Haliburton,33.927272,33.0,8100,DAL@SAC,SAC,DAL,NaN,NaN,NaN,NaN,NaN,PG/SG,34.1,4.21,31.07
29,69397-55059,C,Clint,Clint Capela,Capela,35.167740,31.0,8000,ATL@CHI,ATL,CHI,NaN,NaN,NaN,NaN,NaN,C,39.0,4.87,32.03
30,69397-14507,PG,Kemba,Kemba Walker,Walker,25.917390,23.0,7900,NY@DET,NY,DET,NaN,NaN,NaN,NaN,NaN,PG,31.5,3.98,32.00
34,69397-16359,PG/SG,Malcolm,Malcolm Brogdon,Brogdon,36.223076,26.0,7800,CHA@IND,IND,CHA,GTD,Achilles,NaN,NaN,NaN,PG/SG,36.0,4.62,34.08
36,69397-58460,SG,Devin,Devin Booker,Booker,37.384615,26.0,7600,OKC@PHO,PHO,OKC,NaN,NaN,NaN,NaN,NaN,SG,40.2,5.29,35.57
37,69397-145334,SG,Desmond,Desmond Bane,Bane,28.482858,35.0,7600,LAL@MEM,MEM,LAL,NaN,NaN,NaN,NaN,NaN,SG,30.8,4.05,32.60
39,69397-84690,PG/SG,Jalen,Jalen Brunson,Brunson,29.715626,32.0,7400,DAL@SAC,DAL,SAC,NaN,NaN,NaN,NaN,NaN,PG/SG,36.0,4.86,35.57
40,69397-80810,PG,De'Aaron,De'Aaron Fox,Fox,35.235485,31.0,7400,DAL@SAC,SAC,DAL,NaN,NaN,NaN,NaN,NaN,PG,37.1,5.01,34.01
41,69397-12366,SF/SG,Gordon,Gordon Hayward,Hayward,30.685296,34.0,7300,CHA@IND,CHA,IND,NaN,NaN,NaN,NaN,NaN,SG/SF,32.1,4.39,31.87
42,69397-58253,C/PF,Myles,Myles Turner,Turner,33.030303,33.0,7200,CHA@IND,IND,CHA,NaN,NaN,NaN,NaN,NaN,PF/C,37.7,5.24,33.67
43,69397-9575,PG,Mike,Mike Conley,Conley,28.056667,30.0,7100,UTA@POR,UTA,POR,NaN,NaN,NaN,NaN,NaN,PG,29.5,4.16,29.13
44,69397-9453,PF/C,Al,Al Horford,Horford,33.076001,25.0,7000,LAC@BOS,BOS,LAC,NaN,NaN,NaN,NaN,NaN,PF/C,32.3,4.62,30.28
47,69397-84683,PF/C,Jaren,Jaren Jackson,Jackson,30.717648,34.0,6700,LAL@MEM,MEM,LAL,NaN,NaN,NaN,NaN,NaN,PF/C,33.8,5.05,30.41
48,69397-23798,SG/SF,Caris,Caris LeVert,LeVert,29.453846,26.0,6600,CHA@IND,IND,CHA,NaN,NaN,NaN,NaN,NaN,SG/SF,37.0,5.60,34.66
50,69397-14512,PF/SF,Marcus,Marcus Morris,Morris,24.564285,14.0,6500,LAC@BOS,LAC,BOS,NaN,NaN,NaN,NaN,NaN,SF/PF,26.5,4.08,31.31
51,69397-84708,PF/C,Robert,Robert Williams,Williams,28.615385,26.0,6500,LAC@BOS,BOS,LAC,NaN,NaN,NaN,NaN,NaN,PF/C,31.2,4.80,26.20
52,69397-110343,SF,Nassir,Nassir Little,Little,21.292858,28.0,6500,UTA@POR,POR,UTA,NaN,NaN,NaN,NaN,NaN,SF,27.8,4.27,32.24
53,69397-9508,SF/PF,Carmelo,Carmelo Anthony,Anthony,24.111429,35.0,6500,LAL@MEM,LAL,MEM,NaN,NaN,NaN,NaN,NaN,SF/PF,24.6,3.78,28.59
54,69397-42677,SG/PG,Terry,Terry Rozier,Rozier,29.834616,26.0,6400,CHA@IND,CHA,IND,NaN,NaN,NaN,NaN,NaN,PG/SG,33.0,5.16,33.65
57,69397-145328,SF,Saddiq,Saddiq Bey,Bey,26.931250,32.0,6400,NY@DET,DET,NY,NaN,NaN,NaN,NaN,NaN,SF,35.3,5.52,40.61
59,69397-58153,SF/SG,Kelly,Kelly Oubre,Oubre,26.720000,35.0,6300,CHA@IND,CHA,IND,NaN,NaN,NaN,NaN,NaN,SG/SF,31.6,5.01,32.79
60,69397-15946,SF/PF,Harrison,Harrison Barnes,Barnes,29.683333,30.0,6200,DAL@SAC,SAC,DAL,NaN,NaN,NaN,NaN,NaN,SF/PF,30.1,4.86,34.01
61,69397-23665,SG/SF,Buddy,Buddy Hield,Hield,25.442857,35.0,6200,DAL@SAC,SAC,DAL,NaN,NaN,NaN,NaN,NaN,SG/SF,21.4,3.45,24.24
64,69397-145335,PG/SG,Payton,Payton Pritchard,Pritchard,9.982143,28.0,6200,LAC@BOS,BOS,LAC,NaN,NaN,NaN,NaN,NaN,PG/SG,21.1,3.40,26.13
65,69397-16376,SF/SG,Dorian,Dorian Finney-Smith,Finney-Smith,23.759375,32.0,6200,DAL@SAC,DAL,SAC,NaN,NaN,NaN,NaN,NaN,SG/SF,26.5,4.28,35.07
66,69397-20640,PG/SG,Jordan,Jordan Clarkson,Clarkson,24.042425,33.0,6100,UTA@POR,UTA,POR,NaN,NaN,NaN,NaN,NaN,PG/SG,29.8,4.88,27.08
68,69397-16293,SF/SG,Norman,Norman Powell,Powell,26.803448,29.0,6100,UTA@POR,POR,UTA,NaN,NaN,NaN,NaN,NaN,SG/SF,32.8,5.37,37.08
70,69397-84699,SG/SF,Hamidou,Hamidou Diallo,Diallo,17.204000,25.0,6000,NY@DET,DET,NY,NaN,NaN,NaN,NaN,NaN,SG/SF,33.4,5.57,35.54
71,69397-23447,C/PF,Richaun,Richaun Holmes,Holmes,27.856001,25.0,6000,DAL@SAC,SAC,DAL,NaN,NaN,NaN,NaN,NaN,PF/C,28.4,4.73,28.18
75,69397-23670,SG/PG,Marcus,Marcus Smart,Smart,28.684376,32.0,5800,LAC@BOS,BOS,LAC,GTD,Hand,NaN,NaN,NaN,PG/SG,31.6,5.44,35.20
82,69397-111273,SF/SG,Luguentz,Luguentz Dort,Dort,26.345162,31.0,5600,OKC@PHO,OKC,PHO,NaN,NaN,NaN,NaN,NaN,SG/SF,26.8,4.79,33.17
83,69397-14530,SF/PF,Bojan,Bojan Bogdanovic,Bogdanovic,24.151515,33.0,5600,UTA@POR,UTA,POR,NaN,NaN,NaN,NaN,NaN,SF/PF,26.3,4.70,30.08
85,69397-110315,SG/SF,Terance,Terance Mann,Mann,21.081819,33.0,5600,LAC@BOS,LAC,BOS,NaN,NaN,NaN,NaN,NaN,SG/SF,25.7,4.59,31.81
86,69397-110326,PG/SG,Coby,Coby White,White,13.576923,13.0,5600,ATL@CHI,CHI,ATL,NaN,NaN,NaN,NaN,NaN,PG/SG,23.4,4.18,30.04
87,69397-23096,SF/SG,Evan,Evan Fournier,Fournier,21.229411,34.0,5500,NY@DET,NY,DET,NaN,NaN,NaN,NaN,NaN,SG/SF,23.1,4.20,27.58
88,69397-12355,SG/PG,Eric,Eric Bledsoe,Bledsoe,23.729411,34.0,5500,LAC@BOS,LAC,BOS,NaN,NaN,NaN,NaN,NaN,PG/SG,30.6,5.56,32.78
90,69397-84709,C,Mitchell,Mitchell Robinson,Robinson,23.987096,31.0,5500,NY@DET,NY,DET,NaN,NaN,NaN,NaN,NaN,C,26.1,4.74,26.81
91,69397-15590,C,Mason,Mason Plumlee,Plumlee,23.823078,26.0,5500,CHA@IND,CHA,IND,NaN,NaN,NaN,NaN,NaN,C,26.0,4.73,26.20
92,69397-110357,SF/SG,RJ,RJ Barrett,Barrett,24.959260,27.0,5500,NY@DET,NY,DET,NaN,NaN,NaN,NaN,NaN,SG/SF,25.1,4.57,32.89
94,69397-80824,PG,Frank,Frank Jackson,Jackson,15.368750,32.0,5500,NY@DET,DET,NY,NaN,NaN,NaN,NaN,NaN,PG,30.1,5.47,40.61
97,69397-110339,SG/SF,Cam,Cam Reddish,Reddish,20.372413,29.0,5400,ATL@CHI,ATL,CHI,NaN,NaN,NaN,NaN,NaN,SG/SF,31.4,5.82,37.94
99,69397-48567,PG/SG,Cameron,Cameron Payne,Payne,20.160714,28.0,5400,OKC@PHO,PHO,OKC,NaN,NaN,NaN,NaN,NaN,PG/SG,24.0,4.44,22.73
102,69397-157828,SF,Chris,Chris Duarte,Duarte,23.059376,32.0,5300,CHA@IND,IND,CHA,NaN,NaN,NaN,NaN,NaN,SF,20.1,3.78,25.70
103,69397-70827,C,Ivica,Ivica Zubac,Zubac,25.008823,34.0,5300,LAC@BOS,LAC,BOS,NaN,NaN,NaN,NaN,NaN,C,26.6,5.02,26.99
104,69397-84670,SF/PF,Mikal,Mikal Bridges,Bridges,24.218182,33.0,5300,OKC@PHO,PHO,OKC,NaN,NaN,NaN,NaN,NaN,SF/PF,26.7,5.04,35.61
105,69397-110316,SF,Cameron,Cameron Johnson,Johnson,20.393939,33.0,5300,OKC@PHO,PHO,OKC,NaN,NaN,NaN,NaN,NaN,SF,27.3,5.15,33.73
107,69397-145348,SG/PG,Immanuel,Immanuel Quickley,Quickley,17.826666,30.0,5300,NY@DET,NY,DET,NaN,NaN,NaN,NaN,NaN,PG/SG,21.5,4.06,26.27
108,69397-9739,C,JaVale,JaVale McGee,McGee,22.087880,33.0,5200,OKC@PHO,PHO,OKC,NaN,NaN,NaN,NaN,NaN,C,36.0,6.92,25.81
109,69397-157829,SG,Aaron,Aaron Wiggins,Wiggins,10.486667,15.0,5200,OKC@PHO,OKC,PHO,NaN,NaN,NaN,NaN,NaN,SG,22.3,4.29,29.35
110,69397-14510,SG/SF,Alec,Alec Burks,Burks,22.666667,33.0,5200,NY@DET,NY,DET,NaN,NaN,NaN,NaN,NaN,SG/SF,23.4,4.50,28.57
111,69397-110351,SG/PG,Cody,Cody Martin,Martin,23.519999,30.0,5200,CHA@IND,CHA,IND,NaN,NaN,NaN,NaN,NaN,PG/SG,22.6,4.35,27.37
112,69397-23716,SF/PF,Kyle,Kyle Anderson,Anderson,22.474194,31.0,5100,LAL@MEM,MEM,LAL,NaN,NaN,NaN,NaN,NaN,SF/PF,28.9,5.67,27.85
122,69397-116340,SG/SF,Terence,Terence Davis,Davis,17.140909,22.0,4800,DAL@SAC,SAC,DAL,NaN,NaN,NaN,NaN,NaN,SG/SF,15.8,3.30,16.35
123,69397-23169,C,Steven,Steven Adams,Adams,25.151428,35.0,4800,LAL@MEM,MEM,LAL,NaN,NaN,NaN,NaN,NaN,C,24.6,5.13,26.85
126,69397-110350,PF,Jalen,Jalen McDaniels,McDaniels,14.635714,28.0,4800,CHA@IND,CHA,IND,NaN,NaN,NaN,NaN,NaN,PF,24.0,5.01,30.35
128,69397-16233,SF/SG,Josh,Josh Richardson,Richardson,18.981818,22.0,4800,LAC@BOS,BOS,LAC,NaN,NaN,NaN,NaN,NaN,SG/SF,18.9,3.94,24.29
129,69397-145322,PF/C,Jalen,Jalen Smith,Smith,9.916667,12.0,4800,OKC@PHO,PHO,OKC,NaN,NaN,NaN,NaN,NaN,PF/C,17.3,3.61,18.01
131,69397-145325,SG,Josh,Josh Green,Green,7.611111,18.0,4800,DAL@SAC,DAL,SAC,NaN,NaN,NaN,NaN,NaN,SG,19.3,4.01,25.22
133,69397-157807,C,Luka,Luka Garza,Garza,8.575000,20.0,4700,NY@DET,DET,NY,NaN,NaN,NaN,NaN,NaN,C,23.3,4.96,25.38
137,69397-110337,SG/SF,Talen,Talen Horton-Tucker,Horton-Tucker,22.463157,19.0,4700,LAL@MEM,LAL,MEM,NaN,NaN,NaN,NaN,NaN,SG/SF,24.7,5.24,29.56
139,69397-80816,SG,Malik,Malik Monk,Monk,19.069999,30.0,4700,LAL@MEM,LAL,MEM,NaN,NaN,NaN,NaN,NaN,SG,23.5,5.00,29.67
140,69397-66046,SG/SF,Luke,Luke Kennard,Kennard,19.993939,33.0,4700,LAC@BOS,LAC,BOS,NaN,NaN,NaN,NaN,NaN,SG/SF,25.2,5.35,29.86
141,69397-145536,PG,Theo,Theo Maledon,Maledon,7.282353,17.0,4600,OKC@PHO,OKC,PHO,NaN,NaN,NaN,NaN,NaN,PG,17.7,3.85,21.30
144,69397-110353,PF,Brandon,Brandon Clarke,Clarke,18.238095,21.0,4600,LAL@MEM,MEM,LAL,NaN,NaN,NaN,NaN,NaN,PF,17.7,3.86,17.82
146,69397-16196,C/PF,Dwight,Dwight Powell,Powell,15.260606,33.0,4500,DAL@SAC,DAL,SAC,NaN,NaN,NaN,NaN,NaN,PF/C,20.4,4.54,23.85
148,69397-40262,SG,Sterling,Sterling Brown,Brown,10.800000,25.0,4500,DAL@SAC,DAL,SAC,NaN,NaN,NaN,NaN,NaN,SG,16.0,3.56,20.02
149,69397-18338,SF/PF,Royce,Royce O'Neale,O'Neale,22.096774,31.0,4500,UTA@POR,UTA,POR,NaN,NaN,NaN,NaN,NaN,SF/PF,22.0,4.90,32.08
151,69397-59318,SG/SF,Joe,Joe Ingles,Ingles,18.042425,33.0,4500,UTA@POR,UTA,POR,NaN,NaN,NaN,NaN,NaN,SG/SF,23.8,5.28,29.07
155,69397-85305,SF,Kenrich,Kenrich Williams,Williams,16.900000,30.0,4400,OKC@PHO,OKC,PHO,NaN,NaN,NaN,NaN,NaN,SF,26.6,6.04,29.24
157,69397-117283,SF,Oshae,Oshae Brissett,Brissett,12.708695,23.0,4300,CHA@IND,IND,CHA,NaN,NaN,NaN,NaN,NaN,SF,16.9,3.93,19.77
159,69397-110321,SG,Romeo,Romeo Langford,Langford,12.237037,27.0,4300,LAC@BOS,BOS,LAC,NaN,NaN,NaN,NaN,NaN,SG,21.5,5.00,33.17
160,69397-111492,PF,Amir,Amir Coffey,Coffey,8.542857,21.0,4300,LAC@BOS,LAC,BOS,NaN,NaN,NaN,NaN,NaN,PF,21.6,5.03,28.07
161,69397-145303,SG,Skylar,Skylar Mays,Mays,7.181818,11.0,4300,ATL@CHI,ATL,CHI,NaN,NaN,NaN,NaN,NaN,SG,21.3,4.94,26.02
169,69397-41082,C,Damian,Damian Jones,Jones,11.600000,19.0,4200,DAL@SAC,SAC,DAL,NaN,NaN,NaN,NaN,NaN,C,15.8,3.76,15.78
178,69397-66091,PF,Cheick,Cheick Diallo,Diallo,11.900000,2.0,4000,NY@DET,DET,NY,NaN,NaN,NaN,NaN,NaN,PF,17.8,4.45,19.24
179,69397-157804,SG,Keon,Keon Johnson,Johnson,8.025000,8.0,4000,LAC@BOS,LAC,BOS,NaN,NaN,NaN,NaN,NaN,SG,16.7,4.18,17.65
184,69397-9957,PF/C,Serge,Serge Ibaka,Ibaka,13.246666,15.0,4000,LAC@BOS,LAC,BOS,NaN,NaN,NaN,NaN,NaN,PF/C,22.0,5.50,19.28
188,69397-145342,SG,Cassius,Cassius Stanley,Stanley,22.100000,1.0,4000,NY@DET,DET,NY,NaN,NaN,NaN,NaN,NaN,SG,16.6,4.14,20.37
190,69397-12351,C/PF,Derrick,Derrick Favors,Favors,14.504000,25.0,3900,OKC@PHO,OKC,PHO,NaN,NaN,NaN,NaN,NaN,PF/C,19.2,4.93,16.79
191,69397-112709,SG/SF,Javonte,Javonte Green,Green,14.811111,27.0,3900,ATL@CHI,CHI,ATL,NaN,NaN,NaN,NaN,NaN,SG/SF,19.0,4.88,26.96
199,69397-15947,SG,Reggie,Reggie Bullock,Bullock,10.781482,27.0,3800,DAL@SAC,DAL,SAC,NaN,NaN,NaN,NaN,NaN,SG,18.6,4.91,27.44
201,69397-157849,SG,Ayo,Ayo Dosunmu,Dosunmu,11.233333,27.0,3800,ATL@CHI,CHI,ATL,NaN,NaN,NaN,NaN,NaN,SG,18.2,4.78,26.04
204,69397-58081,PG,Tyus,Tyus Jones,Jones,18.470588,34.0,3800,LAL@MEM,MEM,LAL,NaN,NaN,NaN,NaN,NaN,PG,21.1,5.55,22.86
206,69397-9956,SG,Wayne,Wayne Ellington,Ellington,11.065385,26.0,3800,LAL@MEM,LAL,MEM,NaN,NaN,NaN,NaN,NaN,SG,20.9,5.51,32.68
210,69397-9577,PF/SF,Rudy,Rudy Gay,Gay,16.342105,19.0,3800,UTA@POR,UTA,POR,NaN,NaN,NaN,NaN,NaN,SF/PF,20.8,5.46,22.05
211,69397-159096,SG,Chaundee,Chaundee Brown,Brown,8.066667,3.0,3800,ATL@CHI,ATL,CHI,NaN,NaN,NaN,NaN,NaN,SG,23.4,6.14,30.41
214,69397-9660,C,Dwight,Dwight Howard,Howard,15.637037,27.0,3800,LAL@MEM,LAL,MEM,NaN,NaN,NaN,NaN,NaN,C,22.8,5.99,19.69
215,69397-17894,C,Mike,Mike Muscala,Muscala,14.734616,26.0,3800,OKC@PHO,OKC,PHO,NaN,NaN,NaN,NaN,NaN,C,15.7,4.12,14.58
216,69397-12369,SF,Lance,Lance Stephenson,Stephenson,7.900000,4.0,3700,ATL@CHI,ATL,CHI,NaN,NaN,NaN,NaN,NaN,SF,16.1,4.34,19.99
220,69397-16604,SF/SG,Justin,Justin Holiday,Holiday,17.314285,28.0,3700,CHA@IND,IND,CHA,NaN,NaN,NaN,NaN,NaN,SG/SF,19.0,5.14,27.69
221,69397-58084,SF,Justise,Justise Winslow,Winslow,8.728000,25.0,3700,LAC@BOS,LAC,BOS,NaN,NaN,NaN,NaN,NaN,SF,21.4,5.79,21.30
223,69397-84717,PG/SG,Anfernee,Anfernee Simons,Simons,18.462070,29.0,3700,UTA@POR,POR,UTA,NaN,NaN,NaN,NaN,NaN,PG/SG,26.1,7.06,32.24
230,69397-17517,SF/SG,Tony,Tony Snell,Snell,5.658333,24.0,3600,UTA@POR,POR,UTA,NaN,NaN,NaN,NaN,NaN,SG/SF,16.2,4.50,27.25
232,69397-161491,SF,Malcolm,Malcolm Hill,Hill,5.300000,2.0,3600,ATL@CHI,ATL,CHI,NaN,NaN,NaN,NaN,NaN,SF,24.3,6.75,26.59
235,69397-84724,SG,Landry,Landry Shamet,Shamet,13.343750,32.0,3600,OKC@PHO,PHO,OKC,NaN,NaN,NaN,NaN,NaN,SG,18.0,4.99,24.90
308,69397-110346,PF/C,Isaiah,Isaiah Roby,Roby,11.873334,15.0,3500,OKC@PHO,OKC,PHO,NaN,NaN,NaN,NaN,NaN,PF/C,24.2,6.91,27.31

In [13]:
df_fd['FPPG'] = df_fd.FP
dropped_cols = ['FP', 'Value', 'Min']#, 'expts', 'rkpts', 'vlpts', 'new_expts']
df_fd.drop(dropped_cols, axis=1, inplace=True)
df_fd

/tmp/ipykernel_5869/3747236435.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fd['FPPG'] = df_fd.FP
/home/michael/.local/share/virtualenvs/fan_fact-icAuygf9/lib/python3.8/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
0,69397-9488,SF/PF,LeBron,LeBron James,James,52.8,23.0,11200,LAL@MEM,LAL,MEM,GTD,Abdomen,NaN,NaN,NaN,SF/PF
4,69397-9642,PG,Russell,Russell Westbrook,Westbrook,44.3,35.0,9800,LAL@MEM,LAL,MEM,NaN,NaN,NaN,NaN,NaN,PG
5,69397-84671,PG,Trae,Trae Young,Young,50.0,30.0,9700,ATL@CHI,ATL,CHI,NaN,NaN,NaN,NaN,NaN,PG
7,69397-145485,PG,LaMelo,LaMelo Ball,Ball,44.9,29.0,9400,CHA@IND,CHA,IND,NaN,NaN,NaN,NaN,NaN,PG
9,69397-84680,SG/PG,Shai,Shai Gilgeous-Alexander,Gilgeous-Alexander,42.1,30.0,9300,OKC@PHO,OKC,PHO,NaN,NaN,NaN,NaN,NaN,PG/SG
10,69397-9714,SG/SF,DeMar,DeMar DeRozan,DeRozan,42.6,28.0,9200,ATL@CHI,CHI,ATL,NaN,NaN,NaN,NaN,NaN,SG/SF
11,69397-40203,C,Rudy,Rudy Gobert,Gobert,42.9,33.0,9100,UTA@POR,UTA,POR,NaN,NaN,NaN,NaN,NaN,C
12,69397-20848,PG,Damian,Damian Lillard,Lillard,47.7,27.0,9000,UTA@POR,POR,UTA,NaN,NaN,NaN,NaN,NaN,PG
13,69397-63122,PF/C,Kristaps,Kristaps Porzingis,Porzingis,47.8,24.0,8900,DAL@SAC,DAL,SAC,NaN,NaN,NaN,NaN,NaN,PF/C
14,69397-67026,SF/SG,Jaylen,Jaylen Brown,Brown,42.4,20.0,8800,LAC@BOS,BOS,LAC,NaN,NaN,NaN,NaN,NaN,SG/SF
15,69397-42669,PF/C,Julius,Julius Randle,Randle,40.2,34.0,8700,NY@DET,NY,DET,NaN,NaN,NaN,NaN,NaN,PF/C
16,69397-110344,PG,Ja,Ja Morant,Morant,42.0,23.0,8600,LAL@MEM,MEM,LAL,NaN,NaN,NaN,NaN,NaN,PG
17,69397-40783,SG/PG,Zach,Zach LaVine,LaVine,41.6,29.0,8600,ATL@CHI,CHI,ATL,NaN,NaN,NaN,NaN,NaN,PG/SG
20,69397-59358,PF/C,Domantas,Domantas Sabonis,Sabonis,44.4,33.0,8400,CHA@IND,IND,CHA,NaN,NaN,NaN,NaN,NaN,PF/C
21,69397-14514,C,Nikola,Nikola Vucevic,Vucevic,42.1,24.0,8300,ATL@CHI,CHI,ATL,NaN,NaN,NaN,NaN,NaN,C
24,69397-9623,PG,Chris,Chris Paul,Paul,37.4,33.0,8200,OKC@PHO,PHO,OKC,NaN,NaN,NaN,NaN,NaN,PG
27,69397-145337,PG/SG,Tyrese,Tyrese Haliburton,Haliburton,34.1,33.0,8100,DAL@SAC,SAC,DAL,NaN,NaN,NaN,NaN,NaN,PG/SG
29,69397-55059,C,Clint,Clint Capela,Capela,39.0,31.0,8000,ATL@CHI,ATL,CHI,NaN,NaN,NaN,NaN,NaN,C
30,69397-14507,PG,Kemba,Kemba Walker,Walker,31.5,23.0,7900,NY@DET,NY,DET,NaN,NaN,NaN,NaN,NaN,PG
34,69397-16359,PG/SG,Malcolm,Malcolm Brogdon,Brogdon,36.0,26.0,7800,CHA@IND,IND,CHA,GTD,Achilles,NaN,NaN,NaN,PG/SG
36,69397-58460,SG,Devin,Devin Booker,Booker,40.2,26.0,7600,OKC@PHO,PHO,OKC,NaN,NaN,NaN,NaN,NaN,SG
37,69397-145334,SG,Desmond,Desmond Bane,Bane,30.8,35.0,7600,LAL@MEM,MEM,LAL,NaN,NaN,NaN,NaN,NaN,SG
39,69397-84690,PG/SG,Jalen,Jalen Brunson,Brunson,36.0,32.0,7400,DAL@SAC,DAL,SAC,NaN,NaN,NaN,NaN,NaN,PG/SG
40,69397-80810,PG,De'Aaron,De'Aaron Fox,Fox,37.1,31.0,7400,DAL@SAC,SAC,DAL,NaN,NaN,NaN,NaN,NaN,PG
41,69397-12366,SF/SG,Gordon,Gordon Hayward,Hayward,32.1,34.0,7300,CHA@IND,CHA,IND,NaN,NaN,NaN,NaN,NaN,SG/SF
42,69397-58253,C/PF,Myles,Myles Turner,Turner,37.7,33.0,7200,CHA@IND,IND,CHA,NaN,NaN,NaN,NaN,NaN,PF/C
43,69397-9575,PG,Mike,Mike Conley,Conley,29.5,30.0,7100,UTA@POR,UTA,POR,NaN,NaN,NaN,NaN,NaN,PG
44,69397-9453,PF/C,Al,Al Horford,Horford,32.3,25.0,7000,LAC@BOS,BOS,LAC,NaN,NaN,NaN,NaN,NaN,PF/C
47,69397-84683,PF/C,Jaren,Jaren Jackson,Jackson,33.8,34.0,6700,LAL@MEM,MEM,LAL,NaN,NaN,NaN,NaN,NaN,PF/C
48,69397-23798,SG/SF,Caris,Caris LeVert,LeVert,37.0,26.0,6600,CHA@IND,IND,CHA,NaN,NaN,NaN,NaN,NaN,SG/SF
50,69397-14512,PF/SF,Marcus,Marcus Morris,Morris,26.5,14.0,6500,LAC@BOS,LAC,BOS,NaN,NaN,NaN,NaN,NaN,SF/PF
51,69397-84708,PF/C,Robert,Robert Williams,Williams,31.2,26.0,6500,LAC@BOS,BOS,LAC,NaN,NaN,NaN,NaN,NaN,PF/C
52,69397-110343,SF,Nassir,Nassir Little,Little,27.8,28.0,6500,UTA@POR,POR,UTA,NaN,NaN,NaN,NaN,NaN,SF
53,69397-9508,SF/PF,Carmelo,Carmelo Anthony,Anthony,24.6,35.0,6500,LAL@MEM,LAL,MEM,NaN,NaN,NaN,NaN,NaN,SF/PF
54,69397-42677,SG/PG,Terry,Terry Rozier,Rozier,33.0,26.0,6400,CHA@IND,CHA,IND,NaN,NaN,NaN,NaN,NaN,PG/SG
57,69397-145328,SF,Saddiq,Saddiq Bey,Bey,35.3,32.0,6400,NY@DET,DET,NY,NaN,NaN,NaN,NaN,NaN,SF
59,69397-58153,SF/SG,Kelly,Kelly Oubre,Oubre,31.6,35.0,6300,CHA@IND,CHA,IND,NaN,NaN,NaN,NaN,NaN,SG/SF
60,69397-15946,SF/PF,Harrison,Harrison Barnes,Barnes,30.1,30.0,6200,DAL@SAC,SAC,DAL,NaN,NaN,NaN,NaN,NaN,SF/PF
61,69397-23665,SG/SF,Buddy,Buddy Hield,Hield,21.4,35.0,6200,DAL@SAC,SAC,DAL,NaN,NaN,NaN,NaN,NaN,SG/SF
64,69397-145335,PG/SG,Payton,Payton Pritchard,Pritchard,21.1,28.0,6200,LAC@BOS,BOS,LAC,NaN,NaN,NaN,NaN,NaN,PG/SG
65,69397-16376,SF/SG,Dorian,Dorian Finney-Smith,Finney-Smith,26.5,32.0,6200,DAL@SAC,DAL,SAC,NaN,NaN,NaN,NaN,NaN,SG/SF
66,69397-20640,PG/SG,Jordan,Jordan Clarkson,Clarkson,29.8,33.0,6100,UTA@POR,UTA,POR,NaN,NaN,NaN,NaN,NaN,PG/SG
68,69397-16293,SF/SG,Norman,Norman Powell,Powell,32.8,29.0,6100,UTA@POR,POR,UTA,NaN,NaN,NaN,NaN,NaN,SG/SF
70,69397-84699,SG/SF,Hamidou,Hamidou Diallo,Diallo,33.4,25.0,6000,NY@DET,DET,NY,NaN,NaN,NaN,NaN,NaN,SG/SF
71,69397-23447,C/PF,Richaun,Richaun Holmes,Holmes,28.4,25.0,6000,DAL@SAC,SAC,DAL,NaN,NaN,NaN,NaN,NaN,PF/C
75,69397-23670,SG/PG,Marcus,Marcus Smart,Smart,31.6,32.0,5800,LAC@BOS,BOS,LAC,GTD,Hand,NaN,NaN,NaN,PG/SG
82,69397-111273,SF/SG,Luguentz,Luguentz Dort,Dort,26.8,31.0,5600,OKC@PHO,OKC,PHO,NaN,NaN,NaN,NaN,NaN,SG/SF
83,69397-14530,SF/PF,Bojan,Bojan Bogdanovic,Bogdanovic,26.3,33.0,5600,UTA@POR,UTA,POR,NaN,NaN,NaN,NaN,NaN,SF/PF
85,69397-110315,SG/SF,Terance,Terance Mann,Mann,25.7,33.0,5600,LAC@BOS,LAC,BOS,NaN,NaN,NaN,NaN,NaN,SG/SF
86,69397-110326,PG/SG,Coby,Coby White,White,23.4,13.0,5600,ATL@CHI,CHI,ATL,NaN,NaN,NaN,NaN,NaN,PG/SG
87,69397-23096,SF/SG,Evan,Evan Fournier,Fournier,23.1,34.0,5500,NY@DET,NY,DET,NaN,NaN,NaN,NaN,NaN,SG/SF
88,69397-12355,SG/PG,Eric,Eric Bledsoe,Bledsoe,30.6,34.0,5500,LAC@BOS,LAC,BOS,NaN,NaN,NaN,NaN,NaN,PG/SG
90,69397-84709,C,Mitchell,Mitchell Robinson,Robinson,26.1,31.0,5500,NY@DET,NY,DET,NaN,NaN,NaN,NaN,NaN,C
91,69397-15590,C,Mason,Mason Plumlee,Plumlee,26.0,26.0,5500,CHA@IND,CHA,IND,NaN,NaN,NaN,NaN,NaN,C
92,69397-110357,SF/SG,RJ,RJ Barrett,Barrett,25.1,27.0,5500,NY@DET,NY,DET,NaN,NaN,NaN,NaN,NaN,SG/SF
94,69397-80824,PG,Frank,Frank Jackson,Jackson,30.1,32.0,5500,NY@DET,DET,NY,NaN,NaN,NaN,NaN,NaN,PG
97,69397-110339,SG/SF,Cam,Cam Reddish,Reddish,31.4,29.0,5400,ATL@CHI,ATL,CHI,NaN,NaN,NaN,NaN,NaN,SG/SF
99,69397-48567,PG/SG,Cameron,Cameron Payne,Payne,24.0,28.0,5400,OKC@PHO,PHO,OKC,NaN,NaN,NaN,NaN,NaN,PG/SG
102,69397-157828,SF,Chris,Chris Duarte,Duarte,20.1,32.0,5300,CHA@IND,IND,CHA,NaN,NaN,NaN,NaN,NaN,SF
103,69397-70827,C,Ivica,Ivica Zubac,Zubac,26.6,34.0,5300,LAC@BOS,LAC,BOS,NaN,NaN,NaN,NaN,NaN,C
104,69397-84670,SF/PF,Mikal,Mikal Bridges,Bridges,26.7,33.0,5300,OKC@PHO,PHO,OKC,NaN,NaN,NaN,NaN,NaN,SF/PF
105,69397-110316,SF,Cameron,Cameron Johnson,Johnson,27.3,33.0,5300,OKC@PHO,PHO,OKC,NaN,NaN,NaN,NaN,NaN,SF
107,69397-145348,SG/PG,Immanuel,Immanuel Quickley,Quickley,21.5,30.0,5300,NY@DET,NY,DET,NaN,NaN,NaN,NaN,NaN,PG/SG
108,69397-9739,C,JaVale,JaVale McGee,McGee,36.0,33.0,5200,OKC@PHO,PHO,OKC,NaN,NaN,NaN,NaN,NaN,C
109,69397-157829,SG,Aaron,Aaron Wiggins,Wiggins,22.3,15.0,5200,OKC@PHO,OKC,PHO,NaN,NaN,NaN,NaN,NaN,SG
110,69397-14510,SG/SF,Alec,Alec Burks,Burks,23.4,33.0,5200,NY@DET,NY,DET,NaN,NaN,NaN,NaN,NaN,SG/SF
111,69397-110351,SG/PG,Cody,Cody Martin,Martin,22.6,30.0,5200,CHA@IND,CHA,IND,NaN,NaN,NaN,NaN,NaN,PG/SG
112,69397-23716,SF/PF,Kyle,Kyle Anderson,Anderson,28.9,31.0,5100,LAL@MEM,MEM,LAL,NaN,NaN,NaN,NaN,NaN,SF/PF
122,69397-116340,SG/SF,Terence,Terence Davis,Davis,15.8,22.0,4800,DAL@SAC,SAC,DAL,NaN,NaN,NaN,NaN,NaN,SG/SF
123,69397-23169,C,Steven,Steven Adams,Adams,24.6,35.0,4800,LAL@MEM,MEM,LAL,NaN,NaN,NaN,NaN,NaN,C
126,69397-110350,PF,Jalen,Jalen McDaniels,McDaniels,24.0,28.0,4800,CHA@IND,CHA,IND,NaN,NaN,NaN,NaN,NaN,PF
128,69397-16233,SF/SG,Josh,Josh Richardson,Richardson,18.9,22.0,4800,LAC@BOS,BOS,LAC,NaN,NaN,NaN,NaN,NaN,SG/SF
129,69397-145322,PF/C,Jalen,Jalen Smith,Smith,17.3,12.0,4800,OKC@PHO,PHO,OKC,NaN,NaN,NaN,NaN,NaN,PF/C
131,69397-145325,SG,Josh,Josh Green,Green,19.3,18.0,4800,DAL@SAC,DAL,SAC,NaN,NaN,NaN,NaN,NaN,SG
133,69397-157807,C,Luka,Luka Garza,Garza,23.3,20.0,4700,NY@DET,DET,NY,NaN,NaN,NaN,NaN,NaN,C
137,69397-110337,SG/SF,Talen,Talen Horton-Tucker,Horton-Tucker,24.7,19.0,4700,LAL@MEM,LAL,MEM,NaN,NaN,NaN,NaN,NaN,SG/SF
139,69397-80816,SG,Malik,Malik Monk,Monk,23.5,30.0,4700,LAL@MEM,LAL,MEM,NaN,NaN,NaN,NaN,NaN,SG
140,69397-66046,SG/SF,Luke,Luke Kennard,Kennard,25.2,33.0,4700,LAC@BOS,LAC,BOS,NaN,NaN,NaN,NaN,NaN,SG/SF
141,69397-145536,PG,Theo,Theo Maledon,Maledon,17.7,17.0,4600,OKC@PHO,OKC,PHO,NaN,NaN,NaN,NaN,NaN,PG
144,69397-110353,PF,Brandon,Brandon Clarke,Clarke,17.7,21.0,4600,LAL@MEM,MEM,LAL,NaN,NaN,NaN,NaN,NaN,PF
146,69397-16196,C/PF,Dwight,Dwight Powell,Powell,20.4,33.0,4500,DAL@SAC,DAL,SAC,NaN,NaN,NaN,NaN,NaN,PF/C
148,69397-40262,SG,Sterling,Sterling Brown,Brown,16.0,25.0,4500,DAL@SAC,DAL,SAC,NaN,NaN,NaN,NaN,NaN,SG
149,69397-18338,SF/PF,Royce,Royce O'Neale,O'Neale,22.0,31.0,4500,UTA@POR,UTA,POR,NaN,NaN,NaN,NaN,NaN,SF/PF
151,69397-59318,SG/SF,Joe,Joe Ingles,Ingles,23.8,33.0,4500,UTA@POR,UTA,POR,NaN,NaN,NaN,NaN,NaN,SG/SF
155,69397-85305,SF,Kenrich,Kenrich Williams,Williams,26.6,30.0,4400,OKC@PHO,OKC,PHO,NaN,NaN,NaN,NaN,NaN,SF
157,69397-117283,SF,Oshae,Oshae Brissett,Brissett,16.9,23.0,4300,CHA@IND,IND,CHA,NaN,NaN,NaN,NaN,NaN,SF
159,69397-110321,SG,Romeo,Romeo Langford,Langford,21.5,27.0,4300,LAC@BOS,BOS,LAC,NaN,NaN,NaN,NaN,NaN,SG
160,69397-111492,PF,Amir,Amir Coffey,Coffey,21.6,21.0,4300,LAC@BOS,LAC,BOS,NaN,NaN,NaN,NaN,NaN,PF
161,69397-145303,SG,Skylar,Skylar Mays,Mays,21.3,11.0,4300,ATL@CHI,ATL,CHI,NaN,NaN,NaN,NaN,NaN,SG
169,69397-41082,C,Damian,Damian Jones,Jones,15.8,19.0,4200,DAL@SAC,SAC,DAL,NaN,NaN,NaN,NaN,NaN,C
178,69397-66091,PF,Cheick,Cheick Diallo,Diallo,17.8,2.0,4000,NY@DET,DET,NY,NaN,NaN,NaN,NaN,NaN,PF
179,69397-157804,SG,Keon,Keon Johnson,Johnson,16.7,8.0,4000,LAC@BOS,LAC,BOS,NaN,NaN,NaN,NaN,NaN,SG
184,69397-9957,PF/C,Serge,Serge Ibaka,Ibaka,22.0,15.0,4000,LAC@BOS,LAC,BOS,NaN,NaN,NaN,NaN,NaN,PF/C
188,69397-145342,SG,Cassius,Cassius Stanley,Stanley,16.6,1.0,4000,NY@DET,DET,NY,NaN,NaN,NaN,NaN,NaN,SG
190,69397-12351,C/PF,Derrick,Derrick Favors,Favors,19.2,25.0,3900,OKC@PHO,OKC,PHO,NaN,NaN,NaN,NaN,NaN,PF/C
191,69397-112709,SG/SF,Javonte,Javonte Green,Green,19.0,27.0,3900,ATL@CHI,CHI,ATL,NaN,NaN,NaN,NaN,NaN,SG/SF
199,69397-15947,SG,Reggie,Reggie Bullock,Bullock,18.6,27.0,3800,DAL@SAC,DAL,SAC,NaN,NaN,NaN,NaN,NaN,SG
201,69397-157849,SG,Ayo,Ayo Dosunmu,Dosunmu,18.2,27.0,3800,ATL@CHI,CHI,ATL,NaN,NaN,NaN,NaN,NaN,SG
204,69397-58081,PG,Tyus,Tyus Jones,Jones,21.1,34.0,3800,LAL@MEM,MEM,LAL,NaN,NaN,NaN,NaN,NaN,PG
206,69397-9956,SG,Wayne,Wayne Ellington,Ellington,20.9,26.0,3800,LAL@MEM,LAL,MEM,NaN,NaN,NaN,NaN,NaN,SG
210,69397-9577,PF/SF,Rudy,Rudy Gay,Gay,20.8,19.0,3800,UTA@POR,UTA,POR,NaN,NaN,NaN,NaN,NaN,SF/PF
211,69397-159096,SG,Chaundee,Chaundee Brown,Brown,23.4,3.0,3800,ATL@CHI,ATL,CHI,NaN,NaN,NaN,NaN,NaN,SG
214,69397-9660,C,Dwight,Dwight Howard,Howard,22.8,27.0,3800,LAL@MEM,LAL,MEM,NaN,NaN,NaN,NaN,NaN,C
215,69397-17894,C,Mike,Mike Muscala,Muscala,15.7,26.0,3800,OKC@PHO,OKC,PHO,NaN,NaN,NaN,NaN,NaN,C
216,69397-12369,SF,Lance,Lance Stephenson,Stephenson,16.1,4.0,3700,ATL@CHI,ATL,CHI,NaN,NaN,NaN,NaN,NaN,SF
220,69397-16604,SF/SG,Justin,Justin Holiday,Holiday,19.0,28.0,3700,CHA@IND,IND,CHA,NaN,NaN,NaN,NaN,NaN,SG/SF
221,69397-58084,SF,Justise,Justise Winslow,Winslow,21.4,25.0,3700,LAC@BOS,LAC,BOS,NaN,NaN,NaN,NaN,NaN,SF
223,69397-84717,PG/SG,Anfernee,Anfernee Simons,Simons,26.1,29.0,3700,UTA@POR,POR,UTA,NaN,NaN,NaN,NaN,NaN,PG/SG
230,69397-17517,SF/SG,Tony,Tony Snell,Snell,16.2,24.0,3600,UTA@POR,POR,UTA,NaN,NaN,NaN,NaN,NaN,SG/SF
232,69397-161491,SF,Malcolm,Malcolm Hill,Hill,24.3,2.0,3600,ATL@CHI,ATL,CHI,NaN,NaN,NaN,NaN,NaN,SF
235,69397-84724,SG,Landry,Landry Shamet,Shamet,18.0,32.0,3600,OKC@PHO,PHO,OKC,NaN,NaN,NaN,NaN,NaN,SG
308,69397-110346,PF/C,Isaiah,Isaiah Roby,Roby,24.2,15.0,3500,OKC@PHO,OKC,PHO,NaN,NaN,NaN,NaN,NaN,PF/C

df_fd.query('Nickname == "Gordon Hayward"')

In [14]:
df_fd.to_csv('data/nba/FD_proj.csv')

In [15]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [17]:
from pydfs_lineup_optimizer import Site, Sport, get_optimizer, PlayerFilter, AfterEachExposureStrategy, TeamStack, RandomFantasyPointsStrategy

optimizer = get_optimizer(Site.FANDUEL, Sport.BASKETBALL)
optimizer.load_players_from_csv("data/nba/FD_proj.csv")

# p1 = optimizer.player_pool.get_player_by_name("Kevin Porter")
# p2 = optimizer.player_pool.get_player_by_name("Jarret Allen")
# p3 = optimizer.player_pool.get_player_by_name("Lonzo Ball")
# p4 = optimizer.player_pool.get_player_by_name("Evan Mobley")
# p5 = optimizer.player_pool.get_player_by_name("Isaiah Stewart")

# p1.max_exposure = 0.7
# p1.min_exposure = 0.3
# p2.max_exposure = 0.7 
# p2.min_exposure = 0.3
# p3.max_exposure = 0.65
# p3.min_exposure = 0.3
# p4.max_exposure = 0.65
# p4.min_exposure = 0.3
# p5.max_exposure = 0.6
# p5.min_exposure = 0.3     

# tm1 = 'ATL'
# tm2 = 'OKC'

# optimizer.add_stack(TeamStack(3, for_teams=[tm1,tm2], 
#                               max_exposure_per_team={tm1:0.6, tm2:0.55}))                                                                                                                                                                                                           

# optimizer.player_pool.remove_player('Zach LaVine')
# optimizer.set_max_repeating_players(5)
optimizer.set_fantasy_points_strategy(RandomFantasyPointsStrategy(max_deviation=0.1))
for lineup in optimizer.optimize(1, max_exposure=.5, exposure_strategy=AfterEachExposureStrategy):
    print(lineup)
optimizer.export('data/nba/fd_result.csv')

 1. PG      Damian Lillard                PG    POR            UTA@POR  47.7(46.467)   9000.0$
 2. PG      De'Aaron Fox                  PG    SAC            DAL@SAC  37.1(40.169)   7400.0$
 3. SG      Caris LeVert                  SF/SG IND            CHA@IND  37.0(40.225)   6600.0$
 4. SG      Eric Bledsoe                  PG/SG LAC            LAC@BOS  30.6(33.135)   5500.0$
 5. SF      Hamidou Diallo                SF/SG DET            NY@DET   33.4(35.153)   6000.0$
 6. SF      Kyle Anderson                 PF/SF MEM            LAL@MEM  28.9(30.88)    5100.0$
 7. PF      Domantas Sabonis              C/PF  IND            CHA@IND  44.4(46.227)   8400.0$
 8. PF      Isaiah Roby                   C/PF  OKC            OKC@PHO  24.2(26.519)   3500.0$
 9. C       Nikola Vucevic                C     CHI            ATL@CHI  42.1(44.821)   8300.0$

Fantasy Points 325.40(343.60)
Salary 59800.00