In [1]:
from functions.nfl_clean_data import archive_files

archive_files()

In [3]:
import requests
from bs4 import BeautifulSoup as soup
import pandas as pd
import numpy as np
from functions.nfl_proj_scape import nfl_proj_scape

In [4]:
def get_spread_page():
    url = "https://rotogrinders.com/lineups/nfl"
    html = requests.get(url).text
    page = soup(html)
    return page
page = get_spread_page()

team_list = page.find_all("span", {"class": "shrt"})
teams = [i.text for i in team_list]
odds_list = page.find_all("a", {"href": "/nfl/odds"})
odds = [i.text for i in odds_list]
#teams.sort()
df_odds = dict(zip(teams,odds))
print(dict(sorted(df_odds.items(), key=lambda item: item[1])))

{'DET': '15.25', 'CHI': '15.25', 'HOU': '15.75', 'NYG': '16.75', 'JAC': '17.25', 'NYJ': '18.50', 'LVR': '19.25', 'ATL': '19.25', 'BAL': '20.25', 'PIT': '20.75', 'WAS': '21.25', 'CAR': '21.75', 'CLE': '23.25', 'CIN': '23.25', 'NOS': '24.00', 'MIN': '24.25', 'BUF': '24.25', 'LAR': '24.50', 'SEA': '25.25', 'SFO': '25.25', 'TEN': '26.25', 'LAC': '26.25', 'DEN': '26.75', 'ARI': '27.00', 'DAL': '27.25', 'TBB': '27.75', 'GBP': '27.75', 'KCC': '28.75'}

In [19]:
df_fd_temp = pd.read_csv('data/nfl/FanDuel-NFL-2021 ET-12 ET-12 ET-68179-players-list.csv')
df_fd = df_fd_temp.convert_dtypes()
df_fd.head()

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
0,68179-80001,RB,Austin,Austin Ekeler,Ekeler,19.341667,12,9200,NYG@LAC,LAC,NYG,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
1,68179-42104,RB,Alvin,Alvin Kamara,Kamara,17.75,8,9000,NO@NYJ,NO,NYJ,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
2,68179-62239,QB,Josh,Josh Allen,Allen,23.403333,12,8800,BUF@TB,BUF,TB,<NA>,<NA>,<NA>,<NA>,<NA>,QB
3,68179-53681,WR,Tyreek,Tyreek Hill,Hill,16.15,12,8700,LV@KC,KC,LV,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
4,68179-57439,QB,Patrick,Patrick Mahomes,Mahomes,21.196667,12,8500,LV@KC,KC,LV,<NA>,<NA>,<NA>,<NA>,<NA>,QB

In [20]:
df_teams = list(df_fd.Team.unique())
df_teams.sort()
print(df_teams)

['ATL', 'BAL', 'BUF', 'CAR', 'CIN', 'CLE', 'DAL', 'DEN', 'DET', 'HOU', 'JAC', 'KC', 'LAC', 'LV', 'NO', 'NYG', 'NYJ', 'SEA', 'SF', 'TB', 'TEN', 'WAS']

df_fd.head()

In [21]:
replace_dict = {"GBP":"GB", "KCC":"KC", "LVR":"LV", "NEP":"NE", "NOS":"NO", "SFO":"SF", "TBB":"TB"}
clean_teams = [replace_dict.get(item,item) for item in teams]
print(clean_teams)

['PIT', 'MIN', 'BAL', 'CLE', 'DAL', 'WAS', 'LV', 'KC', 'SEA', 'HOU', 'JAC', 'TEN', 'NO', 'NYJ', 'ATL', 'CAR', 'DET', 'DEN', 'NYG', 'LAC', 'SF', 'CIN', 'BUF', 'TB', 'CHI', 'GB', 'LAR', 'ARI']

In [22]:
df_odds = dict(zip(clean_teams, odds))
#print(df_odds)
print(dict(sorted(df_odds.items(), key=lambda item: item[1])))

{'DET': '15.25', 'CHI': '15.25', 'HOU': '15.75', 'NYG': '16.75', 'JAC': '17.25', 'NYJ': '18.50', 'LV': '19.25', 'ATL': '19.25', 'BAL': '20.25', 'PIT': '20.75', 'WAS': '21.25', 'CAR': '21.75', 'CLE': '23.25', 'CIN': '23.25', 'NO': '24.00', 'MIN': '24.25', 'BUF': '24.25', 'LAR': '24.50', 'SEA': '25.25', 'SF': '25.25', 'TEN': '26.25', 'LAC': '26.25', 'DEN': '26.75', 'ARI': '27.00', 'DAL': '27.25', 'TB': '27.75', 'GB': '27.75', 'KC': '28.75'}

In [23]:
stats_df = nfl_proj_scape()
stats_df.head()

          Nickname    FP Value
0       Josh Allen  22.0  2.49
1  Patrick Mahomes  21.6  2.54
2     Dak Prescott  21.0  2.59
3    Lamar Jackson  21.0  2.65
4   Justin Herbert  20.4  2.43

In [24]:
pd.set_option('display.max_rows', None)
df_fd_def = df_fd.query("Position == 'D'")
df_fd = df_fd.query("Position != 'D'")
df_fd = pd.merge(df_fd, stats_df, how='outer', on='Nickname')

In [25]:
df_fd.head(10)

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position,FP,Value
0,68179-80001,RB,Austin,Austin Ekeler,Ekeler,19.341667,12,9200,NYG@LAC,LAC,NYG,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX,18.4,2
1,68179-42104,RB,Alvin,Alvin Kamara,Kamara,17.75,8,9000,NO@NYJ,NO,NYJ,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX,17.4,1.94
2,68179-62239,QB,Josh,Josh Allen,Allen,23.403333,12,8800,BUF@TB,BUF,TB,<NA>,<NA>,<NA>,<NA>,<NA>,QB,22.0,2.49
3,68179-53681,WR,Tyreek,Tyreek Hill,Hill,16.15,12,8700,LV@KC,KC,LV,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX,15.1,1.73
4,68179-57439,QB,Patrick,Patrick Mahomes,Mahomes,21.196667,12,8500,LV@KC,KC,LV,<NA>,<NA>,<NA>,<NA>,<NA>,QB,21.6,2.54
5,68179-52442,RB,Joe,Joe Mixon,Mixon,17.666667,12,8500,SF@CIN,CIN,SF,Q,Illness,<NA>,<NA>,<NA>,RB/FLEX,15.7,1.85
6,68179-56018,WR,Deebo,Deebo Samuel,Samuel,18.627272,11,8500,SF@CIN,SF,CIN,Q,Groin,<NA>,<NA>,<NA>,WR/FLEX,8.6,1.01
7,68179-69189,QB,Justin,Justin Herbert,Herbert,23.481667,12,8400,NYG@LAC,LAC,NYG,<NA>,<NA>,<NA>,<NA>,<NA>,QB,20.4,2.43
8,68179-6498,QB,Tom,Tom Brady,Brady,23.670001,12,8200,BUF@TB,TB,BUF,<NA>,<NA>,<NA>,<NA>,<NA>,QB,19.9,2.43
9,68179-25079,WR,Stefon,Stefon Diggs,Diggs,13.941667,12,8200,BUF@TB,BUF,TB,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX,14.7,1.79

In [26]:
df_fd.FPPG = df_fd.FP
df_fd.dropna(axis=0, subset=['Salary'], inplace=True)

In [27]:
df_fd['FPPG'] = df_fd.FPPG.astype(float)

In [28]:
df_fd.drop(axis=1, labels=['FP','Value'], inplace=True)

In [29]:
df_fd = df_fd.append(df_fd_def)
df_fd = df_fd[df_fd.FPPG > 5.0]
df_fd.columns

Index(['Id', 'Position', 'First Name', 'Nickname', 'Last Name', 'FPPG',
       'Played', 'Salary', 'Game', 'Team', 'Opponent', 'Injury Indicator',
       'Injury Details', 'Tier', 'Unnamed: 14', 'Unnamed: 15',
       'Roster Position'],
      dtype='object')

In [30]:
df_fd

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
0,68179-80001,RB,Austin,Austin Ekeler,Ekeler,18.4,12,9200,NYG@LAC,LAC,NYG,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
1,68179-42104,RB,Alvin,Alvin Kamara,Kamara,17.4,8,9000,NO@NYJ,NO,NYJ,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
2,68179-62239,QB,Josh,Josh Allen,Allen,22.0,12,8800,BUF@TB,BUF,TB,<NA>,<NA>,<NA>,<NA>,<NA>,QB
3,68179-53681,WR,Tyreek,Tyreek Hill,Hill,15.1,12,8700,LV@KC,KC,LV,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
4,68179-57439,QB,Patrick,Patrick Mahomes,Mahomes,21.6,12,8500,LV@KC,KC,LV,<NA>,<NA>,<NA>,<NA>,<NA>,QB
5,68179-52442,RB,Joe,Joe Mixon,Mixon,15.7,12,8500,SF@CIN,CIN,SF,Q,Illness,<NA>,<NA>,<NA>,RB/FLEX
6,68179-56018,WR,Deebo,Deebo Samuel,Samuel,8.6,11,8500,SF@CIN,SF,CIN,Q,Groin,<NA>,<NA>,<NA>,WR/FLEX
7,68179-69189,QB,Justin,Justin Herbert,Herbert,20.4,12,8400,NYG@LAC,LAC,NYG,<NA>,<NA>,<NA>,<NA>,<NA>,QB
8,68179-6498,QB,Tom,Tom Brady,Brady,19.9,12,8200,BUF@TB,TB,BUF,<NA>,<NA>,<NA>,<NA>,<NA>,QB
9,68179-25079,WR,Stefon,Stefon Diggs,Diggs,14.7,12,8200,BUF@TB,BUF,TB,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
10,68179-31716,QB,Dak,Dak Prescott,Prescott,21.0,11,8100,DAL@WAS,DAL,WAS,<NA>,<NA>,<NA>,<NA>,<NA>,QB
11,68179-63115,QB,Lamar,Lamar Jackson,Jackson,21.0,11,7900,BAL@CLE,BAL,CLE,<NA>,<NA>,<NA>,<NA>,<NA>,QB
12,68179-30733,RB,Cordarrelle,Cordarrelle Patterson,Patterson,15.0,11,7800,ATL@CAR,ATL,CAR,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
13,68179-86631,WR,CeeDee,CeeDee Lamb,Lamb,12.9,11,7800,DAL@WAS,DAL,WAS,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
14,68179-55635,WR,Chris,Chris Godwin,Godwin,14.2,12,7700,BUF@TB,TB,BUF,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
15,68179-45565,QB,Taysom,Taysom Hill,Hill,18.6,8,7700,NO@NYJ,NO,NYJ,<NA>,<NA>,<NA>,<NA>,<NA>,QB
17,68179-52922,RB,Leonard,Leonard Fournette,Fournette,15.2,12,7600,BUF@TB,TB,BUF,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
18,68179-33076,TE,Travis,Travis Kelce,Kelce,13.4,12,7500,LV@KC,KC,LV,<NA>,<NA>,<NA>,<NA>,<NA>,TE/FLEX
19,68179-53562,RB,Nick,Nick Chubb,Chubb,13.9,9,7500,BAL@CLE,CLE,BAL,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
20,68179-22015,QB,Russell,Russell Wilson,Wilson,18.1,9,7500,SEA@HOU,SEA,HOU,<NA>,<NA>,<NA>,<NA>,<NA>,QB
22,68179-90933,RB,Antonio,Antonio Gibson,Gibson,14.3,12,7400,DAL@WAS,WAS,DAL,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
23,68179-14185,QB,Cam,Cam Newton,Newton,20.1,3,7400,ATL@CAR,CAR,ATL,<NA>,<NA>,<NA>,<NA>,<NA>,QB
25,68179-27050,WR,Tyler,Tyler Lockett,Lockett,12.0,12,7300,SEA@HOU,SEA,HOU,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
26,68179-21948,QB,Ryan,Ryan Tannehill,Tannehill,18.7,12,7300,JAC@TEN,TEN,JAC,<NA>,<NA>,<NA>,<NA>,<NA>,QB
27,68179-64401,RB,Saquon,Saquon Barkley,Barkley,13.8,8,7300,NYG@LAC,NYG,LAC,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
28,68179-33259,QB,Teddy,Teddy Bridgewater,Bridgewater,17.8,12,7200,DET@DEN,DEN,DET,<NA>,<NA>,<NA>,<NA>,<NA>,QB
30,68179-32384,WR,Mike,Mike Evans,Evans,11.5,12,7200,BUF@TB,TB,BUF,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
31,68179-85701,WR,Ja'Marr,Ja'Marr Chase,Chase,13.8,12,7200,SF@CIN,CIN,SF,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
32,68179-45859,QB,Derek,Derek Carr,Carr,16.9,12,7200,LV@KC,LV,KC,<NA>,<NA>,<NA>,<NA>,<NA>,QB
34,68179-72731,RB,Josh,Josh Jacobs,Jacobs,15.2,10,7100,LV@KC,LV,KC,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
35,68179-53331,QB,Taylor,Taylor Heinicke,Heinicke,17.0,12,7100,DAL@WAS,WAS,DAL,<NA>,<NA>,<NA>,<NA>,<NA>,QB
36,68179-63336,QB,Joe,Joe Burrow,Burrow,17.6,12,7100,SF@CIN,CIN,SF,<NA>,<NA>,<NA>,<NA>,<NA>,QB
37,68179-39793,TE,George,George Kittle,Kittle,14.1,9,7100,SF@CIN,SF,CIN,<NA>,<NA>,<NA>,<NA>,<NA>,TE/FLEX
38,68179-56250,WR,Terry,Terry McLaurin,McLaurin,11.4,12,7100,DAL@WAS,WAS,DAL,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
40,68179-11460,TE,Rob,Rob Gronkowski,Gronkowski,10.3,7,7000,BUF@TB,TB,BUF,<NA>,<NA>,<NA>,<NA>,<NA>,TE/FLEX
42,68179-52808,RB,Dontrell,Dontrell Hilliard,Hilliard,8.6,2,7000,JAC@TEN,TEN,JAC,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
43,68179-86687,WR,Marquise,Marquise Brown,Brown,11.6,11,7000,BAL@CLE,BAL,CLE,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
45,68179-52436,TE,Mark,Mark Andrews,Andrews,11.4,12,6900,BAL@CLE,BAL,CLE,<NA>,<NA>,<NA>,<NA>,<NA>,TE/FLEX
46,68179-38791,RB,Ezekiel,Ezekiel Elliott,Elliott,13.7,12,6900,DAL@WAS,DAL,WAS,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
47,68179-39829,WR,Mike,Mike Williams,Williams,12.9,12,6900,NYG@LAC,LAC,NYG,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
48,68179-6616,QB,Matt,Matt Ryan,Ryan,14.4,12,6800,ATL@CAR,ATL,CAR,<NA>,<NA>,<NA>,<NA>,<NA>,QB
50,68179-89981,WR,Tee,Tee Higgins,Higgins,12.3,10,6800,SF@CIN,CIN,SF,Q,Ankle,<NA>,<NA>,<NA>,WR/FLEX
52,68179-31001,WR,Amari,Amari Cooper,Cooper,10.2,10,6700,DAL@WAS,DAL,WAS,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
53,68179-54604,QB,Jimmy,Jimmy Garoppolo,Garoppolo,17.3,11,6700,SF@CIN,SF,CIN,<NA>,<NA>,<NA>,<NA>,<NA>,QB
54,68179-93541,RB,Javonte,Javonte Williams,Williams,15.5,12,6700,DET@DEN,DEN,DET,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
55,68179-57986,WR,Hunter,Hunter Renfrow,Renfrow,12.1,12,6700,LV@KC,LV,KC,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
57,68179-90406,QB,Zach,Zach Wilson,Wilson,15.8,8,6600,NO@NYJ,NYJ,NO,<NA>,<NA>,<NA>,<NA>,<NA>,QB
59,68179-89628,QB,Davis,Davis Mills,Mills,13.6,8,6600,SEA@HOU,HOU,SEA,<NA>,<NA>,<NA>,<NA>,<NA>,QB
63,68179-45229,RB,Kareem,Kareem Hunt,Hunt,11.0,7,6500,BAL@CLE,CLE,BAL,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
65,68179-87467,RB,Chuba,Chuba Hubbard,Hubbard,11.2,11,6500,ATL@CAR,CAR,ATL,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
66,68179-41535,QB,Baker,Baker Mayfield,Mayfield,15.9,11,6500,BAL@CLE,CLE,BAL,<NA>,<NA>,<NA>,<NA>,<NA>,QB
67,68179-52897,RB,Darrel,Darrel Williams,Williams,9.0,12,6500,LV@KC,KC,LV,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
68,68179-85741,RB,Clyde,Clyde Edwards-Helaire,Edwards-Helaire,11.3,7,6500,LV@KC,KC,LV,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
69,68179-29501,WR,Brandin,Brandin Cooks,Cooks,11.1,12,6500,SEA@HOU,HOU,SEA,Q,Back,<NA>,<NA>,<NA>,WR/FLEX
70,68179-14190,WR,Julio,Julio Jones,Jones,10.0,6,6500,JAC@TEN,TEN,JAC,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
71,68179-130288,RB,James,James Robinson,Robinson,13.1,11,6400,JAC@TEN,JAC,TEN,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
72,68179-38435,QB,Jared,Jared Goff,Goff,12.4,11,6400,DET@DEN,DET,DEN,<NA>,<NA>,<NA>,<NA>,<NA>,QB
73,68179-31394,WR,Jarvis,Jarvis Landry,Landry,11.1,8,6400,BAL@CLE,CLE,BAL,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
74,68179-85798,WR,Brandon,Brandon Aiyuk,Aiyuk,11.2,12,6400,SF@CIN,SF,CIN,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
75,68179-24920,RB,Devonta,Devonta Freeman,Freeman,11.4,11,6300,BAL@CLE,BAL,CLE,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
76,68179-90561,WR,Jerry,Jerry Jeudy,Jeudy,9.4,6,6300,DET@DEN,DEN,DET,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
78,68179-89951,QB,Trevor,Trevor Lawrence,Lawrence,14.9,12,6300,JAC@TEN,JAC,TEN,<NA>,<NA>,<NA>,<NA>,<NA>,QB
83,68179-52916,WR,Russell,Russell Gage,Gage,9.0,8,6200,ATL@CAR,ATL,CAR,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
84,68179-25410,QB,Mike,Mike Glennon,Glennon,13.3,2,6200,NYG@LAC,NYG,LAC,<NA>,<NA>,<NA>,<NA>,<NA>,QB
86,68179-63759,RB,Tony,Tony Pollard,Pollard,8.6,12,6100,DAL@WAS,DAL,WAS,Q,Foot,<NA>,<NA>,<NA>,RB/FLEX
87,68179-69956,WR,Michael,Michael Gallup,Gallup,8.4,5,6100,DAL@WAS,DAL,WAS,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
102,68179-57403,WR,Courtland,Courtland Sutton,Sutton,7.3,12,6000,DET@DEN,DEN,DET,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
103,68179-64585,TE,Dawson,Dawson Knox,Knox,6.6,10,6000,BUF@TB,BUF,TB,<NA>,<NA>,<NA>,<NA>,<NA>,TE/FLEX
152,68179-86080,TE,Kyle,Kyle Pitts,Pitts,9.9,12,5900,ATL@CAR,ATL,CAR,<NA>,<NA>,<NA>,<NA>,<NA>,TE/FLEX
153,68179-55830,RB,D'Onta,D'Onta Foreman,Foreman,8.6,4,5900,JAC@TEN,TEN,JAC,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
154,68179-40669,WR,Tyler,Tyler Boyd,Boyd,7.6,12,5900,SF@CIN,CIN,SF,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
155,68179-22288,WR,Cole,Cole Beasley,Beasley,8.1,12,5900,BUF@TB,BUF,TB,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
156,68179-71705,TE,Noah,Noah Fant,Fant,6.6,11,5800,DET@DEN,DEN,DET,<NA>,<NA>,<NA>,<NA>,<NA>,TE/FLEX
157,68179-11505,WR,Emmanuel,Emmanuel Sanders,Sanders,7.4,12,5800,BUF@TB,BUF,TB,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
162,68179-55042,TE,Dalton,Dalton Schultz,Schultz,7.1,12,5700,DAL@WAS,DAL,WAS,<NA>,<NA>,<NA>,<NA>,<NA>,TE/FLEX
163,68179-57091,WR,Tim,Tim Patrick,Patrick,7.2,12,5700,DET@DEN,DEN,DET,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
164,68179-27477,WR,Sterling,Sterling Shepard,Shepard,8.6,5,5700,NYG@LAC,NYG,LAC,Q,Quadriceps,<NA>,<NA>,<NA>,WR/FLEX
165,68179-64389,WR,Nick,Nick Westbrook-Ikhine,Westbrook-Ikhine,7.4,10,5700,JAC@TEN,TEN,JAC,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
166,68179-30635,RB,Mike,Mike Davis,Davis,5.4,12,5700,ATL@CAR,ATL,CAR,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
168,68179-40843,RB,Alex,Alex Collins,Collins,8.5,10,5600,SEA@HOU,SEA,HOU,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
169,68179-57342,WR,Tre'Quan,Tre'Quan Smith,Smith,7.9,7,5600,NO@NYJ,NO,NYJ,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
170,68179-62497,RB,David,David Johnson,Johnson,9.5,11,5500,SEA@HOU,HOU,SEA,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
171,68179-24755,WR,Jamison,Jamison Crowder,Crowder,10.4,9,5500,NO@NYJ,NYJ,NO,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
172,68179-71246,WR,Marquez,Marquez Callaway,Callaway,7.3,12,5500,NO@NYJ,NO,NYJ,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
173,68179-26251,WR,Robby,Robby Anderson,Anderson,7.2,12,5500,ATL@CAR,CAR,ATL,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
174,68179-70603,RB,Devin,Devin Singletary,Singletary,8.1,12,5500,BUF@TB,BUF,TB,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
175,68179-54244,WR,Kenny,Kenny Golladay,Golladay,7.8,9,5500,NYG@LAC,NYG,LAC,Q,Ribs,<NA>,<NA>,<NA>,WR/FLEX
176,68179-53303,RB,Matt,Matt Breida,Breida,6.8,5,5400,BUF@TB,BUF,TB,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
182,68179-85845,WR,Rashod,Rashod Bateman,Bateman,5.2,7,5400,BAL@CLE,BAL,CLE,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
184,68179-24641,WR,Sammy,Sammy Watkins,Watkins,5.3,9,5300,BAL@CLE,BAL,CLE,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
185,68179-43334,RB,J.D.,J.D. McKissic,McKissic,5.8,11,5300,DAL@WAS,WAS,DAL,Q,Concussion,<NA>,<NA>,<NA>,RB/FLEX
187,68179-57840,RB,Rashaad,Rashaad Penny,Penny,6.9,5,5300,SEA@HOU,SEA,HOU,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
189,68179-39580,RB,Devontae,Devontae Booker,Booker,5.6,11,5300,NYG@LAC,NYG,LAC,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
191,68179-71352,WR,Mecole,Mecole Hardman,Hardman,5.3,12,5300,LV@KC,KC,LV,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
192,68179-27338,RB,Rex,Rex Burkhead,Burkhead,8.4,9,5300,SEA@HOU,HOU,SEA,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
194,68179-53097,WR,Josh,Josh Reynolds,Reynolds,7.9,6,5300,DET@DEN,DET,DEN,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
195,68179-41872,TE,Evan,Evan Engram,Engram,5.7,10,5300,NYG@LAC,NYG,LAC,<NA>,<NA>,<NA>,<NA>,<NA>,TE/FLEX
199,68179-91426,WR,Donovan,Donovan Peoples-Jones,Peoples-Jones,7.7,8,5200,BAL@CLE,CLE,BAL,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
200,68179-60712,TE,Foster,Foster Moreau,Moreau,9.4,7,5200,LV@KC,LV,KC,<NA>,<NA>,<NA>,<NA>,<NA>,TE/FLEX
201,68179-64843,WR,Jalen,Jalen Guyton,Guyton,7.4,12,5200,NYG@LAC,LAC,NYG,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
202,68179-27229,RB,Ameer,Ameer Abdullah,Abdullah,5.7,12,5200,ATL@CAR,CAR,ATL,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
203,68179-70372,WR,Chester,Chester Rogers,Rogers,6.0,11,5200,JAC@TEN,TEN,JAC,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
207,68179-7761,TE,Jared,Jared Cook,Cook,7.0,12,5100,NYG@LAC,LAC,NYG,<NA>,<NA>,<NA>,<NA>,<NA>,TE/FLEX
208,68179-6739,WR,DeSean,DeSean Jackson,Jackson,5.2,10,5100,LV@KC,LV,KC,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
210,68179-93023,RB,Jermar,Jermar Jefferson,Jefferson,9.0,3,5100,DET@DEN,DET,DEN,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
212,68179-64496,WR,Olamide,Olamide Zaccheaus,Zaccheaus,6.5,11,5100,ATL@CAR,ATL,CAR,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
216,68179-40126,TE,Austin,Austin Hooper,Hooper,7.8,12,5000,BAL@CLE,CLE,BAL,<NA>,<NA>,<NA>,<NA>,<NA>,TE/FLEX
218,68179-63819,WR,Darius,Darius Slayton,Slayton,5.5,9,5000,NYG@LAC,NYG,LAC,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
221,68179-69276,WR,Bryan,Bryan Edwards,Edwards,6.5,12,5000,LV@KC,LV,KC,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
225,68179-70422,WR,Kalif,Kalif Raymond,Raymond,7.4,12,5000,DET@DEN,DET,DEN,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
234,68179-63050,RB,Ty,Ty Johnson,Johnson,10.5,12,4900,NO@NYJ,NYJ,NO,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
240,68179-57565,RB,Austin,Austin Walter,Walter,7.1,2,4800,NO@NYJ,NYJ,NO,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
244,68179-71031,WR,Lil'Jordan,Lil'Jordan Humphrey,Humphrey,6.1,4,4800,NO@NYJ,NO,NYJ,Q,Hamstring,<NA>,<NA>,<NA>,WR/FLEX
245,68179-52613,WR,Curtis,Curtis Samuel,Samuel,6.0,4,4800,DAL@WAS,WAS,DAL,Q,Groin,<NA>,<NA>,<NA>,WR/FLEX
254,68179-40726,RB,Godwin,Godwin Igwebuike,Igwebuike,8.3,8,4800,DET@DEN,DET,DEN,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
259,68179-57299,TE,Gerald,Gerald Everett,Everett,5.9,10,4800,SEA@HOU,SEA,HOU,<NA>,<NA>,<NA>,<NA>,<NA>,TE/FLEX
260,68179-71723,WR,Dez,Dez Fitzpatrick,Fitzpatrick,6.0,3,4700,JAC@TEN,TEN,JAC,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
264,68179-65724,RB,JaMycal,JaMycal Hasty,Hasty,8.0,6,4700,SF@CIN,SF,CIN,<NA>,<NA>,<NA>,<NA>,<NA>,RB/FLEX
269,68179-52495,WR,Braxton,Braxton Berrios,Berrios,6.6,12,4700,NO@NYJ,NYJ,NO,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
282,68179-45791,WR,Rashard,Rashard Higgins,Higgins,6.3,9,4700,BAL@CLE,CLE,BAL,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
284,68179-72453,WR,Denzel,Denzel Mims,Mims,8.5,6,4700,NO@NYJ,NYJ,NO,<NA>,<NA>,<NA>,<NA>,<NA>,WR/FLEX
343,68179-40977,TE,Ricky,Ricky Seals-Jones,Seals-Jones,5.9,7,4500,DAL@WAS,WAS,DAL,<NA>,<NA>,<NA>,<NA>,<NA>,TE/FLEX
214,68179-12542,D,New Orleans,New Orleans Saints,Saints,7.416667,12,5000,NO@NYJ,NO,NYJ,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
238,68179-12553,D,Carolina,Carolina Panthers,Panthers,6.916667,12,4800,ATL@CAR,CAR,ATL,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
267,68179-12534,D,Tennessee,Tennessee Titans,Titans,6.166667,12,4700,JAC@TEN,TEN,JAC,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
415,68179-12550,D,Seattle,Seattle Seahawks,Seahawks,5.5,12,4500,SEA@HOU,SEA,HOU,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
419,68179-12555,D,Baltimore,Baltimore Ravens,Ravens,5.333333,12,4500,BAL@CLE,BAL,CLE,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
594,68179-12531,D,Denver,Denver Broncos,Broncos,8.0,12,4400,DET@DEN,DEN,DET,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
606,68179-12530,D,Dallas,Dallas Cowboys,Cowboys,9.75,12,4200,DAL@WAS,DAL,WAS,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
620,68179-12529,D,Cleveland,Cleveland Browns,Browns,6.083333,12,4100,BAL@CLE,CLE,BAL,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
647,68179-12526,D,Buffalo,Buffalo Bills,Bills,9.583333,12,4000,BUF@TB,BUF,TB,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
709,68179-12549,D,San Francisco,San Francisco 49ers,49ers,6.5,12,3900,SF@CIN,SF,CIN,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
710,68179-12543,D,New York,New York Giants,Giants,6.166667,12,3800,NYG@LAC,NYG,LAC,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
711,68179-12551,D,Tampa Bay,Tampa Bay Buccaneers,Buccaneers,8.666667,12,3800,BUF@TB,TB,BUF,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
712,68179-12528,D,Cincinnati,Cincinnati Bengals,Bengals,6.75,12,3700,SF@CIN,CIN,SF,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
713,68179-12536,D,Kansas City,Kansas City Chiefs,Chiefs,6.666667,12,3700,LV@KC,KC,LV,<NA>,<NA>,<NA>,<NA>,<NA>,DEF
716,68179-12556,D,Houston,Houston Texans,Texans,5.25,12,3400,SEA@HOU,HOU,SEA,<NA>,<NA>,<NA>,<NA>,<NA>,DEF

In [31]:
df_fd.to_csv('data/nfl/FDprojections.csv')

In [37]:
from pydfs_lineup_optimizer import Site, Sport, get_optimizer, PlayerFilter, AfterEachExposureStrategy, TeamStack

optimizer = get_optimizer(Site.FANDUEL, Sport.FOOTBALL)
optimizer.load_players_from_csv("data/nfl/FDprojections.csv")
optimizer.restrict_positions_for_opposing_team(['D'], ['QB', 'RB', 'WR', 'TE', 'FLEX']),
optimizer.add_stack(TeamStack(2, for_positions=['QB', 'WR'], for_teams=['TB','KC','DAL']))
#optimizer.add_stack(TeamStack(3, for_teams=['TB', 'LAR', 'Cx_IN']))
for lineup in optimizer.optimize(10, max_exposure=0.6, exposure_strategy=AfterEachExposureStrategy):
    print(lineup)
optimizer.export('data/nfl/fd_result.csv')

/home/michael/.local/share/virtualenvs/fan_fact-icAuygf9/lib/python3.8/site-packages/pydfs_lineup_optimizer/utils.py:156: DeprecationWarning: available_teams will be removed in version 3.7, use player_pool.available_teams instead
  warnings.warn(text, DeprecationWarning)
/home/michael/.local/share/virtualenvs/fan_fact-icAuygf9/lib/python3.8/site-packages/pydfs_lineup_optimizer/utils.py:156: DeprecationWarning: available_teams will be removed in version 3.7, use player_pool.available_teams instead
  warnings.warn(text, DeprecationWarning)
/home/michael/.local/share/virtualenvs/fan_fact-icAuygf9/lib/python3.8/site-packages/pydfs_lineup_optimizer/utils.py:156: DeprecationWarning: available_teams will be removed in version 3.7, use player_pool.available_teams instead
  warnings.warn(text, DeprecationWarning)

 1. QB      Patrick Mahomes               QB    KC             LV@KC    21.6           8500.0$
 2. RB      Javonte Williams              RB    DEN            DET@DEN  15.5           6700.0$
 3. RB      Josh Jacobs                   RB    LV             LV@KC    15.2           7100.0$
 4. WR      Ja'Marr Chase                 WR    CIN            SF@CIN   13.8           7200.0$
 5. WR      Jamison Crowder               WR    NYJ            NO@NYJ   10.4           5500.0$
 6. WR      Tyreek Hill                   WR    KC             LV@KC    15.1           8700.0$
 7. TE      George Kittle                 TE    SF             SF@CIN   14.1           7100.0$
 8. FLEX    Ty Johnson                    RB    NYJ            NO@NYJ   10.5           4900.0$
 9. DEF     Dallas Cowboys                D     DAL            DAL@WAS  9.75           4200.0$

Fantasy Points 125.95
Salary 59900.00

 1. QB      Tom Brady                     QB    TB             BUF@TB   19.9           8200.0$
 2. RB      Austin Ekeler                 RB    LAC            NYG@LAC  18.4           9200.0$
 3. RB      James Robinson                RB    JAC            JAC@TEN  13.1           6400.0$
 4. WR      Chris Godwin                  WR    TB             BUF@TB   14.2           7700.0$
 5. WR      Denzel Mims                   WR    NYJ            NO@NYJ   8.5            4700.0$
 6. WR      Mike Williams                 WR    LAC            NYG@LAC  12.9           6900.0$
 7. TE      Foster Moreau                 TE    LV             LV@KC    9.4            5200.0$
 8. FLEX    Leonard Fournette             RB    TB             BUF@TB   15.2           7600.0$
 9. DEF     Tampa Bay Buccaneers          D     TB             BUF@TB   8.667          3800.0$

Fantasy Points 120.27
Salary 59700.00

 1. QB      Tom Brady                     QB    TB             BUF@TB   19.9           8200.0$
 2. RB      Javonte Williams              RB    DEN            DET@DEN  15.5           6700.0$
 3. RB      Josh Jacobs                   RB    LV             LV@KC    15.2           7100.0$
 4. WR      Chris Godwin                  WR    TB             BUF@TB   14.2           7700.0$
 5. WR      Ja'Marr Chase                 WR    CIN            SF@CIN   13.8           7200.0$
 6. WR      Mike Williams                 WR    LAC            NYG@LAC  12.9           6900.0$
 7. TE      George Kittle                 TE    SF             SF@CIN   14.1           7100.0$
 8. FLEX    Ty Johnson                    RB    NYJ            NO@NYJ   10.5           4900.0$
 9. DEF     Dallas Cowboys                D     DAL            DAL@WAS  9.75           4200.0$

Fantasy Points 125.85
Salary 60000.00

 1. QB      Patrick Mahomes               QB    KC             LV@KC    21.6           8500.0$
 2. RB      Austin Ekeler                 RB    LAC            NYG@LAC  18.4           9200.0$
 3. RB      Cordarrelle Patterson         RB    ATL            ATL@CAR  15.0           7800.0$
 4. WR      Denzel Mims                   WR    NYJ            NO@NYJ   8.5            4700.0$
 5. WR      Jamison Crowder               WR    NYJ            NO@NYJ   10.4           5500.0$
 6. WR      Tyreek Hill                   WR    KC             LV@KC    15.1           8700.0$
 7. TE      Foster Moreau                 TE    LV             LV@KC    9.4            5200.0$
 8. FLEX    James Robinson                RB    JAC            JAC@TEN  13.1           6400.0$
 9. DEF     Buffalo Bills                 D     BUF            BUF@TB   9.583          4000.0$

Fantasy Points 121.08
Salary 60000.00

 1. QB      Patrick Mahomes               QB    KC             LV@KC    21.6           8500.0$
 2. RB      Javonte Williams              RB    DEN            DET@DEN  15.5           6700.0$
 3. RB      Josh Jacobs                   RB    LV             LV@KC    15.2           7100.0$
 4. WR      Ja'Marr Chase                 WR    CIN            SF@CIN   13.8           7200.0$
 5. WR      Jamison Crowder               WR    NYJ            NO@NYJ   10.4           5500.0$
 6. WR      Tyreek Hill                   WR    KC             LV@KC    15.1           8700.0$
 7. TE      George Kittle                 TE    SF             SF@CIN   14.1           7100.0$
 8. FLEX    Ty Johnson                    RB    NYJ            NO@NYJ   10.5           4900.0$
 9. DEF     Buffalo Bills                 D     BUF            BUF@TB   9.583          4000.0$

Fantasy Points 125.78
Salary 59700.00

 1. QB      Lamar Jackson                 QB    BAL            BAL@CLE  21.0           7900.0$
 2. RB      Ezekiel Elliott               RB    DAL            DAL@WAS  13.7           6900.0$
 3. RB      James Robinson                RB    JAC            JAC@TEN  13.1           6400.0$
 4. WR      Chris Godwin                  WR    TB             BUF@TB   14.2           7700.0$
 5. WR      Mike Evans                    WR    TB             BUF@TB   11.5           7200.0$
 6. WR      Mike Williams                 WR    LAC            NYG@LAC  12.9           6900.0$
 7. TE      Foster Moreau                 TE    LV             LV@KC    9.4            5200.0$
 8. FLEX    Leonard Fournette             RB    TB             BUF@TB   15.2           7600.0$
 9. DEF     Dallas Cowboys                D     DAL            DAL@WAS  9.75           4200.0$

Fantasy Points 120.75
Salary 60000.00

 1. QB      Dak Prescott                  QB    DAL            DAL@WAS  21.0           8100.0$
 2. RB      Javonte Williams              RB    DEN            DET@DEN  15.5           6700.0$
 3. RB      Josh Jacobs                   RB    LV             LV@KC    15.2           7100.0$
 4. WR      CeeDee Lamb                   WR    DAL            DAL@WAS  12.9           7800.0$
 5. WR      Ja'Marr Chase                 WR    CIN            SF@CIN   13.8           7200.0$
 6. WR      Mike Williams                 WR    LAC            NYG@LAC  12.9           6900.0$
 7. TE      George Kittle                 TE    SF             SF@CIN   14.1           7100.0$
 8. FLEX    Ty Johnson                    RB    NYJ            NO@NYJ   10.5           4900.0$
 9. DEF     Dallas Cowboys                D     DAL            DAL@WAS  9.75           4200.0$

Fantasy Points 125.65
Salary 60000.00

 1. QB      Dak Prescott                  QB    DAL            DAL@WAS  21.0           8100.0$
 2. RB      James Robinson                RB    JAC            JAC@TEN  13.1           6400.0$
 3. RB      Javonte Williams              RB    DEN            DET@DEN  15.5           6700.0$
 4. WR      CeeDee Lamb                   WR    DAL            DAL@WAS  12.9           7800.0$
 5. WR      Ja'Marr Chase                 WR    CIN            SF@CIN   13.8           7200.0$
 6. WR      Jamison Crowder               WR    NYJ            NO@NYJ   10.4           5500.0$
 7. TE      George Kittle                 TE    SF             SF@CIN   14.1           7100.0$
 8. FLEX    Josh Jacobs                   RB    LV             LV@KC    15.2           7100.0$
 9. DEF     Buffalo Bills                 D     BUF            BUF@TB   9.583          4000.0$

Fantasy Points 125.58
Salary 59900.00

 1. QB      Patrick Mahomes               QB    KC             LV@KC    21.6           8500.0$
 2. RB      Austin Ekeler                 RB    LAC            NYG@LAC  18.4           9200.0$
 3. RB      Ezekiel Elliott               RB    DAL            DAL@WAS  13.7           6900.0$
 4. WR      Jamison Crowder               WR    NYJ            NO@NYJ   10.4           5500.0$
 5. WR      Mike Williams                 WR    LAC            NYG@LAC  12.9           6900.0$
 6. WR      Tyreek Hill                   WR    KC             LV@KC    15.1           8700.0$
 7. TE      Foster Moreau                 TE    LV             LV@KC    9.4            5200.0$
 8. FLEX    Ty Johnson                    RB    NYJ            NO@NYJ   10.5           4900.0$
 9. DEF     Dallas Cowboys                D     DAL            DAL@WAS  9.75           4200.0$

Fantasy Points 121.75
Salary 60000.00

 1. QB      Lamar Jackson                 QB    BAL            BAL@CLE  21.0           7900.0$
 2. RB      Javonte Williams              RB    DEN            DET@DEN  15.5           6700.0$
 3. RB      Josh Jacobs                   RB    LV             LV@KC    15.2           7100.0$
 4. WR      Chris Godwin                  WR    TB             BUF@TB   14.2           7700.0$
 5. WR      Ja'Marr Chase                 WR    CIN            SF@CIN   13.8           7200.0$
 6. WR      Mike Evans                    WR    TB             BUF@TB   11.5           7200.0$
 7. TE      George Kittle                 TE    SF             SF@CIN   14.1           7100.0$
 8. FLEX    Ty Johnson                    RB    NYJ            NO@NYJ   10.5           4900.0$
 9. DEF     Dallas Cowboys                D     DAL            DAL@WAS  9.75           4200.0$

Fantasy Points 125.55
Salary 60000.00