In [1]:
from functions.nfl_clean_data import archive_files
archive_files()

/home/micheal/code/fan_fact/lineupopt/data/nfl/FanDuel-NFL-2021 ET-10 ET-24 ET-65523-players-list.csv
/home/micheal/code/fan_fact/lineupopt/data/nfl/FDprojections.csv
/home/micheal/code/fan_fact/lineupopt/data/nfl/fd_result.csv

In [3]:
import pandas as pd
import numpy as np
#from functions.nfl_proj_scape import nfl_proj_scape

stats_df = nfl_proj_scape()
stats_df.head()

In [6]:
df_fd = pd.read_csv('data/nfl/FanDuel-NFL-2021 ET-10 ET-24 ET-65656-players-list.csv')

In [7]:
#df_fd = pd.merge(df_fd, stats_df, how='left', on='Nickname')
df_fd.head()

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
0,65656-89675,RB,Jonathan,Jonathan Taylor,Taylor,15.0,6.0,15000,IND@SF,IND,SF,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
1,65656-149696,QB,Trey,Trey Lance,Lance,0.0,4.0,14500,IND@SF,SF,IND,O,Knee,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
2,65656-54604,QB,Jimmy,Jimmy Garoppolo,Garoppolo,12.0,4.0,14500,IND@SF,SF,IND,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
3,65656-70324,QB,Carson,Carson Wentz,Wentz,16.0,6.0,14000,IND@SF,IND,SF,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
4,65656-56018,WR,Deebo,Deebo Samuel,Samuel,17.0,5.0,13000,IND@SF,SF,IND,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX

In [8]:
df_fd.columns

Index(['Id', 'Position', 'First Name', 'Nickname', 'Last Name', 'FPPG',
       'Played', 'Salary', 'Game', 'Team', 'Opponent', 'Injury Indicator',
       'Injury Details', 'Tier', 'Unnamed: 14', 'Unnamed: 15',
       'Roster Position'],
      dtype='object')

In [9]:
#df.drop(df.dropna(subset=['columnA']).index)
df_fd = df_fd.drop(df_fd.dropna(subset=['Injury Indicator']).index)
#df_fd = df_fd.query("Position != 'QB' or Nickname == 'Tom Brady' or Nickname == 'Jalen Hurts'")
df_fd.head()

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
0,65656-89675,RB,Jonathan,Jonathan Taylor,Taylor,15.0,6.0,15000,IND@SF,IND,SF,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
2,65656-54604,QB,Jimmy,Jimmy Garoppolo,Garoppolo,12.0,4.0,14500,IND@SF,SF,IND,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
3,65656-70324,QB,Carson,Carson Wentz,Wentz,16.0,6.0,14000,IND@SF,IND,SF,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
4,65656-56018,WR,Deebo,Deebo Samuel,Samuel,17.0,5.0,13000,IND@SF,SF,IND,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
5,65656-69213,WR,Michael,Michael Pittman Jr.,Pittman Jr.,11.0,6.0,12000,IND@SF,IND,SF,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX

In [10]:
#df_fd = df_fd.merge(proj_df, how='left', left_on='Nickname', right_on='Player')
df_fd.head(3)

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
0,65656-89675,RB,Jonathan,Jonathan Taylor,Taylor,15.0,6.0,15000,IND@SF,IND,SF,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
2,65656-54604,QB,Jimmy,Jimmy Garoppolo,Garoppolo,12.0,4.0,14500,IND@SF,SF,IND,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
3,65656-70324,QB,Carson,Carson Wentz,Wentz,16.0,6.0,14000,IND@SF,IND,SF,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX

In [11]:
# df_fd["FPPG"] = df_fd["FPTS"]
# df_fd.drop(labels = ["Player", "FPTS"], axis=1, inplace=True)
df_fd.head(3)

,Id,Position,First Name,Nickname,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position
0,65656-89675,RB,Jonathan,Jonathan Taylor,Taylor,15.0,6.0,15000,IND@SF,IND,SF,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
2,65656-54604,QB,Jimmy,Jimmy Garoppolo,Garoppolo,12.0,4.0,14500,IND@SF,SF,IND,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX
3,65656-70324,QB,Carson,Carson Wentz,Wentz,16.0,6.0,14000,IND@SF,IND,SF,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX

df_fd.set_index('Id',inplace=True)

In [12]:
df_fd.to_csv('data/nfl/FDprojectionsSD.csv')

In [14]:
from pydfs_lineup_optimizer import Site, Sport, get_optimizer, PlayerFilter, AfterEachExposureStrategy

optimizer = get_optimizer(Site.FANDUEL_SINGLE_GAME, Sport.FOOTBALL)
optimizer.load_players_from_csv("data/nfl/FDprojectionsSD.csv")
for lineup in optimizer.optimize(10, max_exposure=0.5, exposure_strategy=AfterEachExposureStrategy):
    print(lineup)
optimizer.export('data/nfl/fd_resultSD.csv')

 1. MVP     Deebo Samuel                  WR    SF             IND@SF   25.5           13000.0$
 2. UTIL    Carson Wentz                  QB    IND            IND@SF   16.0           14000.0$
 3. UTIL    Jack Doyle                    TE    IND            IND@SF   6.0            6000.0$
 4. UTIL    Jonathan Taylor               RB    IND            IND@SF   15.0           15000.0$
 5. UTIL    Michael Pittman Jr.           WR    IND            IND@SF   11.0           12000.0$

Fantasy Points 73.50
Salary 60000.00

 1. MVP     Carson Wentz                  QB    IND            IND@SF   24.0           14000.0$
 2. UTIL    Deebo Samuel                  WR    SF             IND@SF   17.0           13000.0$
 3. UTIL    Jimmy Garoppolo               QB    SF             IND@SF   12.0           14500.0$
 4. UTIL    Trey Sermon                   RB    SF             IND@SF   6.0            7500.0$
 5. UTIL    Zach Pascal                   WR    IND            IND@SF   8.0            10000.0$

Fantasy Points 67.00
Salary 59000.00

 1. MVP     Jonathan Taylor               RB    IND            IND@SF   22.5           15000.0$
 2. UTIL    Eli Mitchell                  RB    SF             IND@SF   8.0            11000.0$
 3. UTIL    Joey Slye                     K     SF             IND@SF   6.75           9500.0$
 4. UTIL    Mo Alie-Cox                   TE    IND            IND@SF   6.0            7500.0$
 5. UTIL    Nyheim Hines                  RB    IND            IND@SF   6.0            8000.0$

Fantasy Points 49.25
Salary 51000.00

 1. MVP     Carson Wentz                  QB    IND            IND@SF   24.0           14000.0$
 2. UTIL    Deebo Samuel                  WR    SF             IND@SF   17.0           13000.0$
 3. UTIL    Jack Doyle                    TE    IND            IND@SF   6.0            6000.0$
 4. UTIL    Jonathan Taylor               RB    IND            IND@SF   15.0           15000.0$
 5. UTIL    Michael Pittman Jr.           WR    IND            IND@SF   11.0           12000.0$

Fantasy Points 73.00
Salary 60000.00

 1. MVP     Deebo Samuel                  WR    SF             IND@SF   25.5           13000.0$
 2. UTIL    Carson Wentz                  QB    IND            IND@SF   16.0           14000.0$
 3. UTIL    Jimmy Garoppolo               QB    SF             IND@SF   12.0           14500.0$
 4. UTIL    Trey Sermon                   RB    SF             IND@SF   6.0            7500.0$
 5. UTIL    Zach Pascal                   WR    IND            IND@SF   8.0            10000.0$

Fantasy Points 67.50
Salary 59000.00

 1. MVP     Jonathan Taylor               RB    IND            IND@SF   22.5           15000.0$
 2. UTIL    Carson Wentz                  QB    IND            IND@SF   16.0           14000.0$
 3. UTIL    Deebo Samuel                  WR    SF             IND@SF   17.0           13000.0$
 4. UTIL    Jack Doyle                    TE    IND            IND@SF   6.0            6000.0$
 5. UTIL    Michael Pittman Jr.           WR    IND            IND@SF   11.0           12000.0$

Fantasy Points 72.50
Salary 60000.00

 1. MVP     Deebo Samuel                  WR    SF             IND@SF   25.5           13000.0$
 2. UTIL    Jimmy Garoppolo               QB    SF             IND@SF   12.0           14500.0$
 3. UTIL    Jonathan Taylor               RB    IND            IND@SF   15.0           15000.0$
 4. UTIL    Trey Sermon                   RB    SF             IND@SF   6.0            7500.0$
 5. UTIL    Zach Pascal                   WR    IND            IND@SF   8.0            10000.0$

Fantasy Points 66.50
Salary 60000.00

 1. MVP     Deebo Samuel                  WR    SF             IND@SF   25.5           13000.0$
 2. UTIL    Carson Wentz                  QB    IND            IND@SF   16.0           14000.0$
 3. UTIL    JaMycal Hasty                 RB    SF             IND@SF   4.0            6000.0$
 4. UTIL    Jonathan Taylor               RB    IND            IND@SF   15.0           15000.0$
 5. UTIL    Michael Pittman Jr.           WR    IND            IND@SF   11.0           12000.0$

Fantasy Points 71.50
Salary 60000.00

 1. MVP     Carson Wentz                  QB    IND            IND@SF   24.0           14000.0$
 2. UTIL    Deebo Samuel                  WR    SF             IND@SF   17.0           13000.0$
 3. UTIL    Jack Doyle                    TE    IND            IND@SF   6.0            6000.0$
 4. UTIL    Jimmy Garoppolo               QB    SF             IND@SF   12.0           14500.0$
 5. UTIL    Zach Pascal                   WR    IND            IND@SF   8.0            10000.0$

Fantasy Points 67.00
Salary 57500.00

 1. MVP     Deebo Samuel                  WR    SF             IND@SF   25.5           13000.0$
 2. UTIL    Carson Wentz                  QB    IND            IND@SF   16.0           14000.0$
 3. UTIL    Jonathan Taylor               RB    IND            IND@SF   15.0           15000.0$
 4. UTIL    Kyle Juszczyk                 RB    SF             IND@SF   4.0            5500.0$
 5. UTIL    Michael Pittman Jr.           WR    IND            IND@SF   11.0           12000.0$

Fantasy Points 71.50
Salary 59500.00